// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export class TokensAuthorize extends pulumi.CustomResource {
    /**
     * Get an existing TokensAuthorize resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): TokensAuthorize {
        return new TokensAuthorize(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fly-machines:tokens/v1:TokensAuthorize';

    /**
     * Returns true if the given object is an instance of TokensAuthorize.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TokensAuthorize {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TokensAuthorize.__pulumiType;
    }

    declare public readonly access: pulumi.Output<outputs.tokens.v1.FlyioAccess | undefined>;
    declare public readonly header: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly verifiedToken: pulumi.Output<outputs.tokens.v1.RootVerifiedToken | undefined>;

    /**
     * Create a TokensAuthorize resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TokensAuthorizeArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["access"] = args?.access;
            resourceInputs["header"] = args?.header;
            resourceInputs["verifiedToken"] = undefined /*out*/;
        } else {
            resourceInputs["access"] = undefined /*out*/;
            resourceInputs["header"] = undefined /*out*/;
            resourceInputs["verifiedToken"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TokensAuthorize.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a TokensAuthorize resource.
 */
export interface TokensAuthorizeArgs {
    access?: pulumi.Input<inputs.tokens.v1.MainTokenAccessArgs | undefined>;
    header?: pulumi.Input<string | undefined>;
}
