// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TokensAuthorize struct {
	pulumi.CustomResourceState

	Access        FlyioAccessPtrOutput       `pulumi:"access"`
	Header        pulumi.StringPtrOutput     `pulumi:"header"`
	VerifiedToken RootVerifiedTokenPtrOutput `pulumi:"verifiedToken"`
}

// NewTokensAuthorize registers a new resource with the given unique name, arguments, and options.
func NewTokensAuthorize(ctx *pulumi.Context,
	name string, args *TokensAuthorizeArgs, opts ...pulumi.ResourceOption) (*TokensAuthorize, error) {
	if args == nil {
		args = &TokensAuthorizeArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource TokensAuthorize
	err := ctx.RegisterResource("fly-machines:tokens/v1:TokensAuthorize", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTokensAuthorize gets an existing TokensAuthorize resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTokensAuthorize(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TokensAuthorizeState, opts ...pulumi.ResourceOption) (*TokensAuthorize, error) {
	var resource TokensAuthorize
	err := ctx.ReadResource("fly-machines:tokens/v1:TokensAuthorize", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering TokensAuthorize resources.
type tokensAuthorizeState struct {
}

type TokensAuthorizeState struct {
}

func (TokensAuthorizeState) ElementType() reflect.Type {
	return reflect.TypeOf((*tokensAuthorizeState)(nil)).Elem()
}

type tokensAuthorizeArgs struct {
	Access *MainTokenAccess `pulumi:"access"`
	Header *string          `pulumi:"header"`
}

// The set of arguments for constructing a TokensAuthorize resource.
type TokensAuthorizeArgs struct {
	Access MainTokenAccessPtrInput
	Header pulumi.StringPtrInput
}

func (TokensAuthorizeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*tokensAuthorizeArgs)(nil)).Elem()
}

type TokensAuthorizeInput interface {
	pulumi.Input

	ToTokensAuthorizeOutput() TokensAuthorizeOutput
	ToTokensAuthorizeOutputWithContext(ctx context.Context) TokensAuthorizeOutput
}

func (*TokensAuthorize) ElementType() reflect.Type {
	return reflect.TypeOf((**TokensAuthorize)(nil)).Elem()
}

func (i *TokensAuthorize) ToTokensAuthorizeOutput() TokensAuthorizeOutput {
	return i.ToTokensAuthorizeOutputWithContext(context.Background())
}

func (i *TokensAuthorize) ToTokensAuthorizeOutputWithContext(ctx context.Context) TokensAuthorizeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TokensAuthorizeOutput)
}

type TokensAuthorizeOutput struct{ *pulumi.OutputState }

func (TokensAuthorizeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**TokensAuthorize)(nil)).Elem()
}

func (o TokensAuthorizeOutput) ToTokensAuthorizeOutput() TokensAuthorizeOutput {
	return o
}

func (o TokensAuthorizeOutput) ToTokensAuthorizeOutputWithContext(ctx context.Context) TokensAuthorizeOutput {
	return o
}

func (o TokensAuthorizeOutput) Access() FlyioAccessPtrOutput {
	return o.ApplyT(func(v *TokensAuthorize) FlyioAccessPtrOutput { return v.Access }).(FlyioAccessPtrOutput)
}

func (o TokensAuthorizeOutput) Header() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *TokensAuthorize) pulumi.StringPtrOutput { return v.Header }).(pulumi.StringPtrOutput)
}

func (o TokensAuthorizeOutput) VerifiedToken() RootVerifiedTokenPtrOutput {
	return o.ApplyT(func(v *TokensAuthorize) RootVerifiedTokenPtrOutput { return v.VerifiedToken }).(RootVerifiedTokenPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TokensAuthorizeInput)(nil)).Elem(), &TokensAuthorize{})
	pulumi.RegisterOutputType(TokensAuthorizeOutput{})
}
