// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

export class App extends pulumi.CustomResource {
    /**
     * Get an existing App resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): App {
        return new App(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fly-machines:apps/v1:App';

    /**
     * Returns true if the given object is an instance of App.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is App {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === App.__pulumiType;
    }

    declare public /*out*/ readonly createdAt: pulumi.Output<number | undefined>;
    declare public readonly enableSubdomains: pulumi.Output<boolean | undefined>;
    /**
     * When set, makes a retry of this exact request safe: a
     * second create with the same key and the same name (or no name) returns
     * the app the first request created, instead of erroring on a false name
     * conflict or creating a duplicate. A second create with the same key
     * but a *different* name is rejected outright; it won't silently
     * hand back the first app.
     */
    declare public readonly idempotencyKey: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string | undefined>;
    declare public readonly network: pulumi.Output<string | undefined>;
    declare public readonly orgSlug: pulumi.Output<string | undefined>;

    /**
     * Create a App resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: AppArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["enableSubdomains"] = args?.enableSubdomains;
            resourceInputs["idempotencyKey"] = args?.idempotencyKey;
            resourceInputs["name"] = args?.name;
            resourceInputs["network"] = args?.network;
            resourceInputs["orgSlug"] = args?.orgSlug;
            resourceInputs["createdAt"] = undefined /*out*/;
        } else {
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["enableSubdomains"] = undefined /*out*/;
            resourceInputs["idempotencyKey"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["network"] = undefined /*out*/;
            resourceInputs["orgSlug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(App.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a App resource.
 */
export interface AppArgs {
    enableSubdomains?: pulumi.Input<boolean | undefined>;
    /**
     * When set, makes a retry of this exact request safe: a
     * second create with the same key and the same name (or no name) returns
     * the app the first request created, instead of erroring on a false name
     * conflict or creating a duplicate. A second create with the same key
     * but a *different* name is rejected outright; it won't silently
     * hand back the first app.
     */
    idempotencyKey?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    network?: pulumi.Input<string | undefined>;
    orgSlug?: pulumi.Input<string | undefined>;
}
