// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getSecretkey(args: GetSecretkeyArgs, opts?: pulumi.InvokeOptions): Promise<GetSecretkeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:apps/v1:getSecretkey", {
        "appName": args.appName,
        "queryParams": args.queryParams,
        "secretName": args.secretName,
    }, opts);
}

export interface GetSecretkeyArgs {
    /**
     * Fly App Name
     */
    appName: string;
    /**
     * Query params to send with the API request.
     */
    queryParams?: inputs.apps.v1.GetSecretkeyQueryParams;
    /**
     * Secret key name
     */
    secretName: string;
}

export interface GetSecretkeyResult {
    readonly createdAt?: string;
    readonly name?: string;
    readonly publicKey?: number[];
    readonly type?: string;
    readonly updatedAt?: string;
}
export function getSecretkeyOutput(args: GetSecretkeyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetSecretkeyResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:apps/v1:getSecretkey", {
        "appName": args.appName,
        "queryParams": args.queryParams,
        "secretName": args.secretName,
    }, opts);
}

export interface GetSecretkeyOutputArgs {
    /**
     * Fly App Name
     */
    appName: pulumi.Input<string>;
    /**
     * Query params to send with the API request.
     */
    queryParams?: pulumi.Input<inputs.apps.v1.GetSecretkeyQueryParamsArgs | undefined>;
    /**
     * Secret key name
     */
    secretName: pulumi.Input<string>;
}
