// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getVolume(args: GetVolumeArgs, opts?: pulumi.InvokeOptions): Promise<GetVolumeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:apps/v1:getVolume", {
        "appName": args.appName,
        "queryParams": args.queryParams,
        "volumeId": args.volumeId,
    }, opts);
}

export interface GetVolumeArgs {
    /**
     * Fly App Name
     */
    appName: string;
    /**
     * Query params to send with the API request.
     */
    queryParams?: inputs.apps.v1.GetVolumeQueryParams;
    /**
     * Volume ID
     */
    volumeId: string;
}

export interface GetVolumeResult {
    readonly attachedAllocId?: string;
    readonly attachedMachineId?: string;
    readonly autoBackupEnabled?: boolean;
    readonly blockSize?: number;
    readonly blocks?: number;
    readonly blocksAvail?: number;
    readonly blocksFree?: number;
    readonly bytesTotal?: number;
    readonly bytesUsed?: number;
    readonly createdAt?: string;
    readonly encrypted?: boolean;
    readonly fstype?: string;
    readonly hostFeatures?: string[];
    readonly hostStatus?: enums.apps.v1.VolumeHostStatus;
    readonly id?: string;
    readonly name?: string;
    readonly region?: string;
    readonly requiredHostFeatures?: string[];
    readonly sizeGb?: number;
    readonly snapshotRetention?: number;
    readonly state?: string;
    readonly type?: enums.apps.v1.VolumeType;
    readonly zone?: string;
}
export function getVolumeOutput(args: GetVolumeOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVolumeResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:apps/v1:getVolume", {
        "appName": args.appName,
        "queryParams": args.queryParams,
        "volumeId": args.volumeId,
    }, opts);
}

export interface GetVolumeOutputArgs {
    /**
     * Fly App Name
     */
    appName: pulumi.Input<string>;
    /**
     * Query params to send with the API request.
     */
    queryParams?: pulumi.Input<inputs.apps.v1.GetVolumeQueryParamsArgs | undefined>;
    /**
     * Volume ID
     */
    volumeId: pulumi.Input<string>;
}
