// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listApps(args: ListAppsArgs, opts?: pulumi.InvokeOptions): Promise<ListAppsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:apps/v1:listApps", {
        "queryParams": args.queryParams,
    }, opts);
}

export interface ListAppsArgs {
    /**
     * Query params to send with the API request.
     */
    queryParams: inputs.apps.v1.ListAppsQueryParams;
}

export interface ListAppsResult {
    readonly apps?: outputs.apps.v1.App[];
    /**
     * Pagination cursor for the next page. Absent when no more apps remain.
     * Cursors expire 30 minutes after the first page was requested.
     */
    readonly nextCursor?: string;
    /**
     * The number of apps matching the request, across all pages. When
     * paginating, it is counted once when the first page is requested and not
     * updated afterwards, so it may differ slightly from the number of apps
     * returned: it excludes apps created later and includes apps deleted while
     * paginating. Apps created in the seconds before the first page may also be
     * counted but missing from the pages.
     */
    readonly totalApps?: number;
}
export function listAppsOutput(args: ListAppsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListAppsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:apps/v1:listApps", {
        "queryParams": args.queryParams,
    }, opts);
}

export interface ListAppsOutputArgs {
    /**
     * Query params to send with the API request.
     */
    queryParams: pulumi.Input<inputs.apps.v1.ListAppsQueryParamsArgs>;
}
