// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listSecretkeys(args: ListSecretkeysArgs, opts?: pulumi.InvokeOptions): Promise<ListSecretkeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:apps/v1:listSecretkeys", {
        "appName": args.appName,
    }, opts);
}

export interface ListSecretkeysArgs {
    /**
     * Fly App Name
     */
    appName: string;
}

export interface ListSecretkeysResult {
    readonly secretKeys?: outputs.apps.v1.SecretKey[];
}
export function listSecretkeysOutput(args: ListSecretkeysOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListSecretkeysResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:apps/v1:listSecretkeys", {
        "appName": args.appName,
    }, opts);
}

export interface ListSecretkeysOutputArgs {
    /**
     * Fly App Name
     */
    appName: pulumi.Input<string>;
}
