// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listMachines(args: ListMachinesArgs, opts?: pulumi.InvokeOptions): Promise<ListMachinesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:apps/v1:listMachines", {
        "appName": args.appName,
    }, opts);
}

export interface ListMachinesArgs {
    /**
     * Fly App Name
     */
    appName: string;
}

export interface ListMachinesResult {
    readonly items: outputs.apps.v1.Machine[];
}
export function listMachinesOutput(args: ListMachinesOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListMachinesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:apps/v1:listMachines", {
        "appName": args.appName,
    }, opts);
}

export interface ListMachinesOutputArgs {
    /**
     * Fly App Name
     */
    appName: pulumi.Input<string>;
}
