// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

export class MachinesLease extends pulumi.CustomResource {
    /**
     * Get an existing MachinesLease resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): MachinesLease {
        return new MachinesLease(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fly-machines:apps/v1:MachinesLease';

    /**
     * Returns true if the given object is an instance of MachinesLease.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MachinesLease {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MachinesLease.__pulumiType;
    }

    /**
     * Description or reason for the Lease.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid.
     */
    declare public /*out*/ readonly expiresAt: pulumi.Output<number | undefined>;
    /**
     * Nonce is the unique ID autogenerated and associated with the Lease.
     */
    declare public /*out*/ readonly nonce: pulumi.Output<string | undefined>;
    /**
     * Owner is the user identifier which acquired the Lease.
     */
    declare public /*out*/ readonly owner: pulumi.Output<string | undefined>;
    /**
     * seconds lease will be valid
     */
    declare public readonly ttl: pulumi.Output<number | undefined>;
    /**
     * Machine version
     */
    declare public /*out*/ readonly version: pulumi.Output<string | undefined>;

    /**
     * Create a MachinesLease resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: MachinesLeaseArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["appName"] = args?.appName;
            resourceInputs["description"] = args?.description;
            resourceInputs["machineId"] = args?.machineId;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["nonce"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        } else {
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["expiresAt"] = undefined /*out*/;
            resourceInputs["nonce"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["ttl"] = undefined /*out*/;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MachinesLease.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a MachinesLease resource.
 */
export interface MachinesLeaseArgs {
    /**
     * Fly App Name
     */
    appName?: pulumi.Input<string | undefined>;
    description?: pulumi.Input<string | undefined>;
    /**
     * Machine ID
     */
    machineId?: pulumi.Input<string | undefined>;
    /**
     * seconds lease will be valid
     */
    ttl?: pulumi.Input<number | undefined>;
}
