// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function getPlatformRegion(args?: GetPlatformRegionArgs, opts?: pulumi.InvokeOptions): Promise<GetPlatformRegionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:platform/v1:getPlatformRegion", {
        "queryParams": args.queryParams,
    }, opts);
}

export interface GetPlatformRegionArgs {
    /**
     * Query params to send with the API request.
     */
    queryParams?: inputs.platform.v1.GetPlatformRegionQueryParams;
}

export interface GetPlatformRegionResult {
    readonly nearest?: string;
    readonly regions?: outputs.platform.v1.MainRegionRow[];
}
export function getPlatformRegionOutput(args?: GetPlatformRegionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPlatformRegionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:platform/v1:getPlatformRegion", {
        "queryParams": args.queryParams,
    }, opts);
}

export interface GetPlatformRegionOutputArgs {
    /**
     * Query params to send with the API request.
     */
    queryParams?: pulumi.Input<inputs.platform.v1.GetPlatformRegionQueryParamsArgs | undefined>;
}
