// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { GetPlatformRegionArgs, GetPlatformRegionResult } from "./getPlatformRegion";
export const getPlatformRegion: typeof import("./getPlatformRegion").getPlatformRegion = null as any;
export const getPlatformRegionOutput: typeof import("./getPlatformRegion").getPlatformRegionOutput = null as any;
utilities.lazyLoad(exports, ["getPlatformRegion","getPlatformRegionOutput"], () => require("./getPlatformRegion"));

export { PlatformPlacementArgs } from "./platformPlacement";
export type PlatformPlacement = import("./platformPlacement").PlatformPlacement;
export const PlatformPlacement: typeof import("./platformPlacement").PlatformPlacement = null as any;
utilities.lazyLoad(exports, ["PlatformPlacement"], () => require("./platformPlacement"));


// Export enums:
export * from "../../types/enums/platform/v1";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "fly-machines:platform/v1:PlatformPlacement":
                return new PlatformPlacement(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fly-machines", "platform/v1", _module)
