// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class AcmeChallenge
    {
        public readonly string? Name;
        public readonly string? Target;

        [OutputConstructor]
        private AcmeChallenge(
            string? name,

            string? target)
        {
            Name = name;
            Target = target;
        }
    }
}
