// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class AppOrganizationInfo
    {
        public readonly int? InternalNumericId;
        public readonly string? Name;
        public readonly string? Slug;

        [OutputConstructor]
        private AppOrganizationInfo(
            int? internalNumericId,

            string? name,

            string? slug)
        {
            InternalNumericId = internalNumericId;
            Name = name;
            Slug = slug;
        }
    }
}
