// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// Unhealthy policy that determines what action to take if a container is deemed unhealthy
    /// </summary>
    [OutputType]
    public sealed class FlyContainerHealthcheckUnhealthy
    {
        [OutputConstructor]
        private FlyContainerHealthcheckUnhealthy()
        {
        }
    }
}
