// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// Restart is used to define the restart policy for the container.
    /// </summary>
    [OutputType]
    public sealed class FlyContainerConfigRestart
    {
        /// <summary>
        /// When policy is on-failure, the maximum number of times to attempt to restart the Machine before letting it stop.
        /// </summary>
        public readonly int? MaxRetries;
        /// <summary>
        /// * no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.
        /// * always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.
        /// * on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.
        /// </summary>
        public readonly Pulumi.FlyMachines.AppsV1.FlyMachineRestartPolicy? Policy;

        [OutputConstructor]
        private FlyContainerConfigRestart(
            int? maxRetries,

            Pulumi.FlyMachines.AppsV1.FlyMachineRestartPolicy? policy)
        {
            MaxRetries = maxRetries;
            Policy = policy;
        }
    }
}
