// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class FlyContainerConfig
    {
        /// <summary>
        /// CmdOverride is used to override the default command of the image.
        /// </summary>
        public readonly ImmutableArray<string> Cmd;
        /// <summary>
        /// DependsOn can be used to define dependencies between containers. The container will only be
        /// started after all of its dependent conditions have been satisfied.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlyContainerDependency> DependsOn;
        /// <summary>
        /// EntrypointOverride is used to override the default entrypoint of the image.
        /// </summary>
        public readonly ImmutableArray<string> Entrypoint;
        /// <summary>
        /// ExtraEnv is used to add additional environment variables to the container.
        /// </summary>
        public readonly object? Env;
        /// <summary>
        /// EnvFrom can be provided to set environment variables from machine fields.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlyEnvFrom> EnvFrom;
        /// <summary>
        /// Image Config overrides - these fields are used to override the image configuration.
        /// If not provided, the image configuration will be used.
        /// ExecOverride is used to override the default command of the image.
        /// </summary>
        public readonly ImmutableArray<string> Exec;
        /// <summary>
        /// Files are files that will be written to the container file system.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlyFile> Files;
        /// <summary>
        /// Healthchecks determine the health of your containers. Healthchecks can use HTTP, TCP or an Exec command.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlyContainerHealthcheck> Healthchecks;
        /// <summary>
        /// Image is the docker image to run.
        /// </summary>
        public readonly string? Image;
        /// <summary>
        /// Name is used to identify the container in the machine.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Restart is used to define the restart policy for the container.
        /// </summary>
        public readonly Outputs.FlyContainerConfigRestart? Restart;
        /// <summary>
        /// Secrets can be provided at the process level to explicitly indicate which secrets should be
        /// used for the process. If not provided, the secrets provided at the machine level will be used.
        /// </summary>
        public readonly ImmutableArray<Outputs.FlyMachineSecret> Secrets;
        /// <summary>
        /// Stop is used to define the signal and timeout for stopping the container.
        /// </summary>
        public readonly Outputs.FlyContainerConfigStop? Stop;
        /// <summary>
        /// UserOverride is used to override the default user of the image.
        /// </summary>
        public readonly string? User;

        [OutputConstructor]
        private FlyContainerConfig(
            ImmutableArray<string> cmd,

            ImmutableArray<Outputs.FlyContainerDependency> dependsOn,

            ImmutableArray<string> entrypoint,

            object? env,

            ImmutableArray<Outputs.FlyEnvFrom> envFrom,

            ImmutableArray<string> exec,

            ImmutableArray<Outputs.FlyFile> files,

            ImmutableArray<Outputs.FlyContainerHealthcheck> healthchecks,

            string? image,

            string? name,

            Outputs.FlyContainerConfigRestart? restart,

            ImmutableArray<Outputs.FlyMachineSecret> secrets,

            Outputs.FlyContainerConfigStop? stop,

            string? user)
        {
            Cmd = cmd;
            DependsOn = dependsOn;
            Entrypoint = entrypoint;
            Env = env;
            EnvFrom = envFrom;
            Exec = exec;
            Files = files;
            Healthchecks = healthchecks;
            Image = image;
            Name = name;
            Restart = restart;
            Secrets = secrets;
            Stop = stop;
            User = user;
        }
    }
}
