// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// A Secret needing to be set in the environment of the Machine. env_var is required
    /// </summary>
    [OutputType]
    public sealed class FlyMachineSecret
    {
        /// <summary>
        /// EnvVar is required and is the name of the environment variable that will be set from the
        /// secret. It must be a valid environment variable name.
        /// </summary>
        public readonly string? EnvVar;
        /// <summary>
        /// Name is optional and when provided is used to reference a secret name where the EnvVar is
        /// different from what was set as the secret name.
        /// </summary>
        public readonly string? Name;

        [OutputConstructor]
        private FlyMachineSecret(
            string? envVar,

            string? name)
        {
            EnvVar = envVar;
            Name = name;
        }
    }
}
