// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// For http checks, an array of objects with string field Name and array of strings field Values. The key/value pairs specify header and header values that will get passed with the check call.
    /// </summary>
    [OutputType]
    public sealed class FlyMachineHTTPHeader
    {
        /// <summary>
        /// The header name
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// The header value
        /// </summary>
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private FlyMachineHTTPHeader(
            string? name,

            ImmutableArray<string> values)
        {
            Name = name;
            Values = values;
        }
    }
}
