// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class ImageRef
    {
        public readonly string? Digest;
        public readonly object? Labels;
        public readonly string? Registry;
        public readonly string? Repository;
        public readonly string? Tag;

        [OutputConstructor]
        private ImageRef(
            string? digest,

            object? labels,

            string? registry,

            string? repository,

            string? tag)
        {
            Digest = digest;
            Labels = labels;
            Registry = registry;
            Repository = repository;
            Tag = tag;
        }
    }
}
