// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class IPAssignment
    {
        public readonly string? CreatedAt;
        public readonly bool? Egress;
        public readonly string? Ip;
        /// <summary>
        /// The 6PN network a Flycast (private_v6) address belongs to. Null for all other IP types.
        /// </summary>
        public readonly Outputs.IPAssignmentNetwork? Network;
        public readonly string? Region;
        public readonly string? ServiceName;
        public readonly bool? Shared;

        [OutputConstructor]
        private IPAssignment(
            string? createdAt,

            bool? egress,

            string? ip,

            Outputs.IPAssignmentNetwork? network,

            string? region,

            string? serviceName,

            bool? shared)
        {
            CreatedAt = createdAt;
            Egress = egress;
            Ip = ip;
            Network = network;
            Region = region;
            ServiceName = serviceName;
            Shared = shared;
        }
    }
}
