// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    [OutputType]
    public sealed class MachineQueryParams
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        public readonly Outputs.MachineCreateQueryParams? Create;
        /// <summary>
        /// Query params for the delete operation.
        /// </summary>
        public readonly Outputs.MachineDeleteQueryParams? Delete;
        /// <summary>
        /// Query params for the put operation.
        /// </summary>
        public readonly Outputs.MachinePutQueryParams? Put;
        /// <summary>
        /// Query params for the read operation.
        /// </summary>
        public readonly Outputs.MachineReadQueryParams? Read;

        [OutputConstructor]
        private MachineQueryParams(
            Outputs.MachineCreateQueryParams? create,

            Outputs.MachineDeleteQueryParams? delete,

            Outputs.MachinePutQueryParams? put,

            Outputs.MachineReadQueryParams? read)
        {
            Create = create;
            Delete = delete;
            Put = put;
            Read = read;
        }
    }
}
