// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// Query params for the API request.
    /// </summary>
    [OutputType]
    public sealed class MachinesRestartCreateQueryParams
    {
        /// <summary>
        /// Additional query params to send with the request that are not defined in the API spec.
        /// </summary>
        public readonly ImmutableDictionary<string, string>? AdditionalParams;
        /// <summary>
        /// Unix signal name
        /// </summary>
        public readonly Pulumi.FlyMachines.AppsV1.MachinesRestartCreateQueryParamsSignal? Signal;
        /// <summary>
        /// Restart timeout as a Go duration string or number of seconds
        /// </summary>
        public readonly string? Timeout;

        [OutputConstructor]
        private MachinesRestartCreateQueryParams(
            ImmutableDictionary<string, string>? additionalParams,

            Pulumi.FlyMachines.AppsV1.MachinesRestartCreateQueryParamsSignal? signal,

            string? timeout)
        {
            AdditionalParams = additionalParams;
            Signal = signal;
            Timeout = timeout;
        }
    }
}
