// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    [OutputType]
    public sealed class SecretkeyQueryParams
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        public readonly Outputs.SecretkeyCreateQueryParams? Create;
        /// <summary>
        /// Query params for the delete operation.
        /// </summary>
        public readonly Outputs.SecretkeyDeleteQueryParams? Delete;
        /// <summary>
        /// Query params for the read operation.
        /// </summary>
        public readonly Outputs.SecretkeyReadQueryParams? Read;

        [OutputConstructor]
        private SecretkeyQueryParams(
            Outputs.SecretkeyCreateQueryParams? create,

            Outputs.SecretkeyDeleteQueryParams? delete,

            Outputs.SecretkeyReadQueryParams? read)
        {
            Create = create;
            Delete = delete;
            Read = read;
        }
    }
}
