// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class StrippedLease
    {
        public readonly string? Description;
        public readonly int? ExpiresAt;
        public readonly string? Owner;

        [OutputConstructor]
        private StrippedLease(
            string? description,

            int? expiresAt,

            string? owner)
        {
            Description = description;
            ExpiresAt = expiresAt;
            Owner = owner;
        }
    }
}
