// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Outputs
{

    [OutputType]
    public sealed class Volume
    {
        public readonly string? AttachedAllocId;
        public readonly string? AttachedMachineId;
        public readonly bool? AutoBackupEnabled;
        public readonly int? BlockSize;
        public readonly int? Blocks;
        public readonly int? BlocksAvail;
        public readonly int? BlocksFree;
        public readonly int? BytesTotal;
        public readonly int? BytesUsed;
        public readonly string? CreatedAt;
        public readonly bool? Encrypted;
        public readonly string? Fstype;
        public readonly ImmutableArray<string> HostFeatures;
        public readonly Pulumi.FlyMachines.AppsV1.VolumeHostStatus? HostStatus;
        public readonly string? Id;
        public readonly string? Name;
        public readonly string? Region;
        public readonly ImmutableArray<string> RequiredHostFeatures;
        public readonly int? SizeGb;
        public readonly int? SnapshotRetention;
        public readonly string? State;
        public readonly Pulumi.FlyMachines.AppsV1.VolumeType? Type;
        public readonly string? Zone;

        [OutputConstructor]
        private Volume(
            string? attachedAllocId,

            string? attachedMachineId,

            bool? autoBackupEnabled,

            int? blockSize,

            int? blocks,

            int? blocksAvail,

            int? blocksFree,

            int? bytesTotal,

            int? bytesUsed,

            string? createdAt,

            bool? encrypted,

            string? fstype,

            ImmutableArray<string> hostFeatures,

            Pulumi.FlyMachines.AppsV1.VolumeHostStatus? hostStatus,

            string? id,

            string? name,

            string? region,

            ImmutableArray<string> requiredHostFeatures,

            int? sizeGb,

            int? snapshotRetention,

            string? state,

            Pulumi.FlyMachines.AppsV1.VolumeType? type,

            string? zone)
        {
            AttachedAllocId = attachedAllocId;
            AttachedMachineId = attachedMachineId;
            AutoBackupEnabled = autoBackupEnabled;
            BlockSize = blockSize;
            Blocks = blocks;
            BlocksAvail = blocksAvail;
            BlocksFree = blocksFree;
            BytesTotal = bytesTotal;
            BytesUsed = bytesUsed;
            CreatedAt = createdAt;
            Encrypted = encrypted;
            Fstype = fstype;
            HostFeatures = hostFeatures;
            HostStatus = hostStatus;
            Id = id;
            Name = name;
            Region = region;
            RequiredHostFeatures = requiredHostFeatures;
            SizeGb = sizeGb;
            SnapshotRetention = snapshotRetention;
            State = state;
            Type = type;
            Zone = zone;
        }
    }
}
