# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs

__all__ = [
    'ListPostgresExtensionsResult',
    'AwaitableListPostgresExtensionsResult',
    'list_postgres_extensions',
    'list_postgres_extensions_output',
]

@pulumi.output_type
class ListPostgresExtensionsResult:
    def __init__(__self__, data=None):
        if data and not isinstance(data, list):
            raise TypeError("Expected argument 'data' to be a list")
        pulumi.set(__self__, "data", data)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[Sequence['outputs.PostgresExtension']]:
        return pulumi.get(self, "data")


class AwaitableListPostgresExtensionsResult(ListPostgresExtensionsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListPostgresExtensionsResult(
            data=self.data)


def list_postgres_extensions(database_name: Optional[_builtins.str] = None,
                             postgres_cluster_id: Optional[_builtins.str] = None,
                             opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListPostgresExtensionsResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str database_name: Database Name
    :param _builtins.str postgres_cluster_id: Managed Postgres Cluster ID
    """
    __args__ = dict()
    __args__['databaseName'] = database_name
    __args__['postgresClusterId'] = postgres_cluster_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:postgres/v1:listPostgresExtensions', __args__, opts=opts, typ=ListPostgresExtensionsResult).value

    return AwaitableListPostgresExtensionsResult(
        data=pulumi.get(__ret__, 'data'))
def list_postgres_extensions_output(database_name: pulumi.Input[Optional[_builtins.str]] = None,
                                    postgres_cluster_id: pulumi.Input[Optional[_builtins.str]] = None,
                                    opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListPostgresExtensionsResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str database_name: Database Name
    :param _builtins.str postgres_cluster_id: Managed Postgres Cluster ID
    """
    __args__ = dict()
    __args__['databaseName'] = database_name
    __args__['postgresClusterId'] = postgres_cluster_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:postgres/v1:listPostgresExtensions', __args__, opts=opts, typ=ListPostgresExtensionsResult)
    return __ret__.apply(lambda __response__: ListPostgresExtensionsResult(
        data=pulumi.get(__response__, 'data')))
