# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = [
    'ListPostgresResult',
    'AwaitableListPostgresResult',
    'list_postgres',
    'list_postgres_output',
]

@pulumi.output_type
class ListPostgresResult:
    def __init__(__self__, data=None):
        if data and not isinstance(data, list):
            raise TypeError("Expected argument 'data' to be a list")
        pulumi.set(__self__, "data", data)

    @_builtins.property
    @pulumi.getter
    def data(self) -> Optional[Sequence['outputs.PostgresClusterSummary']]:
        return pulumi.get(self, "data")


class AwaitableListPostgresResult(ListPostgresResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListPostgresResult(
            data=self.data)


def list_postgres(query_params: Optional[Union['ListPostgresQueryParams', 'ListPostgresQueryParamsDict']] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListPostgresResult:
    """
    Use this data source to access information about an existing resource.

    :param Union['ListPostgresQueryParams', 'ListPostgresQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:postgres/v1:listPostgres', __args__, opts=opts, typ=ListPostgresResult).value

    return AwaitableListPostgresResult(
        data=pulumi.get(__ret__, 'data'))
def list_postgres_output(query_params: pulumi.Input[Optional[Union['ListPostgresQueryParams', 'ListPostgresQueryParamsDict']]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListPostgresResult]:
    """
    Use this data source to access information about an existing resource.

    :param Union['ListPostgresQueryParams', 'ListPostgresQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:postgres/v1:listPostgres', __args__, opts=opts, typ=ListPostgresResult)
    return __ret__.apply(lambda __response__: ListPostgresResult(
        data=pulumi.get(__response__, 'data')))
