// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPostgresQueriesActive(ctx *pulumi.Context, args *GetPostgresQueriesActiveArgs, opts ...pulumi.InvokeOption) (*GetPostgresQueriesActiveResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPostgresQueriesActiveResult
	err := ctx.Invoke("fly-machines:postgres/v1:getPostgresQueriesActive", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetPostgresQueriesActiveArgs struct {
	// Managed Postgres Cluster ID
	PostgresClusterId string `pulumi:"postgresClusterId"`
}

type GetPostgresQueriesActiveResult struct {
	Data []PostgresActiveQuery `pulumi:"data"`
}

func GetPostgresQueriesActiveOutput(ctx *pulumi.Context, args GetPostgresQueriesActiveOutputArgs, opts ...pulumi.InvokeOption) GetPostgresQueriesActiveResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:postgres/v1:getPostgresQueriesActive", args, GetPostgresQueriesActiveResultOutput{}, options).(GetPostgresQueriesActiveResultOutput)
}

type GetPostgresQueriesActiveOutputArgs struct {
	// Managed Postgres Cluster ID
	PostgresClusterId pulumi.StringInput `pulumi:"postgresClusterId"`
}

func (GetPostgresQueriesActiveOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPostgresQueriesActiveArgs)(nil)).Elem()
}

type GetPostgresQueriesActiveResultOutput struct{ *pulumi.OutputState }

func (GetPostgresQueriesActiveResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPostgresQueriesActiveResult)(nil)).Elem()
}

func (o GetPostgresQueriesActiveResultOutput) ToGetPostgresQueriesActiveResultOutput() GetPostgresQueriesActiveResultOutput {
	return o
}

func (o GetPostgresQueriesActiveResultOutput) ToGetPostgresQueriesActiveResultOutputWithContext(ctx context.Context) GetPostgresQueriesActiveResultOutput {
	return o
}

func (o GetPostgresQueriesActiveResultOutput) Data() PostgresActiveQueryArrayOutput {
	return o.ApplyT(func(v GetPostgresQueriesActiveResult) []PostgresActiveQuery { return v.Data }).(PostgresActiveQueryArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPostgresQueriesActiveResultOutput{})
}
