// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "fly-machines:postgres/v1:Postgres":
		r = &Postgres{}
	case "fly-machines:postgres/v1:PostgresAttachment":
		r = &PostgresAttachment{}
	case "fly-machines:postgres/v1:PostgresBackup":
		r = &PostgresBackup{}
	case "fly-machines:postgres/v1:PostgresDatabase":
		r = &PostgresDatabase{}
	case "fly-machines:postgres/v1:PostgresExtension":
		r = &PostgresExtension{}
	case "fly-machines:postgres/v1:PostgresFork":
		r = &PostgresFork{}
	case "fly-machines:postgres/v1:PostgresRestore":
		r = &PostgresRestore{}
	case "fly-machines:postgres/v1:PostgresUser":
		r = &PostgresUser{}
	case "fly-machines:postgres/v1:PostgresUsersRotatePassword":
		r = &PostgresUsersRotatePassword{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"fly-machines",
		"postgres/v1",
		&module{version},
	)
}
