// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PostgresFork struct {
	pulumi.CustomResourceState

	Data PostgresClusterPtrOutput `pulumi:"data"`
	// Name for the forked cluster. Defaults to the source name with a -fork suffix.
	Name pulumi.StringPtrOutput `pulumi:"name"`
}

// NewPostgresFork registers a new resource with the given unique name, arguments, and options.
func NewPostgresFork(ctx *pulumi.Context,
	name string, args *PostgresForkArgs, opts ...pulumi.ResourceOption) (*PostgresFork, error) {
	if args == nil {
		args = &PostgresForkArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PostgresFork
	err := ctx.RegisterResource("fly-machines:postgres/v1:PostgresFork", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPostgresFork gets an existing PostgresFork resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPostgresFork(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PostgresForkState, opts ...pulumi.ResourceOption) (*PostgresFork, error) {
	var resource PostgresFork
	err := ctx.ReadResource("fly-machines:postgres/v1:PostgresFork", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PostgresFork resources.
type postgresForkState struct {
}

type PostgresForkState struct {
}

func (PostgresForkState) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresForkState)(nil)).Elem()
}

type postgresForkArgs struct {
	// Name for the forked cluster. Defaults to the source name with a -fork suffix.
	Name *string `pulumi:"name"`
	// Managed Postgres Cluster ID
	PostgresClusterId *string `pulumi:"postgresClusterId"`
}

// The set of arguments for constructing a PostgresFork resource.
type PostgresForkArgs struct {
	// Name for the forked cluster. Defaults to the source name with a -fork suffix.
	Name pulumi.StringPtrInput
	// Managed Postgres Cluster ID
	PostgresClusterId pulumi.StringPtrInput
}

func (PostgresForkArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresForkArgs)(nil)).Elem()
}

type PostgresForkInput interface {
	pulumi.Input

	ToPostgresForkOutput() PostgresForkOutput
	ToPostgresForkOutputWithContext(ctx context.Context) PostgresForkOutput
}

func (*PostgresFork) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresFork)(nil)).Elem()
}

func (i *PostgresFork) ToPostgresForkOutput() PostgresForkOutput {
	return i.ToPostgresForkOutputWithContext(context.Background())
}

func (i *PostgresFork) ToPostgresForkOutputWithContext(ctx context.Context) PostgresForkOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresForkOutput)
}

type PostgresForkOutput struct{ *pulumi.OutputState }

func (PostgresForkOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresFork)(nil)).Elem()
}

func (o PostgresForkOutput) ToPostgresForkOutput() PostgresForkOutput {
	return o
}

func (o PostgresForkOutput) ToPostgresForkOutputWithContext(ctx context.Context) PostgresForkOutput {
	return o
}

func (o PostgresForkOutput) Data() PostgresClusterPtrOutput {
	return o.ApplyT(func(v *PostgresFork) PostgresClusterPtrOutput { return v.Data }).(PostgresClusterPtrOutput)
}

// Name for the forked cluster. Defaults to the source name with a -fork suffix.
func (o PostgresForkOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostgresFork) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresForkInput)(nil)).Elem(), &PostgresFork{})
	pulumi.RegisterOutputType(PostgresForkOutput{})
}
