// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"errors"
	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PostgresAttachment struct {
	pulumi.CustomResourceState

	// Name of the Fly app to attach.
	AppName pulumi.StringOutput             `pulumi:"appName"`
	Data    PostgresAttachmentTypePtrOutput `pulumi:"data"`
}

// NewPostgresAttachment registers a new resource with the given unique name, arguments, and options.
func NewPostgresAttachment(ctx *pulumi.Context,
	name string, args *PostgresAttachmentArgs, opts ...pulumi.ResourceOption) (*PostgresAttachment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AppName == nil {
		return nil, errors.New("invalid value for required argument 'AppName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PostgresAttachment
	err := ctx.RegisterResource("fly-machines:postgres/v1:PostgresAttachment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPostgresAttachment gets an existing PostgresAttachment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPostgresAttachment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PostgresAttachmentState, opts ...pulumi.ResourceOption) (*PostgresAttachment, error) {
	var resource PostgresAttachment
	err := ctx.ReadResource("fly-machines:postgres/v1:PostgresAttachment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PostgresAttachment resources.
type postgresAttachmentState struct {
}

type PostgresAttachmentState struct {
}

func (PostgresAttachmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresAttachmentState)(nil)).Elem()
}

type postgresAttachmentArgs struct {
	// Name of the Fly app to attach.
	AppName string `pulumi:"appName"`
	// Managed Postgres Cluster ID
	PostgresClusterId *string `pulumi:"postgresClusterId"`
}

// The set of arguments for constructing a PostgresAttachment resource.
type PostgresAttachmentArgs struct {
	// Name of the Fly app to attach.
	AppName pulumi.StringInput
	// Managed Postgres Cluster ID
	PostgresClusterId pulumi.StringPtrInput
}

func (PostgresAttachmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresAttachmentArgs)(nil)).Elem()
}

type PostgresAttachmentInput interface {
	pulumi.Input

	ToPostgresAttachmentOutput() PostgresAttachmentOutput
	ToPostgresAttachmentOutputWithContext(ctx context.Context) PostgresAttachmentOutput
}

func (*PostgresAttachment) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresAttachment)(nil)).Elem()
}

func (i *PostgresAttachment) ToPostgresAttachmentOutput() PostgresAttachmentOutput {
	return i.ToPostgresAttachmentOutputWithContext(context.Background())
}

func (i *PostgresAttachment) ToPostgresAttachmentOutputWithContext(ctx context.Context) PostgresAttachmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresAttachmentOutput)
}

type PostgresAttachmentOutput struct{ *pulumi.OutputState }

func (PostgresAttachmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresAttachment)(nil)).Elem()
}

func (o PostgresAttachmentOutput) ToPostgresAttachmentOutput() PostgresAttachmentOutput {
	return o
}

func (o PostgresAttachmentOutput) ToPostgresAttachmentOutputWithContext(ctx context.Context) PostgresAttachmentOutput {
	return o
}

// Name of the Fly app to attach.
func (o PostgresAttachmentOutput) AppName() pulumi.StringOutput {
	return o.ApplyT(func(v *PostgresAttachment) pulumi.StringOutput { return v.AppName }).(pulumi.StringOutput)
}

func (o PostgresAttachmentOutput) Data() PostgresAttachmentTypePtrOutput {
	return o.ApplyT(func(v *PostgresAttachment) PostgresAttachmentTypePtrOutput { return v.Data }).(PostgresAttachmentTypePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresAttachmentInput)(nil)).Elem(), &PostgresAttachment{})
	pulumi.RegisterOutputType(PostgresAttachmentOutput{})
}
