// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type PostgresRestore struct {
	pulumi.CustomResourceState

	// Backup label to restore from, as returned by the backups list. Mutually exclusive with pitr_time.
	BackupId pulumi.StringPtrOutput   `pulumi:"backupId"`
	Data     PostgresClusterPtrOutput `pulumi:"data"`
	// Name for the restored cluster. Defaults to a generated name derived from the source cluster and backup/point in time when omitted or blank.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Point in time to restore to, as an RFC3339 timestamp with an explicit offset from UTC (e.g. Z or +02:00). Normalized to UTC and must fall within the cluster's PITR recovery window. Mutually exclusive with backup_id.
	PitrTime pulumi.StringPtrOutput `pulumi:"pitrTime"`
	// Query params to send with the API requests for this resource.
	QueryParams PostgresRestoreQueryParamsPtrOutput `pulumi:"queryParams"`
}

// NewPostgresRestore registers a new resource with the given unique name, arguments, and options.
func NewPostgresRestore(ctx *pulumi.Context,
	name string, args *PostgresRestoreArgs, opts ...pulumi.ResourceOption) (*PostgresRestore, error) {
	if args == nil {
		args = &PostgresRestoreArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource PostgresRestore
	err := ctx.RegisterResource("fly-machines:postgres/v1:PostgresRestore", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPostgresRestore gets an existing PostgresRestore resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPostgresRestore(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PostgresRestoreState, opts ...pulumi.ResourceOption) (*PostgresRestore, error) {
	var resource PostgresRestore
	err := ctx.ReadResource("fly-machines:postgres/v1:PostgresRestore", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering PostgresRestore resources.
type postgresRestoreState struct {
}

type PostgresRestoreState struct {
}

func (PostgresRestoreState) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresRestoreState)(nil)).Elem()
}

type postgresRestoreArgs struct {
	// Backup label to restore from, as returned by the backups list. Mutually exclusive with pitr_time.
	BackupId *string `pulumi:"backupId"`
	// Name for the restored cluster. Defaults to a generated name derived from the source cluster and backup/point in time when omitted or blank.
	Name *string `pulumi:"name"`
	// Point in time to restore to, as an RFC3339 timestamp with an explicit offset from UTC (e.g. Z or +02:00). Normalized to UTC and must fall within the cluster's PITR recovery window. Mutually exclusive with backup_id.
	PitrTime *string `pulumi:"pitrTime"`
	// Managed Postgres Cluster ID
	PostgresClusterId *string `pulumi:"postgresClusterId"`
	// Query params to send with the API requests for this resource.
	QueryParams *PostgresRestoreQueryParams `pulumi:"queryParams"`
}

// The set of arguments for constructing a PostgresRestore resource.
type PostgresRestoreArgs struct {
	// Backup label to restore from, as returned by the backups list. Mutually exclusive with pitr_time.
	BackupId pulumi.StringPtrInput
	// Name for the restored cluster. Defaults to a generated name derived from the source cluster and backup/point in time when omitted or blank.
	Name pulumi.StringPtrInput
	// Point in time to restore to, as an RFC3339 timestamp with an explicit offset from UTC (e.g. Z or +02:00). Normalized to UTC and must fall within the cluster's PITR recovery window. Mutually exclusive with backup_id.
	PitrTime pulumi.StringPtrInput
	// Managed Postgres Cluster ID
	PostgresClusterId pulumi.StringPtrInput
	// Query params to send with the API requests for this resource.
	QueryParams PostgresRestoreQueryParamsPtrInput
}

func (PostgresRestoreArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresRestoreArgs)(nil)).Elem()
}

type PostgresRestoreInput interface {
	pulumi.Input

	ToPostgresRestoreOutput() PostgresRestoreOutput
	ToPostgresRestoreOutputWithContext(ctx context.Context) PostgresRestoreOutput
}

func (*PostgresRestore) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresRestore)(nil)).Elem()
}

func (i *PostgresRestore) ToPostgresRestoreOutput() PostgresRestoreOutput {
	return i.ToPostgresRestoreOutputWithContext(context.Background())
}

func (i *PostgresRestore) ToPostgresRestoreOutputWithContext(ctx context.Context) PostgresRestoreOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresRestoreOutput)
}

type PostgresRestoreOutput struct{ *pulumi.OutputState }

func (PostgresRestoreOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PostgresRestore)(nil)).Elem()
}

func (o PostgresRestoreOutput) ToPostgresRestoreOutput() PostgresRestoreOutput {
	return o
}

func (o PostgresRestoreOutput) ToPostgresRestoreOutputWithContext(ctx context.Context) PostgresRestoreOutput {
	return o
}

// Backup label to restore from, as returned by the backups list. Mutually exclusive with pitr_time.
func (o PostgresRestoreOutput) BackupId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostgresRestore) pulumi.StringPtrOutput { return v.BackupId }).(pulumi.StringPtrOutput)
}

func (o PostgresRestoreOutput) Data() PostgresClusterPtrOutput {
	return o.ApplyT(func(v *PostgresRestore) PostgresClusterPtrOutput { return v.Data }).(PostgresClusterPtrOutput)
}

// Name for the restored cluster. Defaults to a generated name derived from the source cluster and backup/point in time when omitted or blank.
func (o PostgresRestoreOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostgresRestore) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Point in time to restore to, as an RFC3339 timestamp with an explicit offset from UTC (e.g. Z or +02:00). Normalized to UTC and must fall within the cluster's PITR recovery window. Mutually exclusive with backup_id.
func (o PostgresRestoreOutput) PitrTime() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *PostgresRestore) pulumi.StringPtrOutput { return v.PitrTime }).(pulumi.StringPtrOutput)
}

// Query params to send with the API requests for this resource.
func (o PostgresRestoreOutput) QueryParams() PostgresRestoreQueryParamsPtrOutput {
	return o.ApplyT(func(v *PostgresRestore) PostgresRestoreQueryParamsPtrOutput { return v.QueryParams }).(PostgresRestoreQueryParamsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresRestoreInput)(nil)).Elem(), &PostgresRestore{})
	pulumi.RegisterOutputType(PostgresRestoreOutput{})
}
