// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"errors"
	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Postgres struct {
	pulumi.CustomResourceState

	Data PostgresClusterPtrOutput `pulumi:"data"`
	// Disk size in gigabytes.
	DiskSizeGb pulumi.IntPtrOutput `pulumi:"diskSizeGb"`
	// Name for the cluster. A name is generated when omitted.
	Name pulumi.StringPtrOutput `pulumi:"name"`
	// Slug of the organization that will own the cluster, or "personal" for the caller's personal organization.
	OrgSlug pulumi.StringOutput `pulumi:"orgSlug"`
	// Postgres major version.
	PgMajorVersion PgMajorVersionPtrOutput `pulumi:"pgMajorVersion"`
	// Plan slug selecting CPU, memory, and disk sizing. Matched case-insensitively.
	Plan PlanOutput `pulumi:"plan"`
	// Connection pooler mode.
	PoolMode PoolModePtrOutput `pulumi:"poolMode"`
	// Enable PostGIS support, required to later enable PostGIS extensions.
	PostgisEnabled pulumi.BoolPtrOutput `pulumi:"postgisEnabled"`
	// Fly region code where the cluster's primary runs.
	Region pulumi.StringOutput `pulumi:"region"`
}

// NewPostgres registers a new resource with the given unique name, arguments, and options.
func NewPostgres(ctx *pulumi.Context,
	name string, args *PostgresArgs, opts ...pulumi.ResourceOption) (*Postgres, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.OrgSlug == nil {
		return nil, errors.New("invalid value for required argument 'OrgSlug'")
	}
	if args.Plan == nil {
		return nil, errors.New("invalid value for required argument 'Plan'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Postgres
	err := ctx.RegisterResource("fly-machines:postgres/v1:Postgres", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetPostgres gets an existing Postgres resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetPostgres(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *PostgresState, opts ...pulumi.ResourceOption) (*Postgres, error) {
	var resource Postgres
	err := ctx.ReadResource("fly-machines:postgres/v1:Postgres", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Postgres resources.
type postgresState struct {
}

type PostgresState struct {
}

func (PostgresState) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresState)(nil)).Elem()
}

type postgresArgs struct {
	// Disk size in gigabytes.
	DiskSizeGb *int `pulumi:"diskSizeGb"`
	// Name for the cluster. A name is generated when omitted.
	Name *string `pulumi:"name"`
	// Slug of the organization that will own the cluster, or "personal" for the caller's personal organization.
	OrgSlug string `pulumi:"orgSlug"`
	// Postgres major version.
	PgMajorVersion *PgMajorVersion `pulumi:"pgMajorVersion"`
	// Plan slug selecting CPU, memory, and disk sizing. Matched case-insensitively.
	Plan Plan `pulumi:"plan"`
	// Connection pooler mode.
	PoolMode *PoolMode `pulumi:"poolMode"`
	// Enable PostGIS support, required to later enable PostGIS extensions.
	PostgisEnabled *bool `pulumi:"postgisEnabled"`
	// Fly region code where the cluster's primary runs.
	Region string `pulumi:"region"`
}

// The set of arguments for constructing a Postgres resource.
type PostgresArgs struct {
	// Disk size in gigabytes.
	DiskSizeGb pulumi.IntPtrInput
	// Name for the cluster. A name is generated when omitted.
	Name pulumi.StringPtrInput
	// Slug of the organization that will own the cluster, or "personal" for the caller's personal organization.
	OrgSlug pulumi.StringInput
	// Postgres major version.
	PgMajorVersion PgMajorVersionPtrInput
	// Plan slug selecting CPU, memory, and disk sizing. Matched case-insensitively.
	Plan PlanInput
	// Connection pooler mode.
	PoolMode PoolModePtrInput
	// Enable PostGIS support, required to later enable PostGIS extensions.
	PostgisEnabled pulumi.BoolPtrInput
	// Fly region code where the cluster's primary runs.
	Region pulumi.StringInput
}

func (PostgresArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*postgresArgs)(nil)).Elem()
}

type PostgresInput interface {
	pulumi.Input

	ToPostgresOutput() PostgresOutput
	ToPostgresOutputWithContext(ctx context.Context) PostgresOutput
}

func (*Postgres) ElementType() reflect.Type {
	return reflect.TypeOf((**Postgres)(nil)).Elem()
}

func (i *Postgres) ToPostgresOutput() PostgresOutput {
	return i.ToPostgresOutputWithContext(context.Background())
}

func (i *Postgres) ToPostgresOutputWithContext(ctx context.Context) PostgresOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PostgresOutput)
}

type PostgresOutput struct{ *pulumi.OutputState }

func (PostgresOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Postgres)(nil)).Elem()
}

func (o PostgresOutput) ToPostgresOutput() PostgresOutput {
	return o
}

func (o PostgresOutput) ToPostgresOutputWithContext(ctx context.Context) PostgresOutput {
	return o
}

func (o PostgresOutput) Data() PostgresClusterPtrOutput {
	return o.ApplyT(func(v *Postgres) PostgresClusterPtrOutput { return v.Data }).(PostgresClusterPtrOutput)
}

// Disk size in gigabytes.
func (o PostgresOutput) DiskSizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Postgres) pulumi.IntPtrOutput { return v.DiskSizeGb }).(pulumi.IntPtrOutput)
}

// Name for the cluster. A name is generated when omitted.
func (o PostgresOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Postgres) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

// Slug of the organization that will own the cluster, or "personal" for the caller's personal organization.
func (o PostgresOutput) OrgSlug() pulumi.StringOutput {
	return o.ApplyT(func(v *Postgres) pulumi.StringOutput { return v.OrgSlug }).(pulumi.StringOutput)
}

// Postgres major version.
func (o PostgresOutput) PgMajorVersion() PgMajorVersionPtrOutput {
	return o.ApplyT(func(v *Postgres) PgMajorVersionPtrOutput { return v.PgMajorVersion }).(PgMajorVersionPtrOutput)
}

// Plan slug selecting CPU, memory, and disk sizing. Matched case-insensitively.
func (o PostgresOutput) Plan() PlanOutput {
	return o.ApplyT(func(v *Postgres) PlanOutput { return v.Plan }).(PlanOutput)
}

// Connection pooler mode.
func (o PostgresOutput) PoolMode() PoolModePtrOutput {
	return o.ApplyT(func(v *Postgres) PoolModePtrOutput { return v.PoolMode }).(PoolModePtrOutput)
}

// Enable PostGIS support, required to later enable PostGIS extensions.
func (o PostgresOutput) PostgisEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Postgres) pulumi.BoolPtrOutput { return v.PostgisEnabled }).(pulumi.BoolPtrOutput)
}

// Fly region code where the cluster's primary runs.
func (o PostgresOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Postgres) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PostgresInput)(nil)).Elem(), &Postgres{})
	pulumi.RegisterOutputType(PostgresOutput{})
}
