// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const FlyioAccessAction = {
    FlyioAccessAction_d_float64_1_: 1,
    FlyioAccessAction_d_float64_2_: 2,
    FlyioAccessAction_d_float64_4_: 4,
    FlyioAccessAction_d_float64_8_: 8,
    FlyioAccessAction_d_float64_16_: 16,
    FlyioAccessAction_d_float64_31_: 31,
    FlyioAccessAction_d_float64_0_: 0,
} as const;

export type FlyioAccessAction = (typeof FlyioAccessAction)[keyof typeof FlyioAccessAction];
