// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { GetPostgresArgs, GetPostgresResult, GetPostgresOutputArgs } from "./getPostgres";
export const getPostgres: typeof import("./getPostgres").getPostgres = null as any;
export const getPostgresOutput: typeof import("./getPostgres").getPostgresOutput = null as any;
utilities.lazyLoad(exports, ["getPostgres","getPostgresOutput"], () => require("./getPostgres"));

export { GetPostgresQueriesActiveArgs, GetPostgresQueriesActiveResult, GetPostgresQueriesActiveOutputArgs } from "./getPostgresQueriesActive";
export const getPostgresQueriesActive: typeof import("./getPostgresQueriesActive").getPostgresQueriesActive = null as any;
export const getPostgresQueriesActiveOutput: typeof import("./getPostgresQueriesActive").getPostgresQueriesActiveOutput = null as any;
utilities.lazyLoad(exports, ["getPostgresQueriesActive","getPostgresQueriesActiveOutput"], () => require("./getPostgresQueriesActive"));

export { GetPostgresQueriesSlowArgs, GetPostgresQueriesSlowResult, GetPostgresQueriesSlowOutputArgs } from "./getPostgresQueriesSlow";
export const getPostgresQueriesSlow: typeof import("./getPostgresQueriesSlow").getPostgresQueriesSlow = null as any;
export const getPostgresQueriesSlowOutput: typeof import("./getPostgresQueriesSlow").getPostgresQueriesSlowOutput = null as any;
utilities.lazyLoad(exports, ["getPostgresQueriesSlow","getPostgresQueriesSlowOutput"], () => require("./getPostgresQueriesSlow"));

export { GetPostgresUsersCredentialArgs, GetPostgresUsersCredentialResult, GetPostgresUsersCredentialOutputArgs } from "./getPostgresUsersCredential";
export const getPostgresUsersCredential: typeof import("./getPostgresUsersCredential").getPostgresUsersCredential = null as any;
export const getPostgresUsersCredentialOutput: typeof import("./getPostgresUsersCredential").getPostgresUsersCredentialOutput = null as any;
utilities.lazyLoad(exports, ["getPostgresUsersCredential","getPostgresUsersCredentialOutput"], () => require("./getPostgresUsersCredential"));

export { ListPostgresArgs, ListPostgresResult } from "./listPostgres";
export const listPostgres: typeof import("./listPostgres").listPostgres = null as any;
export const listPostgresOutput: typeof import("./listPostgres").listPostgresOutput = null as any;
utilities.lazyLoad(exports, ["listPostgres","listPostgresOutput"], () => require("./listPostgres"));

export { ListPostgresBackupsArgs, ListPostgresBackupsResult, ListPostgresBackupsOutputArgs } from "./listPostgresBackups";
export const listPostgresBackups: typeof import("./listPostgresBackups").listPostgresBackups = null as any;
export const listPostgresBackupsOutput: typeof import("./listPostgresBackups").listPostgresBackupsOutput = null as any;
utilities.lazyLoad(exports, ["listPostgresBackups","listPostgresBackupsOutput"], () => require("./listPostgresBackups"));

export { ListPostgresDatabasesArgs, ListPostgresDatabasesResult, ListPostgresDatabasesOutputArgs } from "./listPostgresDatabases";
export const listPostgresDatabases: typeof import("./listPostgresDatabases").listPostgresDatabases = null as any;
export const listPostgresDatabasesOutput: typeof import("./listPostgresDatabases").listPostgresDatabasesOutput = null as any;
utilities.lazyLoad(exports, ["listPostgresDatabases","listPostgresDatabasesOutput"], () => require("./listPostgresDatabases"));

export { ListPostgresExtensionsArgs, ListPostgresExtensionsResult, ListPostgresExtensionsOutputArgs } from "./listPostgresExtensions";
export const listPostgresExtensions: typeof import("./listPostgresExtensions").listPostgresExtensions = null as any;
export const listPostgresExtensionsOutput: typeof import("./listPostgresExtensions").listPostgresExtensionsOutput = null as any;
utilities.lazyLoad(exports, ["listPostgresExtensions","listPostgresExtensionsOutput"], () => require("./listPostgresExtensions"));

export { ListPostgresUsersArgs, ListPostgresUsersResult, ListPostgresUsersOutputArgs } from "./listPostgresUsers";
export const listPostgresUsers: typeof import("./listPostgresUsers").listPostgresUsers = null as any;
export const listPostgresUsersOutput: typeof import("./listPostgresUsers").listPostgresUsersOutput = null as any;
utilities.lazyLoad(exports, ["listPostgresUsers","listPostgresUsersOutput"], () => require("./listPostgresUsers"));

export { PostgresArgs } from "./postgres";
export type Postgres = import("./postgres").Postgres;
export const Postgres: typeof import("./postgres").Postgres = null as any;
utilities.lazyLoad(exports, ["Postgres"], () => require("./postgres"));

export { PostgresAttachmentArgs } from "./postgresAttachment";
export type PostgresAttachment = import("./postgresAttachment").PostgresAttachment;
export const PostgresAttachment: typeof import("./postgresAttachment").PostgresAttachment = null as any;
utilities.lazyLoad(exports, ["PostgresAttachment"], () => require("./postgresAttachment"));

export { PostgresBackupArgs } from "./postgresBackup";
export type PostgresBackup = import("./postgresBackup").PostgresBackup;
export const PostgresBackup: typeof import("./postgresBackup").PostgresBackup = null as any;
utilities.lazyLoad(exports, ["PostgresBackup"], () => require("./postgresBackup"));

export { PostgresDatabaseArgs } from "./postgresDatabase";
export type PostgresDatabase = import("./postgresDatabase").PostgresDatabase;
export const PostgresDatabase: typeof import("./postgresDatabase").PostgresDatabase = null as any;
utilities.lazyLoad(exports, ["PostgresDatabase"], () => require("./postgresDatabase"));

export { PostgresExtensionArgs } from "./postgresExtension";
export type PostgresExtension = import("./postgresExtension").PostgresExtension;
export const PostgresExtension: typeof import("./postgresExtension").PostgresExtension = null as any;
utilities.lazyLoad(exports, ["PostgresExtension"], () => require("./postgresExtension"));

export { PostgresForkArgs } from "./postgresFork";
export type PostgresFork = import("./postgresFork").PostgresFork;
export const PostgresFork: typeof import("./postgresFork").PostgresFork = null as any;
utilities.lazyLoad(exports, ["PostgresFork"], () => require("./postgresFork"));

export { PostgresRestoreArgs } from "./postgresRestore";
export type PostgresRestore = import("./postgresRestore").PostgresRestore;
export const PostgresRestore: typeof import("./postgresRestore").PostgresRestore = null as any;
utilities.lazyLoad(exports, ["PostgresRestore"], () => require("./postgresRestore"));

export { PostgresUserArgs } from "./postgresUser";
export type PostgresUser = import("./postgresUser").PostgresUser;
export const PostgresUser: typeof import("./postgresUser").PostgresUser = null as any;
utilities.lazyLoad(exports, ["PostgresUser"], () => require("./postgresUser"));

export { PostgresUsersRotatePasswordArgs } from "./postgresUsersRotatePassword";
export type PostgresUsersRotatePassword = import("./postgresUsersRotatePassword").PostgresUsersRotatePassword;
export const PostgresUsersRotatePassword: typeof import("./postgresUsersRotatePassword").PostgresUsersRotatePassword = null as any;
utilities.lazyLoad(exports, ["PostgresUsersRotatePassword"], () => require("./postgresUsersRotatePassword"));


// Export enums:
export * from "../../types/enums/postgres/v1";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "fly-machines:postgres/v1:Postgres":
                return new Postgres(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresAttachment":
                return new PostgresAttachment(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresBackup":
                return new PostgresBackup(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresDatabase":
                return new PostgresDatabase(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresExtension":
                return new PostgresExtension(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresFork":
                return new PostgresFork(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresRestore":
                return new PostgresRestore(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresUser":
                return new PostgresUser(name, <any>undefined, { urn })
            case "fly-machines:postgres/v1:PostgresUsersRotatePassword":
                return new PostgresUsersRotatePassword(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fly-machines", "postgres/v1", _module)
