// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export class PostgresDatabase extends pulumi.CustomResource {
    /**
     * Get an existing PostgresDatabase resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PostgresDatabase {
        return new PostgresDatabase(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fly-machines:postgres/v1:PostgresDatabase';

    /**
     * Returns true if the given object is an instance of PostgresDatabase.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PostgresDatabase {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PostgresDatabase.__pulumiType;
    }

    declare public /*out*/ readonly data: pulumi.Output<outputs.postgres.v1.PostgresDatabase | undefined>;
    /**
     * Name of the database to create. Must start and end with an alphanumeric
     * character and may contain hyphens and underscores, up to 63 characters.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Query params to send with the API requests for this resource.
     */
    declare public readonly queryParams: pulumi.Output<outputs.postgres.v1.PostgresDatabaseQueryParams | undefined>;

    /**
     * Create a PostgresDatabase resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PostgresDatabaseArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["name"] = args?.name;
            resourceInputs["postgresClusterId"] = args?.postgresClusterId;
            resourceInputs["queryParams"] = args?.queryParams;
            resourceInputs["data"] = undefined /*out*/;
        } else {
            resourceInputs["data"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["queryParams"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PostgresDatabase.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PostgresDatabase resource.
 */
export interface PostgresDatabaseArgs {
    /**
     * Name of the database to create. Must start and end with an alphanumeric
     * character and may contain hyphens and underscores, up to 63 characters.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Managed Postgres Cluster ID
     */
    postgresClusterId?: pulumi.Input<string | undefined>;
    /**
     * Query params to send with the API requests for this resource.
     */
    queryParams?: pulumi.Input<inputs.postgres.v1.PostgresDatabaseQueryParamsArgs | undefined>;
}
