// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export class PostgresExtension extends pulumi.CustomResource {
    /**
     * Get an existing PostgresExtension resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PostgresExtension {
        return new PostgresExtension(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'fly-machines:postgres/v1:PostgresExtension';

    /**
     * Returns true if the given object is an instance of PostgresExtension.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PostgresExtension {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PostgresExtension.__pulumiType;
    }

    /**
     * Create the schema first if it does not exist.
     */
    declare public readonly createSchema: pulumi.Output<boolean | undefined>;
    /**
     * Extension to enable.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Query params to send with the API requests for this resource.
     */
    declare public readonly queryParams: pulumi.Output<outputs.postgres.v1.PostgresExtensionQueryParams | undefined>;
    /**
     * Schema to install the extension into. Defaults to the database's default schema.
     */
    declare public readonly schema: pulumi.Output<string | undefined>;

    /**
     * Create a PostgresExtension resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PostgresExtensionArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["createSchema"] = args?.createSchema;
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["name"] = args?.name;
            resourceInputs["postgresClusterId"] = args?.postgresClusterId;
            resourceInputs["queryParams"] = args?.queryParams;
            resourceInputs["schema"] = args?.schema;
        } else {
            resourceInputs["createSchema"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["queryParams"] = undefined /*out*/;
            resourceInputs["schema"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PostgresExtension.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PostgresExtension resource.
 */
export interface PostgresExtensionArgs {
    /**
     * Create the schema first if it does not exist.
     */
    createSchema?: pulumi.Input<boolean | undefined>;
    /**
     * Database Name
     */
    databaseName?: pulumi.Input<string | undefined>;
    /**
     * Extension to enable.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Managed Postgres Cluster ID
     */
    postgresClusterId?: pulumi.Input<string | undefined>;
    /**
     * Query params to send with the API requests for this resource.
     */
    queryParams?: pulumi.Input<inputs.postgres.v1.PostgresExtensionQueryParamsArgs | undefined>;
    /**
     * Schema to install the extension into. Defaults to the database's default schema.
     */
    schema?: pulumi.Input<string | undefined>;
}
