// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.FlyMachines.OrgsV1
{
    /// <summary>
    /// Deprecated: use MachineConfig.Rootfs instead
    /// </summary>
    [EnumType]
    public readonly struct FlyMachineGuestPersistRootfs : IEquatable<FlyMachineGuestPersistRootfs>
    {
        private readonly string _value;

        private FlyMachineGuestPersistRootfs(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyMachineGuestPersistRootfs Never { get; } = new FlyMachineGuestPersistRootfs("never");
        public static FlyMachineGuestPersistRootfs Always { get; } = new FlyMachineGuestPersistRootfs("always");
        public static FlyMachineGuestPersistRootfs Restart { get; } = new FlyMachineGuestPersistRootfs("restart");

        public static bool operator ==(FlyMachineGuestPersistRootfs left, FlyMachineGuestPersistRootfs right) => left.Equals(right);
        public static bool operator !=(FlyMachineGuestPersistRootfs left, FlyMachineGuestPersistRootfs right) => !left.Equals(right);

        public static explicit operator string(FlyMachineGuestPersistRootfs value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyMachineGuestPersistRootfs other && Equals(other);
        public bool Equals(FlyMachineGuestPersistRootfs other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct OrgVolumeHostStatus : IEquatable<OrgVolumeHostStatus>
    {
        private readonly string _value;

        private OrgVolumeHostStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static OrgVolumeHostStatus Ok { get; } = new OrgVolumeHostStatus("ok");
        public static OrgVolumeHostStatus Unknown { get; } = new OrgVolumeHostStatus("unknown");
        public static OrgVolumeHostStatus Unreachable { get; } = new OrgVolumeHostStatus("unreachable");

        public static bool operator ==(OrgVolumeHostStatus left, OrgVolumeHostStatus right) => left.Equals(right);
        public static bool operator !=(OrgVolumeHostStatus left, OrgVolumeHostStatus right) => !left.Equals(right);

        public static explicit operator string(OrgVolumeHostStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is OrgVolumeHostStatus other && Equals(other);
        public bool Equals(OrgVolumeHostStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct OrgVolumeType : IEquatable<OrgVolumeType>
    {
        private readonly string _value;

        private OrgVolumeType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static OrgVolumeType Local { get; } = new OrgVolumeType("local");
        public static OrgVolumeType Cache { get; } = new OrgVolumeType("cache");

        public static bool operator ==(OrgVolumeType left, OrgVolumeType right) => left.Equals(right);
        public static bool operator !=(OrgVolumeType left, OrgVolumeType right) => !left.Equals(right);

        public static explicit operator string(OrgVolumeType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is OrgVolumeType other && Equals(other);
        public bool Equals(OrgVolumeType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
