// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.OrgsV1
{
    public static class ListMachinesOrg
    {
        public static Task<ListMachinesOrgResult> InvokeAsync(ListMachinesOrgArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ListMachinesOrgResult>("fly-machines:orgs/v1:listMachinesOrg", args ?? new ListMachinesOrgArgs(), options.WithDefaults());

        public static Output<ListMachinesOrgResult> Invoke(ListMachinesOrgInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ListMachinesOrgResult>("fly-machines:orgs/v1:listMachinesOrg", args ?? new ListMachinesOrgInvokeArgs(), options.WithDefaults());

        public static Output<ListMachinesOrgResult> Invoke(ListMachinesOrgInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<ListMachinesOrgResult>("fly-machines:orgs/v1:listMachinesOrg", args ?? new ListMachinesOrgInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListMachinesOrgArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Fly Organization Slug
        /// </summary>
        [Input("orgSlug", required: true)]
        public string OrgSlug { get; set; } = null!;

        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Inputs.ListMachinesOrgQueryParams? QueryParams { get; set; }

        public ListMachinesOrgArgs()
        {
        }
        public static new ListMachinesOrgArgs Empty => new ListMachinesOrgArgs();
    }

    public sealed class ListMachinesOrgInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Fly Organization Slug
        /// </summary>
        [Input("orgSlug", required: true)]
        public Input<string> OrgSlug { get; set; } = null!;

        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Input<Inputs.ListMachinesOrgQueryParamsArgs>? QueryParams { get; set; }

        public ListMachinesOrgInvokeArgs()
        {
        }
        public static new ListMachinesOrgInvokeArgs Empty => new ListMachinesOrgInvokeArgs();
    }


    [OutputType]
    public sealed class ListMachinesOrgResult
    {
        public readonly ImmutableArray<string> ErrorRegions;
        public readonly string? LastMachineId;
        public readonly string? LastUpdatedAt;
        public readonly ImmutableArray<Outputs.OrgMachine> Machines;
        public readonly string? NextCursor;

        [OutputConstructor]
        private ListMachinesOrgResult(
            ImmutableArray<string> errorRegions,

            string? lastMachineId,

            string? lastUpdatedAt,

            ImmutableArray<Outputs.OrgMachine> machines,

            string? nextCursor)
        {
            ErrorRegions = errorRegions;
            LastMachineId = lastMachineId;
            LastUpdatedAt = lastUpdatedAt;
            Machines = machines;
            NextCursor = nextCursor;
        }
    }
}
