// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    public sealed class FlyContainerDependencyArgs : global::Pulumi.ResourceArgs
    {
        [Input("condition")]
        public Input<Inputs.FlyContainerDependencyConditionArgs>? Condition { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        public FlyContainerDependencyArgs()
        {
        }
        public static new FlyContainerDependencyArgs Empty => new FlyContainerDependencyArgs();
    }
}
