// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    public sealed class FlyExecHealthcheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("command")]
        private InputList<string>? _command;

        /// <summary>
        /// The command to run to check the health of the container (e.g. ["cat", "/tmp/healthy"])
        /// </summary>
        public InputList<string> Command
        {
            get => _command ?? (_command = new InputList<string>());
            set => _command = value;
        }

        public FlyExecHealthcheckArgs()
        {
        }
        public static new FlyExecHealthcheckArgs Empty => new FlyExecHealthcheckArgs();
    }
}
