// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    /// <summary>
    /// A file that will be written to the Machine. One of RawValue or SecretName must be set.
    /// </summary>
    public sealed class FlyFileArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GuestPath is the path on the machine where the file will be written and must be an absolute path.
        /// For example: /full/path/to/file.json
        /// </summary>
        [Input("guestPath")]
        public Input<string>? GuestPath { get; set; }

        /// <summary>
        /// The name of an image to use the OCI image config as the file contents.
        /// </summary>
        [Input("imageConfig")]
        public Input<string>? ImageConfig { get; set; }

        /// <summary>
        /// Mode bits used to set permissions on this file as accepted by chmod(2).
        /// </summary>
        [Input("mode")]
        public Input<int>? Mode { get; set; }

        /// <summary>
        /// The base64 encoded string of the file contents.
        /// </summary>
        [Input("rawValue")]
        public Input<string>? RawValue { get; set; }

        /// <summary>
        /// The name of the secret that contains the base64 encoded file contents.
        /// </summary>
        [Input("secretName")]
        public Input<string>? SecretName { get; set; }

        public FlyFileArgs()
        {
        }
        public static new FlyFileArgs Empty => new FlyFileArgs();
    }
}
