// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    public sealed class FlyHTTPHealthcheckArgs : global::Pulumi.ResourceArgs
    {
        [Input("headers")]
        private InputList<Inputs.FlyMachineHTTPHeaderArgs>? _headers;

        /// <summary>
        /// Additional headers to send with the request
        /// </summary>
        public InputList<Inputs.FlyMachineHTTPHeaderArgs> Headers
        {
            get => _headers ?? (_headers = new InputList<Inputs.FlyMachineHTTPHeaderArgs>());
            set => _headers = value;
        }

        /// <summary>
        /// The HTTP method to use to when making the request
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        /// <summary>
        /// The path to send the request to
        /// </summary>
        [Input("path")]
        public Input<string>? Path { get; set; }

        /// <summary>
        /// The port to connect to, often the same as internal_port
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// Whether to use http or https
        /// </summary>
        [Input("scheme")]
        public Input<Inputs.FlyHTTPHealthcheckSchemeArgs>? Scheme { get; set; }

        /// <summary>
        /// If the protocol is https, the hostname to use for TLS certificate validation
        /// </summary>
        [Input("tlsServerName")]
        public Input<string>? TlsServerName { get; set; }

        /// <summary>
        /// If the protocol is https, whether or not to verify the TLS certificate
        /// </summary>
        [Input("tlsSkipVerify")]
        public Input<bool>? TlsSkipVerify { get; set; }

        public FlyHTTPHealthcheckArgs()
        {
        }
        public static new FlyHTTPHealthcheckArgs Empty => new FlyHTTPHealthcheckArgs();
    }
}
