// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    /// <summary>
    /// Query params for the API request.
    /// </summary>
    public sealed class GetMachinesWaitQueryParamsArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalParams")]
        private InputMap<string>? _additionalParams;

        /// <summary>
        /// Additional query params to send with the request that are not defined in the API spec.
        /// </summary>
        public InputMap<string> AdditionalParams
        {
            get => _additionalParams ?? (_additionalParams = new InputMap<string>());
            set => _additionalParams = value;
        }

        /// <summary>
        /// 26-character Machine event ID to start waiting after
        /// </summary>
        [Input("fromEventId")]
        public Input<string>? FromEventId { get; set; }

        /// <summary>
        /// 26-character Machine version ID (deprecated; use version)
        /// </summary>
        [Input("instanceId")]
        public Input<string>? InstanceId { get; set; }

        /// <summary>
        /// desired state(s), supports repeated or comma-separated values
        /// </summary>
        [Input("state")]
        public Input<Pulumi.FlyMachines.AppsV1.GetMachinesWaitQueryParamsState>? State { get; set; }

        /// <summary>
        /// wait timeout. default 60s
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        /// <summary>
        /// 26-character Machine version ID
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public GetMachinesWaitQueryParamsArgs()
        {
        }
        public static new GetMachinesWaitQueryParamsArgs Empty => new GetMachinesWaitQueryParamsArgs();
    }
}
