// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    /// <summary>
    /// Query params for the API request.
    /// </summary>
    public sealed class ListAppCertificatesQueryParamsArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalParams")]
        private InputMap<string>? _additionalParams;

        /// <summary>
        /// Additional query params to send with the request that are not defined in the API spec.
        /// </summary>
        public InputMap<string> AdditionalParams
        {
            get => _additionalParams ?? (_additionalParams = new InputMap<string>());
            set => _additionalParams = value;
        }

        /// <summary>
        /// Pagination cursor from previous response
        /// </summary>
        [Input("cursor")]
        public Input<string>? Cursor { get; set; }

        /// <summary>
        /// Hostname filter (substring match)
        /// </summary>
        [Input("filter")]
        public Input<string>? Filter { get; set; }

        /// <summary>
        /// Number of results per page (default 25, max 500)
        /// </summary>
        [Input("limit")]
        public Input<int>? Limit { get; set; }

        public ListAppCertificatesQueryParamsArgs()
        {
        }
        public static new ListAppCertificatesQueryParamsArgs Empty => new ListAppCertificatesQueryParamsArgs();
    }
}
