// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    /// <summary>
    /// Query params for the API request.
    /// </summary>
    public sealed class ListAppsQueryParams : global::Pulumi.InvokeArgs
    {
        [Input("additionalParams")]
        private Dictionary<string, string>? _additionalParams;

        /// <summary>
        /// Additional query params to send with the request that are not defined in the API spec.
        /// </summary>
        public Dictionary<string, string> AdditionalParams
        {
            get => _additionalParams ?? (_additionalParams = new Dictionary<string, string>());
            set => _additionalParams = value;
        }

        /// <summary>
        /// Filter apps by role
        /// </summary>
        [Input("appRole")]
        public string? AppRole { get; set; }

        /// <summary>
        /// The org slug, or 'personal', to filter apps
        /// </summary>
        [Input("orgSlug", required: true)]
        public string OrgSlug { get; set; } = null!;

        public ListAppsQueryParams()
        {
        }
        public static new ListAppsQueryParams Empty => new ListAppsQueryParams();
    }
}
