// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    public sealed class MachinesMetadataQueryParamsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        [Input("create")]
        public Input<Inputs.MachinesMetadataCreateQueryParamsArgs>? Create { get; set; }

        /// <summary>
        /// Query params for the read operation.
        /// </summary>
        [Input("read")]
        public Input<Inputs.MachinesMetadataReadQueryParamsArgs>? Read { get; set; }

        /// <summary>
        /// Query params for the update operation.
        /// </summary>
        [Input("update")]
        public Input<Inputs.MachinesMetadataUpdateQueryParamsArgs>? Update { get; set; }

        public MachinesMetadataQueryParamsArgs()
        {
        }
        public static new MachinesMetadataQueryParamsArgs Empty => new MachinesMetadataQueryParamsArgs();
    }
}
