// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1.Inputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    public sealed class MachineQueryParamsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        [Input("create")]
        public Input<Inputs.MachineCreateQueryParamsArgs>? Create { get; set; }

        /// <summary>
        /// Query params for the delete operation.
        /// </summary>
        [Input("delete")]
        public Input<Inputs.MachineDeleteQueryParamsArgs>? Delete { get; set; }

        /// <summary>
        /// Query params for the put operation.
        /// </summary>
        [Input("put")]
        public Input<Inputs.MachinePutQueryParamsArgs>? Put { get; set; }

        /// <summary>
        /// Query params for the read operation.
        /// </summary>
        [Input("read")]
        public Input<Inputs.MachineReadQueryParamsArgs>? Read { get; set; }

        public MachineQueryParamsArgs()
        {
        }
        public static new MachineQueryParamsArgs Empty => new MachineQueryParamsArgs();
    }
}
