// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PostgresV1
{
    [FlyMachinesResourceType("fly-machines:postgres/v1:PostgresAttachment")]
    public partial class PostgresAttachment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the Fly app to attach.
        /// </summary>
        [Output("appName")]
        public Output<string> AppName { get; private set; } = null!;

        [Output("data")]
        public Output<Outputs.PostgresAttachment?> Data { get; private set; } = null!;


        /// <summary>
        /// Create a PostgresAttachment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PostgresAttachment(string name, PostgresAttachmentArgs args, CustomResourceOptions? options = null)
            : base("fly-machines:postgres/v1:PostgresAttachment", name, args ?? new PostgresAttachmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PostgresAttachment(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:postgres/v1:PostgresAttachment", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PostgresAttachment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PostgresAttachment Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PostgresAttachment(name, id, options);
        }
    }

    public sealed class PostgresAttachmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the Fly app to attach.
        /// </summary>
        [Input("appName", required: true)]
        public Input<string> AppName { get; set; } = null!;

        /// <summary>
        /// Managed Postgres Cluster ID
        /// </summary>
        [Input("postgresClusterId")]
        public Input<string>? PostgresClusterId { get; set; }

        public PostgresAttachmentArgs()
        {
        }
        public static new PostgresAttachmentArgs Empty => new PostgresAttachmentArgs();
    }
}
