// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PostgresV1
{
    [FlyMachinesResourceType("fly-machines:postgres/v1:Postgres")]
    public partial class Postgres : global::Pulumi.CustomResource
    {
        [Output("data")]
        public Output<Outputs.PostgresCluster?> Data { get; private set; } = null!;

        /// <summary>
        /// Disk size in gigabytes.
        /// </summary>
        [Output("diskSizeGb")]
        public Output<int?> DiskSizeGb { get; private set; } = null!;

        /// <summary>
        /// Name for the cluster. A name is generated when omitted.
        /// </summary>
        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// Slug of the organization that will own the cluster, or "personal" for the caller's personal organization.
        /// </summary>
        [Output("orgSlug")]
        public Output<string> OrgSlug { get; private set; } = null!;

        /// <summary>
        /// Postgres major version.
        /// </summary>
        [Output("pgMajorVersion")]
        public Output<Pulumi.FlyMachines.PostgresV1.PgMajorVersion?> PgMajorVersion { get; private set; } = null!;

        /// <summary>
        /// Plan slug selecting CPU, memory, and disk sizing. Matched case-insensitively.
        /// </summary>
        [Output("plan")]
        public Output<Pulumi.FlyMachines.PostgresV1.Plan> Plan { get; private set; } = null!;

        /// <summary>
        /// Connection pooler mode.
        /// </summary>
        [Output("poolMode")]
        public Output<Pulumi.FlyMachines.PostgresV1.PoolMode?> PoolMode { get; private set; } = null!;

        /// <summary>
        /// Enable PostGIS support, required to later enable PostGIS extensions.
        /// </summary>
        [Output("postgisEnabled")]
        public Output<bool?> PostgisEnabled { get; private set; } = null!;

        /// <summary>
        /// Fly region code where the cluster's primary runs.
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;


        /// <summary>
        /// Create a Postgres resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Postgres(string name, PostgresArgs args, CustomResourceOptions? options = null)
            : base("fly-machines:postgres/v1:Postgres", name, args ?? new PostgresArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Postgres(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:postgres/v1:Postgres", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Postgres resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Postgres Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Postgres(name, id, options);
        }
    }

    public sealed class PostgresArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Disk size in gigabytes.
        /// </summary>
        [Input("diskSizeGb")]
        public Input<int>? DiskSizeGb { get; set; }

        /// <summary>
        /// Name for the cluster. A name is generated when omitted.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Slug of the organization that will own the cluster, or "personal" for the caller's personal organization.
        /// </summary>
        [Input("orgSlug", required: true)]
        public Input<string> OrgSlug { get; set; } = null!;

        /// <summary>
        /// Postgres major version.
        /// </summary>
        [Input("pgMajorVersion")]
        public Input<Pulumi.FlyMachines.PostgresV1.PgMajorVersion>? PgMajorVersion { get; set; }

        /// <summary>
        /// Plan slug selecting CPU, memory, and disk sizing. Matched case-insensitively.
        /// </summary>
        [Input("plan", required: true)]
        public Input<Pulumi.FlyMachines.PostgresV1.Plan> Plan { get; set; } = null!;

        /// <summary>
        /// Connection pooler mode.
        /// </summary>
        [Input("poolMode")]
        public Input<Pulumi.FlyMachines.PostgresV1.PoolMode>? PoolMode { get; set; }

        /// <summary>
        /// Enable PostGIS support, required to later enable PostGIS extensions.
        /// </summary>
        [Input("postgisEnabled")]
        public Input<bool>? PostgisEnabled { get; set; }

        /// <summary>
        /// Fly region code where the cluster's primary runs.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public PostgresArgs()
        {
        }
        public static new PostgresArgs Empty => new PostgresArgs();
    }
}
