// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.FlyMachines.PlatformV1
{
    /// <summary>
    /// Deprecated: use MachineConfig.Rootfs instead
    /// </summary>
    [EnumType]
    public readonly struct FlyMachineGuestPersistRootfs : IEquatable<FlyMachineGuestPersistRootfs>
    {
        private readonly string _value;

        private FlyMachineGuestPersistRootfs(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyMachineGuestPersistRootfs Never { get; } = new FlyMachineGuestPersistRootfs("never");
        public static FlyMachineGuestPersistRootfs Always { get; } = new FlyMachineGuestPersistRootfs("always");
        public static FlyMachineGuestPersistRootfs Restart { get; } = new FlyMachineGuestPersistRootfs("restart");

        public static bool operator ==(FlyMachineGuestPersistRootfs left, FlyMachineGuestPersistRootfs right) => left.Equals(right);
        public static bool operator !=(FlyMachineGuestPersistRootfs left, FlyMachineGuestPersistRootfs right) => !left.Equals(right);

        public static explicit operator string(FlyMachineGuestPersistRootfs value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyMachineGuestPersistRootfs other && Equals(other);
        public bool Equals(FlyMachineGuestPersistRootfs other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
