// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PlatformV1
{
    public static class GetPlatformRegion
    {
        public static Task<GetPlatformRegionResult> InvokeAsync(GetPlatformRegionArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPlatformRegionResult>("fly-machines:platform/v1:getPlatformRegion", args ?? new GetPlatformRegionArgs(), options.WithDefaults());

        public static Output<GetPlatformRegionResult> Invoke(GetPlatformRegionInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlatformRegionResult>("fly-machines:platform/v1:getPlatformRegion", args ?? new GetPlatformRegionInvokeArgs(), options.WithDefaults());

        public static Output<GetPlatformRegionResult> Invoke(GetPlatformRegionInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPlatformRegionResult>("fly-machines:platform/v1:getPlatformRegion", args ?? new GetPlatformRegionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPlatformRegionArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Inputs.GetPlatformRegionQueryParams? QueryParams { get; set; }

        public GetPlatformRegionArgs()
        {
        }
        public static new GetPlatformRegionArgs Empty => new GetPlatformRegionArgs();
    }

    public sealed class GetPlatformRegionInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Input<Inputs.GetPlatformRegionQueryParamsArgs>? QueryParams { get; set; }

        public GetPlatformRegionInvokeArgs()
        {
        }
        public static new GetPlatformRegionInvokeArgs Empty => new GetPlatformRegionInvokeArgs();
    }


    [OutputType]
    public sealed class GetPlatformRegionResult
    {
        public readonly string? Nearest;
        public readonly ImmutableArray<Outputs.MainRegionRow> Regions;

        [OutputConstructor]
        private GetPlatformRegionResult(
            string? nearest,

            ImmutableArray<Outputs.MainRegionRow> regions)
        {
            Nearest = nearest;
            Regions = regions;
        }
    }
}
