// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PlatformV1
{
    [FlyMachinesResourceType("fly-machines:platform/v1:PlatformPlacement")]
    public partial class PlatformPlacement : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Resource requirements for the Machine to simulate. Defaults to a performance-1x machine
        /// </summary>
        [Output("compute")]
        public Output<Outputs.Compute?> Compute { get; private set; } = null!;

        /// <summary>
        /// Number of machines to simulate placement.
        /// Defaults to 0, which returns the org-specific limit for each region.
        /// </summary>
        [Output("count")]
        public Output<int?> Count { get; private set; } = null!;

        [Output("orgSlug")]
        public Output<string> OrgSlug { get; private set; } = null!;

        /// <summary>
        /// Region expression for placement as a comma-delimited set of regions or aliases.
        /// Defaults to "[region],any", to prefer the API endpoint's local region with any other region as fallback.
        /// </summary>
        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("regions")]
        public Output<ImmutableArray<Outputs.PlacementRegionPlacement>> Regions { get; private set; } = null!;

        [Output("volumeName")]
        public Output<string?> VolumeName { get; private set; } = null!;

        [Output("volumeSizeBytes")]
        public Output<int?> VolumeSizeBytes { get; private set; } = null!;

        /// <summary>
        /// Optional weights to override default placement preferences.
        /// </summary>
        [Output("weights")]
        public Output<Outputs.Weights?> Weights { get; private set; } = null!;


        /// <summary>
        /// Create a PlatformPlacement resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public PlatformPlacement(string name, PlatformPlacementArgs args, CustomResourceOptions? options = null)
            : base("fly-machines:platform/v1:PlatformPlacement", name, args ?? new PlatformPlacementArgs(), MakeResourceOptions(options, ""))
        {
        }

        private PlatformPlacement(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:platform/v1:PlatformPlacement", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing PlatformPlacement resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static PlatformPlacement Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new PlatformPlacement(name, id, options);
        }
    }

    public sealed class PlatformPlacementArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Resource requirements for the Machine to simulate. Defaults to a performance-1x machine
        /// </summary>
        [Input("compute")]
        public Input<Inputs.ComputeArgs>? Compute { get; set; }

        /// <summary>
        /// Number of machines to simulate placement.
        /// Defaults to 0, which returns the org-specific limit for each region.
        /// </summary>
        [Input("count")]
        public Input<int>? Count { get; set; }

        [Input("orgSlug", required: true)]
        public Input<string> OrgSlug { get; set; } = null!;

        /// <summary>
        /// Region expression for placement as a comma-delimited set of regions or aliases.
        /// Defaults to "[region],any", to prefer the API endpoint's local region with any other region as fallback.
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("volumeName")]
        public Input<string>? VolumeName { get; set; }

        [Input("volumeSizeBytes")]
        public Input<int>? VolumeSizeBytes { get; set; }

        /// <summary>
        /// Optional weights to override default placement preferences.
        /// </summary>
        [Input("weights")]
        public Input<Inputs.WeightsArgs>? Weights { get; set; }

        public PlatformPlacementArgs()
        {
        }
        public static new PlatformPlacementArgs Empty => new PlatformPlacementArgs();
    }
}
