// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type AppDeployToken struct {
	pulumi.CustomResourceState

	Expiry pulumi.StringPtrOutput `pulumi:"expiry"`
	// Query params to send with the API requests for this resource.
	QueryParams AppDeployTokenQueryParamsPtrOutput `pulumi:"queryParams"`
	Token       pulumi.StringPtrOutput             `pulumi:"token"`
}

// NewAppDeployToken registers a new resource with the given unique name, arguments, and options.
func NewAppDeployToken(ctx *pulumi.Context,
	name string, args *AppDeployTokenArgs, opts ...pulumi.ResourceOption) (*AppDeployToken, error) {
	if args == nil {
		args = &AppDeployTokenArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource AppDeployToken
	err := ctx.RegisterResource("fly-machines:apps/v1:AppDeployToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetAppDeployToken gets an existing AppDeployToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetAppDeployToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *AppDeployTokenState, opts ...pulumi.ResourceOption) (*AppDeployToken, error) {
	var resource AppDeployToken
	err := ctx.ReadResource("fly-machines:apps/v1:AppDeployToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering AppDeployToken resources.
type appDeployTokenState struct {
}

type AppDeployTokenState struct {
}

func (AppDeployTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*appDeployTokenState)(nil)).Elem()
}

type appDeployTokenArgs struct {
	// Fly App Name
	AppName *string `pulumi:"appName"`
	Expiry  *string `pulumi:"expiry"`
	// Query params to send with the API requests for this resource.
	QueryParams *AppDeployTokenQueryParams `pulumi:"queryParams"`
}

// The set of arguments for constructing a AppDeployToken resource.
type AppDeployTokenArgs struct {
	// Fly App Name
	AppName pulumi.StringPtrInput
	Expiry  pulumi.StringPtrInput
	// Query params to send with the API requests for this resource.
	QueryParams AppDeployTokenQueryParamsPtrInput
}

func (AppDeployTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*appDeployTokenArgs)(nil)).Elem()
}

type AppDeployTokenInput interface {
	pulumi.Input

	ToAppDeployTokenOutput() AppDeployTokenOutput
	ToAppDeployTokenOutputWithContext(ctx context.Context) AppDeployTokenOutput
}

func (*AppDeployToken) ElementType() reflect.Type {
	return reflect.TypeOf((**AppDeployToken)(nil)).Elem()
}

func (i *AppDeployToken) ToAppDeployTokenOutput() AppDeployTokenOutput {
	return i.ToAppDeployTokenOutputWithContext(context.Background())
}

func (i *AppDeployToken) ToAppDeployTokenOutputWithContext(ctx context.Context) AppDeployTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppDeployTokenOutput)
}

type AppDeployTokenOutput struct{ *pulumi.OutputState }

func (AppDeployTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AppDeployToken)(nil)).Elem()
}

func (o AppDeployTokenOutput) ToAppDeployTokenOutput() AppDeployTokenOutput {
	return o
}

func (o AppDeployTokenOutput) ToAppDeployTokenOutputWithContext(ctx context.Context) AppDeployTokenOutput {
	return o
}

func (o AppDeployTokenOutput) Expiry() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AppDeployToken) pulumi.StringPtrOutput { return v.Expiry }).(pulumi.StringPtrOutput)
}

// Query params to send with the API requests for this resource.
func (o AppDeployTokenOutput) QueryParams() AppDeployTokenQueryParamsPtrOutput {
	return o.ApplyT(func(v *AppDeployToken) AppDeployTokenQueryParamsPtrOutput { return v.QueryParams }).(AppDeployTokenQueryParamsPtrOutput)
}

func (o AppDeployTokenOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AppDeployToken) pulumi.StringPtrOutput { return v.Token }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AppDeployTokenInput)(nil)).Elem(), &AppDeployToken{})
	pulumi.RegisterOutputType(AppDeployTokenOutput{})
}
