// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupApp(ctx *pulumi.Context, args *LookupAppArgs, opts ...pulumi.InvokeOption) (*LookupAppResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAppResult
	err := ctx.Invoke("fly-machines:apps/v1:getApp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupAppArgs struct {
	// Fly App Name
	AppName string `pulumi:"appName"`
}

type LookupAppResult struct {
	Id                *string              `pulumi:"id"`
	InternalNumericId *int                 `pulumi:"internalNumericId"`
	MachineCount      *int                 `pulumi:"machineCount"`
	Name              *string              `pulumi:"name"`
	Network           *string              `pulumi:"network"`
	NetworkCidr       *string              `pulumi:"networkCidr"`
	Organization      *AppOrganizationInfo `pulumi:"organization"`
	Status            *string              `pulumi:"status"`
	VolumeCount       *int                 `pulumi:"volumeCount"`
}

func LookupAppOutput(ctx *pulumi.Context, args LookupAppOutputArgs, opts ...pulumi.InvokeOption) LookupAppResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:apps/v1:getApp", args, LookupAppResultOutput{}, options).(LookupAppResultOutput)
}

type LookupAppOutputArgs struct {
	// Fly App Name
	AppName pulumi.StringInput `pulumi:"appName"`
}

func (LookupAppOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppArgs)(nil)).Elem()
}

type LookupAppResultOutput struct{ *pulumi.OutputState }

func (LookupAppResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppResult)(nil)).Elem()
}

func (o LookupAppResultOutput) ToLookupAppResultOutput() LookupAppResultOutput {
	return o
}

func (o LookupAppResultOutput) ToLookupAppResultOutputWithContext(ctx context.Context) LookupAppResultOutput {
	return o
}

func (o LookupAppResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupAppResultOutput) InternalNumericId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *int { return v.InternalNumericId }).(pulumi.IntPtrOutput)
}

func (o LookupAppResultOutput) MachineCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *int { return v.MachineCount }).(pulumi.IntPtrOutput)
}

func (o LookupAppResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupAppResultOutput) Network() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *string { return v.Network }).(pulumi.StringPtrOutput)
}

func (o LookupAppResultOutput) NetworkCidr() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *string { return v.NetworkCidr }).(pulumi.StringPtrOutput)
}

func (o LookupAppResultOutput) Organization() AppOrganizationInfoPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *AppOrganizationInfo { return v.Organization }).(AppOrganizationInfoPtrOutput)
}

func (o LookupAppResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

func (o LookupAppResultOutput) VolumeCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupAppResult) *int { return v.VolumeCount }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAppResultOutput{})
}
