// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAppCertificate(ctx *pulumi.Context, args *GetAppCertificateArgs, opts ...pulumi.InvokeOption) (*GetAppCertificateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAppCertificateResult
	err := ctx.Invoke("fly-machines:apps/v1:getAppCertificate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetAppCertificateArgs struct {
	// Fly App Name
	AppName string `pulumi:"appName"`
	// Certificate Hostname
	Hostname string `pulumi:"hostname"`
}

type GetAppCertificateResult struct {
	AcmeRequested    *bool                        `pulumi:"acmeRequested"`
	Certificates     []CertificateEntry           `pulumi:"certificates"`
	Configured       *bool                        `pulumi:"configured"`
	DnsProvider      *string                      `pulumi:"dnsProvider"`
	DnsRequirements  *DNSRequirements             `pulumi:"dnsRequirements"`
	Hostname         *string                      `pulumi:"hostname"`
	RateLimitedUntil *string                      `pulumi:"rateLimitedUntil"`
	Status           *string                      `pulumi:"status"`
	Validation       *CertificateValidation       `pulumi:"validation"`
	ValidationErrors []CertificateValidationError `pulumi:"validationErrors"`
}

func GetAppCertificateOutput(ctx *pulumi.Context, args GetAppCertificateOutputArgs, opts ...pulumi.InvokeOption) GetAppCertificateResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:apps/v1:getAppCertificate", args, GetAppCertificateResultOutput{}, options).(GetAppCertificateResultOutput)
}

type GetAppCertificateOutputArgs struct {
	// Fly App Name
	AppName pulumi.StringInput `pulumi:"appName"`
	// Certificate Hostname
	Hostname pulumi.StringInput `pulumi:"hostname"`
}

func (GetAppCertificateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAppCertificateArgs)(nil)).Elem()
}

type GetAppCertificateResultOutput struct{ *pulumi.OutputState }

func (GetAppCertificateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetAppCertificateResult)(nil)).Elem()
}

func (o GetAppCertificateResultOutput) ToGetAppCertificateResultOutput() GetAppCertificateResultOutput {
	return o
}

func (o GetAppCertificateResultOutput) ToGetAppCertificateResultOutputWithContext(ctx context.Context) GetAppCertificateResultOutput {
	return o
}

func (o GetAppCertificateResultOutput) AcmeRequested() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *bool { return v.AcmeRequested }).(pulumi.BoolPtrOutput)
}

func (o GetAppCertificateResultOutput) Certificates() CertificateEntryArrayOutput {
	return o.ApplyT(func(v GetAppCertificateResult) []CertificateEntry { return v.Certificates }).(CertificateEntryArrayOutput)
}

func (o GetAppCertificateResultOutput) Configured() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *bool { return v.Configured }).(pulumi.BoolPtrOutput)
}

func (o GetAppCertificateResultOutput) DnsProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *string { return v.DnsProvider }).(pulumi.StringPtrOutput)
}

func (o GetAppCertificateResultOutput) DnsRequirements() DNSRequirementsPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *DNSRequirements { return v.DnsRequirements }).(DNSRequirementsPtrOutput)
}

func (o GetAppCertificateResultOutput) Hostname() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *string { return v.Hostname }).(pulumi.StringPtrOutput)
}

func (o GetAppCertificateResultOutput) RateLimitedUntil() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *string { return v.RateLimitedUntil }).(pulumi.StringPtrOutput)
}

func (o GetAppCertificateResultOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *string { return v.Status }).(pulumi.StringPtrOutput)
}

func (o GetAppCertificateResultOutput) Validation() CertificateValidationPtrOutput {
	return o.ApplyT(func(v GetAppCertificateResult) *CertificateValidation { return v.Validation }).(CertificateValidationPtrOutput)
}

func (o GetAppCertificateResultOutput) ValidationErrors() CertificateValidationErrorArrayOutput {
	return o.ApplyT(func(v GetAppCertificateResult) []CertificateValidationError { return v.ValidationErrors }).(CertificateValidationErrorArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetAppCertificateResultOutput{})
}
