// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetMachinesMetadata(ctx *pulumi.Context, args *GetMachinesMetadataArgs, opts ...pulumi.InvokeOption) (interface{}, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv map[string]interface{}
	err := ctx.Invoke("fly-machines:apps/v1:getMachinesMetadata", args, &rv, opts...)
	var result interface{}
	if err != nil {
		return result, err
	}
	for _, v := range rv {
		result = v
		break
	}
	return result, nil
}

type GetMachinesMetadataArgs struct {
	// Fly App Name
	AppName string `pulumi:"appName"`
	// Machine ID
	MachineId string `pulumi:"machineId"`
}

func GetMachinesMetadataOutput(ctx *pulumi.Context, args GetMachinesMetadataOutputArgs, opts ...pulumi.InvokeOption) pulumi.AnyOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	rv := ctx.InvokeOutput("fly-machines:apps/v1:getMachinesMetadata", args, pulumi.MapOutput{}, options).(pulumi.MapOutput)
	return rv.ApplyT(func(rv map[string]interface{}) interface{} {
		var result interface{}
		for _, v := range rv {
			result = v
		}
		return result
	}).(pulumi.AnyOutput)
}

type GetMachinesMetadataOutputArgs struct {
	// Fly App Name
	AppName pulumi.StringInput `pulumi:"appName"`
	// Machine ID
	MachineId pulumi.StringInput `pulumi:"machineId"`
}

func (GetMachinesMetadataOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMachinesMetadataArgs)(nil)).Elem()
}
