// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupVolume(ctx *pulumi.Context, args *LookupVolumeArgs, opts ...pulumi.InvokeOption) (*LookupVolumeResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVolumeResult
	err := ctx.Invoke("fly-machines:apps/v1:getVolume", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupVolumeArgs struct {
	// Fly App Name
	AppName string `pulumi:"appName"`
	// Volume ID
	VolumeId string `pulumi:"volumeId"`
}

type LookupVolumeResult struct {
	AttachedAllocId      *string           `pulumi:"attachedAllocId"`
	AttachedMachineId    *string           `pulumi:"attachedMachineId"`
	AutoBackupEnabled    *bool             `pulumi:"autoBackupEnabled"`
	BlockSize            *int              `pulumi:"blockSize"`
	Blocks               *int              `pulumi:"blocks"`
	BlocksAvail          *int              `pulumi:"blocksAvail"`
	BlocksFree           *int              `pulumi:"blocksFree"`
	BytesTotal           *int              `pulumi:"bytesTotal"`
	BytesUsed            *int              `pulumi:"bytesUsed"`
	CreatedAt            *string           `pulumi:"createdAt"`
	Encrypted            *bool             `pulumi:"encrypted"`
	Fstype               *string           `pulumi:"fstype"`
	HostFeatures         []string          `pulumi:"hostFeatures"`
	HostStatus           *VolumeHostStatus `pulumi:"hostStatus"`
	Id                   *string           `pulumi:"id"`
	Name                 *string           `pulumi:"name"`
	Region               *string           `pulumi:"region"`
	RequiredHostFeatures []string          `pulumi:"requiredHostFeatures"`
	SizeGb               *int              `pulumi:"sizeGb"`
	SnapshotRetention    *int              `pulumi:"snapshotRetention"`
	State                *string           `pulumi:"state"`
	Type                 *VolumeTypeEnum   `pulumi:"type"`
	Zone                 *string           `pulumi:"zone"`
}

func LookupVolumeOutput(ctx *pulumi.Context, args LookupVolumeOutputArgs, opts ...pulumi.InvokeOption) LookupVolumeResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:apps/v1:getVolume", args, LookupVolumeResultOutput{}, options).(LookupVolumeResultOutput)
}

type LookupVolumeOutputArgs struct {
	// Fly App Name
	AppName pulumi.StringInput `pulumi:"appName"`
	// Volume ID
	VolumeId pulumi.StringInput `pulumi:"volumeId"`
}

func (LookupVolumeOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVolumeArgs)(nil)).Elem()
}

type LookupVolumeResultOutput struct{ *pulumi.OutputState }

func (LookupVolumeResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVolumeResult)(nil)).Elem()
}

func (o LookupVolumeResultOutput) ToLookupVolumeResultOutput() LookupVolumeResultOutput {
	return o
}

func (o LookupVolumeResultOutput) ToLookupVolumeResultOutputWithContext(ctx context.Context) LookupVolumeResultOutput {
	return o
}

func (o LookupVolumeResultOutput) AttachedAllocId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.AttachedAllocId }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) AttachedMachineId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.AttachedMachineId }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) AutoBackupEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *bool { return v.AutoBackupEnabled }).(pulumi.BoolPtrOutput)
}

func (o LookupVolumeResultOutput) BlockSize() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.BlockSize }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) Blocks() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.Blocks }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) BlocksAvail() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.BlocksAvail }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) BlocksFree() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.BlocksFree }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) BytesTotal() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.BytesTotal }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) BytesUsed() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.BytesUsed }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) Encrypted() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *bool { return v.Encrypted }).(pulumi.BoolPtrOutput)
}

func (o LookupVolumeResultOutput) Fstype() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.Fstype }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) HostFeatures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupVolumeResult) []string { return v.HostFeatures }).(pulumi.StringArrayOutput)
}

func (o LookupVolumeResultOutput) HostStatus() VolumeHostStatusPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *VolumeHostStatus { return v.HostStatus }).(VolumeHostStatusPtrOutput)
}

func (o LookupVolumeResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.Region }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) RequiredHostFeatures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupVolumeResult) []string { return v.RequiredHostFeatures }).(pulumi.StringArrayOutput)
}

func (o LookupVolumeResultOutput) SizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.SizeGb }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) SnapshotRetention() pulumi.IntPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *int { return v.SnapshotRetention }).(pulumi.IntPtrOutput)
}

func (o LookupVolumeResultOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.State }).(pulumi.StringPtrOutput)
}

func (o LookupVolumeResultOutput) Type() VolumeTypeEnumPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *VolumeTypeEnum { return v.Type }).(VolumeTypeEnumPtrOutput)
}

func (o LookupVolumeResultOutput) Zone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVolumeResult) *string { return v.Zone }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVolumeResultOutput{})
}
