// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListMachinesVersions(ctx *pulumi.Context, args *ListMachinesVersionsArgs, opts ...pulumi.InvokeOption) (*ListMachinesVersionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListMachinesVersionsResult
	err := ctx.Invoke("fly-machines:apps/v1:listMachinesVersions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListMachinesVersionsArgs struct {
	// Fly App Name
	AppName string `pulumi:"appName"`
	// Machine ID
	MachineId string `pulumi:"machineId"`
}

type ListMachinesVersionsResult struct {
	Items []MachineVersion `pulumi:"items"`
}

func ListMachinesVersionsOutput(ctx *pulumi.Context, args ListMachinesVersionsOutputArgs, opts ...pulumi.InvokeOption) ListMachinesVersionsResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:apps/v1:listMachinesVersions", args, ListMachinesVersionsResultOutput{}, options).(ListMachinesVersionsResultOutput)
}

type ListMachinesVersionsOutputArgs struct {
	// Fly App Name
	AppName pulumi.StringInput `pulumi:"appName"`
	// Machine ID
	MachineId pulumi.StringInput `pulumi:"machineId"`
}

func (ListMachinesVersionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListMachinesVersionsArgs)(nil)).Elem()
}

type ListMachinesVersionsResultOutput struct{ *pulumi.OutputState }

func (ListMachinesVersionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListMachinesVersionsResult)(nil)).Elem()
}

func (o ListMachinesVersionsResultOutput) ToListMachinesVersionsResultOutput() ListMachinesVersionsResultOutput {
	return o
}

func (o ListMachinesVersionsResultOutput) ToListMachinesVersionsResultOutputWithContext(ctx context.Context) ListMachinesVersionsResultOutput {
	return o
}

func (o ListMachinesVersionsResultOutput) Items() MachineVersionArrayOutput {
	return o.ApplyT(func(v ListMachinesVersionsResult) []MachineVersion { return v.Items }).(MachineVersionArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ListMachinesVersionsResultOutput{})
}
