// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListApps(ctx *pulumi.Context, args *ListAppsArgs, opts ...pulumi.InvokeOption) (*ListAppsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListAppsResult
	err := ctx.Invoke("fly-machines:apps/v1:listApps", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListAppsArgs struct {
}

type ListAppsResult struct {
	Apps      []AppType `pulumi:"apps"`
	TotalApps *int      `pulumi:"totalApps"`
}

func ListAppsOutput(ctx *pulumi.Context, args ListAppsOutputArgs, opts ...pulumi.InvokeOption) ListAppsResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:apps/v1:listApps", args, ListAppsResultOutput{}, options).(ListAppsResultOutput)
}

type ListAppsOutputArgs struct {
}

func (ListAppsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListAppsArgs)(nil)).Elem()
}

type ListAppsResultOutput struct{ *pulumi.OutputState }

func (ListAppsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListAppsResult)(nil)).Elem()
}

func (o ListAppsResultOutput) ToListAppsResultOutput() ListAppsResultOutput {
	return o
}

func (o ListAppsResultOutput) ToListAppsResultOutputWithContext(ctx context.Context) ListAppsResultOutput {
	return o
}

func (o ListAppsResultOutput) Apps() AppTypeArrayOutput {
	return o.ApplyT(func(v ListAppsResult) []AppType { return v.Apps }).(AppTypeArrayOutput)
}

func (o ListAppsResultOutput) TotalApps() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListAppsResult) *int { return v.TotalApps }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ListAppsResultOutput{})
}
