// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListAppCertificates(ctx *pulumi.Context, args *ListAppCertificatesArgs, opts ...pulumi.InvokeOption) (*ListAppCertificatesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListAppCertificatesResult
	err := ctx.Invoke("fly-machines:apps/v1:listAppCertificates", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListAppCertificatesArgs struct {
	// Fly App Name
	AppName string `pulumi:"appName"`
	// Query params to send with the API request.
	QueryParams *ListAppCertificatesQueryParams `pulumi:"queryParams"`
}

type ListAppCertificatesResult struct {
	Certificates []CertificateSummary `pulumi:"certificates"`
	NextCursor   *string              `pulumi:"nextCursor"`
	TotalCount   *int                 `pulumi:"totalCount"`
}

func ListAppCertificatesOutput(ctx *pulumi.Context, args ListAppCertificatesOutputArgs, opts ...pulumi.InvokeOption) ListAppCertificatesResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("fly-machines:apps/v1:listAppCertificates", args, ListAppCertificatesResultOutput{}, options).(ListAppCertificatesResultOutput)
}

type ListAppCertificatesOutputArgs struct {
	// Fly App Name
	AppName pulumi.StringInput `pulumi:"appName"`
	// Query params to send with the API request.
	QueryParams ListAppCertificatesQueryParamsPtrInput `pulumi:"queryParams"`
}

func (ListAppCertificatesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListAppCertificatesArgs)(nil)).Elem()
}

type ListAppCertificatesResultOutput struct{ *pulumi.OutputState }

func (ListAppCertificatesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListAppCertificatesResult)(nil)).Elem()
}

func (o ListAppCertificatesResultOutput) ToListAppCertificatesResultOutput() ListAppCertificatesResultOutput {
	return o
}

func (o ListAppCertificatesResultOutput) ToListAppCertificatesResultOutputWithContext(ctx context.Context) ListAppCertificatesResultOutput {
	return o
}

func (o ListAppCertificatesResultOutput) Certificates() CertificateSummaryArrayOutput {
	return o.ApplyT(func(v ListAppCertificatesResult) []CertificateSummary { return v.Certificates }).(CertificateSummaryArrayOutput)
}

func (o ListAppCertificatesResultOutput) NextCursor() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ListAppCertificatesResult) *string { return v.NextCursor }).(pulumi.StringPtrOutput)
}

func (o ListAppCertificatesResultOutput) TotalCount() pulumi.IntPtrOutput {
	return o.ApplyT(func(v ListAppCertificatesResult) *int { return v.TotalCount }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ListAppCertificatesResultOutput{})
}
