// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type MachinesStart struct {
	pulumi.CustomResourceState
}

// NewMachinesStart registers a new resource with the given unique name, arguments, and options.
func NewMachinesStart(ctx *pulumi.Context,
	name string, args *MachinesStartArgs, opts ...pulumi.ResourceOption) (*MachinesStart, error) {
	if args == nil {
		args = &MachinesStartArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MachinesStart
	err := ctx.RegisterResource("fly-machines:apps/v1:MachinesStart", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMachinesStart gets an existing MachinesStart resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMachinesStart(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MachinesStartState, opts ...pulumi.ResourceOption) (*MachinesStart, error) {
	var resource MachinesStart
	err := ctx.ReadResource("fly-machines:apps/v1:MachinesStart", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MachinesStart resources.
type machinesStartState struct {
}

type MachinesStartState struct {
}

func (MachinesStartState) ElementType() reflect.Type {
	return reflect.TypeOf((*machinesStartState)(nil)).Elem()
}

type machinesStartArgs struct {
	// Fly App Name
	AppName *string `pulumi:"appName"`
	// Machine ID
	MachineId *string `pulumi:"machineId"`
}

// The set of arguments for constructing a MachinesStart resource.
type MachinesStartArgs struct {
	// Fly App Name
	AppName pulumi.StringPtrInput
	// Machine ID
	MachineId pulumi.StringPtrInput
}

func (MachinesStartArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*machinesStartArgs)(nil)).Elem()
}

type MachinesStartInput interface {
	pulumi.Input

	ToMachinesStartOutput() MachinesStartOutput
	ToMachinesStartOutputWithContext(ctx context.Context) MachinesStartOutput
}

func (*MachinesStart) ElementType() reflect.Type {
	return reflect.TypeOf((**MachinesStart)(nil)).Elem()
}

func (i *MachinesStart) ToMachinesStartOutput() MachinesStartOutput {
	return i.ToMachinesStartOutputWithContext(context.Background())
}

func (i *MachinesStart) ToMachinesStartOutputWithContext(ctx context.Context) MachinesStartOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachinesStartOutput)
}

type MachinesStartOutput struct{ *pulumi.OutputState }

func (MachinesStartOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MachinesStart)(nil)).Elem()
}

func (o MachinesStartOutput) ToMachinesStartOutput() MachinesStartOutput {
	return o
}

func (o MachinesStartOutput) ToMachinesStartOutputWithContext(ctx context.Context) MachinesStartOutput {
	return o
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MachinesStartInput)(nil)).Elem(), &MachinesStart{})
	pulumi.RegisterOutputType(MachinesStartOutput{})
}
