// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type MachinesMetadataKey struct {
	pulumi.CustomResourceState

	// Query params to send with the API requests for this resource.
	QueryParams MachinesMetadataKeyQueryParamsPtrOutput `pulumi:"queryParams"`
	UpdatedAt   pulumi.StringPtrOutput                  `pulumi:"updatedAt"`
	Value       pulumi.StringPtrOutput                  `pulumi:"value"`
}

// NewMachinesMetadataKey registers a new resource with the given unique name, arguments, and options.
func NewMachinesMetadataKey(ctx *pulumi.Context,
	name string, args *MachinesMetadataKeyArgs, opts ...pulumi.ResourceOption) (*MachinesMetadataKey, error) {
	if args == nil {
		args = &MachinesMetadataKeyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MachinesMetadataKey
	err := ctx.RegisterResource("fly-machines:apps/v1:MachinesMetadataKey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMachinesMetadataKey gets an existing MachinesMetadataKey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMachinesMetadataKey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MachinesMetadataKeyState, opts ...pulumi.ResourceOption) (*MachinesMetadataKey, error) {
	var resource MachinesMetadataKey
	err := ctx.ReadResource("fly-machines:apps/v1:MachinesMetadataKey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MachinesMetadataKey resources.
type machinesMetadataKeyState struct {
}

type MachinesMetadataKeyState struct {
}

func (MachinesMetadataKeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*machinesMetadataKeyState)(nil)).Elem()
}

type machinesMetadataKeyArgs struct {
	// Fly App Name
	AppName *string `pulumi:"appName"`
	// Metadata Key
	Key *string `pulumi:"key"`
	// Machine ID
	MachineId *string `pulumi:"machineId"`
	// Query params to send with the API requests for this resource.
	QueryParams *MachinesMetadataKeyQueryParams `pulumi:"queryParams"`
	UpdatedAt   *string                         `pulumi:"updatedAt"`
	Value       *string                         `pulumi:"value"`
}

// The set of arguments for constructing a MachinesMetadataKey resource.
type MachinesMetadataKeyArgs struct {
	// Fly App Name
	AppName pulumi.StringPtrInput
	// Metadata Key
	Key pulumi.StringPtrInput
	// Machine ID
	MachineId pulumi.StringPtrInput
	// Query params to send with the API requests for this resource.
	QueryParams MachinesMetadataKeyQueryParamsPtrInput
	UpdatedAt   pulumi.StringPtrInput
	Value       pulumi.StringPtrInput
}

func (MachinesMetadataKeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*machinesMetadataKeyArgs)(nil)).Elem()
}

type MachinesMetadataKeyInput interface {
	pulumi.Input

	ToMachinesMetadataKeyOutput() MachinesMetadataKeyOutput
	ToMachinesMetadataKeyOutputWithContext(ctx context.Context) MachinesMetadataKeyOutput
}

func (*MachinesMetadataKey) ElementType() reflect.Type {
	return reflect.TypeOf((**MachinesMetadataKey)(nil)).Elem()
}

func (i *MachinesMetadataKey) ToMachinesMetadataKeyOutput() MachinesMetadataKeyOutput {
	return i.ToMachinesMetadataKeyOutputWithContext(context.Background())
}

func (i *MachinesMetadataKey) ToMachinesMetadataKeyOutputWithContext(ctx context.Context) MachinesMetadataKeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MachinesMetadataKeyOutput)
}

type MachinesMetadataKeyOutput struct{ *pulumi.OutputState }

func (MachinesMetadataKeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MachinesMetadataKey)(nil)).Elem()
}

func (o MachinesMetadataKeyOutput) ToMachinesMetadataKeyOutput() MachinesMetadataKeyOutput {
	return o
}

func (o MachinesMetadataKeyOutput) ToMachinesMetadataKeyOutputWithContext(ctx context.Context) MachinesMetadataKeyOutput {
	return o
}

// Query params to send with the API requests for this resource.
func (o MachinesMetadataKeyOutput) QueryParams() MachinesMetadataKeyQueryParamsPtrOutput {
	return o.ApplyT(func(v *MachinesMetadataKey) MachinesMetadataKeyQueryParamsPtrOutput { return v.QueryParams }).(MachinesMetadataKeyQueryParamsPtrOutput)
}

func (o MachinesMetadataKeyOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MachinesMetadataKey) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

func (o MachinesMetadataKeyOutput) Value() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MachinesMetadataKey) pulumi.StringPtrOutput { return v.Value }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MachinesMetadataKeyInput)(nil)).Elem(), &MachinesMetadataKey{})
	pulumi.RegisterOutputType(MachinesMetadataKeyOutput{})
}
