// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SecretsUpdate struct {
	pulumi.CustomResourceState

	Secrets AppSecretArrayOutput `pulumi:"secrets"`
	Values  pulumi.AnyOutput     `pulumi:"values"`
	Version pulumi.IntPtrOutput  `pulumi:"version"`
}

// NewSecretsUpdate registers a new resource with the given unique name, arguments, and options.
func NewSecretsUpdate(ctx *pulumi.Context,
	name string, args *SecretsUpdateArgs, opts ...pulumi.ResourceOption) (*SecretsUpdate, error) {
	if args == nil {
		args = &SecretsUpdateArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SecretsUpdate
	err := ctx.RegisterResource("fly-machines:apps/v1:SecretsUpdate", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecretsUpdate gets an existing SecretsUpdate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecretsUpdate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecretsUpdateState, opts ...pulumi.ResourceOption) (*SecretsUpdate, error) {
	var resource SecretsUpdate
	err := ctx.ReadResource("fly-machines:apps/v1:SecretsUpdate", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecretsUpdate resources.
type secretsUpdateState struct {
}

type SecretsUpdateState struct {
}

func (SecretsUpdateState) ElementType() reflect.Type {
	return reflect.TypeOf((*secretsUpdateState)(nil)).Elem()
}

type secretsUpdateArgs struct {
	// Fly App Name
	AppName *string     `pulumi:"appName"`
	Values  interface{} `pulumi:"values"`
}

// The set of arguments for constructing a SecretsUpdate resource.
type SecretsUpdateArgs struct {
	// Fly App Name
	AppName pulumi.StringPtrInput
	Values  pulumi.Input
}

func (SecretsUpdateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*secretsUpdateArgs)(nil)).Elem()
}

type SecretsUpdateInput interface {
	pulumi.Input

	ToSecretsUpdateOutput() SecretsUpdateOutput
	ToSecretsUpdateOutputWithContext(ctx context.Context) SecretsUpdateOutput
}

func (*SecretsUpdate) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretsUpdate)(nil)).Elem()
}

func (i *SecretsUpdate) ToSecretsUpdateOutput() SecretsUpdateOutput {
	return i.ToSecretsUpdateOutputWithContext(context.Background())
}

func (i *SecretsUpdate) ToSecretsUpdateOutputWithContext(ctx context.Context) SecretsUpdateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretsUpdateOutput)
}

type SecretsUpdateOutput struct{ *pulumi.OutputState }

func (SecretsUpdateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretsUpdate)(nil)).Elem()
}

func (o SecretsUpdateOutput) ToSecretsUpdateOutput() SecretsUpdateOutput {
	return o
}

func (o SecretsUpdateOutput) ToSecretsUpdateOutputWithContext(ctx context.Context) SecretsUpdateOutput {
	return o
}

func (o SecretsUpdateOutput) Secrets() AppSecretArrayOutput {
	return o.ApplyT(func(v *SecretsUpdate) AppSecretArrayOutput { return v.Secrets }).(AppSecretArrayOutput)
}

func (o SecretsUpdateOutput) Values() pulumi.AnyOutput {
	return o.ApplyT(func(v *SecretsUpdate) pulumi.AnyOutput { return v.Values }).(pulumi.AnyOutput)
}

func (o SecretsUpdateOutput) Version() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *SecretsUpdate) pulumi.IntPtrOutput { return v.Version }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecretsUpdateInput)(nil)).Elem(), &SecretsUpdate{})
	pulumi.RegisterOutputType(SecretsUpdateOutput{})
}
