// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Secretkey struct {
	pulumi.CustomResourceState

	CreatedAt pulumi.StringPtrOutput `pulumi:"createdAt"`
	Name      pulumi.StringPtrOutput `pulumi:"name"`
	PublicKey pulumi.IntArrayOutput  `pulumi:"publicKey"`
	Type      pulumi.StringPtrOutput `pulumi:"type"`
	UpdatedAt pulumi.StringPtrOutput `pulumi:"updatedAt"`
	Value     pulumi.IntArrayOutput  `pulumi:"value"`
	Version   pulumi.IntPtrOutput    `pulumi:"version"`
}

// NewSecretkey registers a new resource with the given unique name, arguments, and options.
func NewSecretkey(ctx *pulumi.Context,
	name string, args *SecretkeyArgs, opts ...pulumi.ResourceOption) (*Secretkey, error) {
	if args == nil {
		args = &SecretkeyArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Secretkey
	err := ctx.RegisterResource("fly-machines:apps/v1:Secretkey", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecretkey gets an existing Secretkey resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecretkey(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecretkeyState, opts ...pulumi.ResourceOption) (*Secretkey, error) {
	var resource Secretkey
	err := ctx.ReadResource("fly-machines:apps/v1:Secretkey", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Secretkey resources.
type secretkeyState struct {
}

type SecretkeyState struct {
}

func (SecretkeyState) ElementType() reflect.Type {
	return reflect.TypeOf((*secretkeyState)(nil)).Elem()
}

type secretkeyArgs struct {
	// Fly App Name
	AppName *string `pulumi:"appName"`
	// Secret key name
	SecretName *string `pulumi:"secretName"`
	Type       *string `pulumi:"type"`
	Value      []int   `pulumi:"value"`
}

// The set of arguments for constructing a Secretkey resource.
type SecretkeyArgs struct {
	// Fly App Name
	AppName pulumi.StringPtrInput
	// Secret key name
	SecretName pulumi.StringPtrInput
	Type       pulumi.StringPtrInput
	Value      pulumi.IntArrayInput
}

func (SecretkeyArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*secretkeyArgs)(nil)).Elem()
}

type SecretkeyInput interface {
	pulumi.Input

	ToSecretkeyOutput() SecretkeyOutput
	ToSecretkeyOutputWithContext(ctx context.Context) SecretkeyOutput
}

func (*Secretkey) ElementType() reflect.Type {
	return reflect.TypeOf((**Secretkey)(nil)).Elem()
}

func (i *Secretkey) ToSecretkeyOutput() SecretkeyOutput {
	return i.ToSecretkeyOutputWithContext(context.Background())
}

func (i *Secretkey) ToSecretkeyOutputWithContext(ctx context.Context) SecretkeyOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretkeyOutput)
}

type SecretkeyOutput struct{ *pulumi.OutputState }

func (SecretkeyOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Secretkey)(nil)).Elem()
}

func (o SecretkeyOutput) ToSecretkeyOutput() SecretkeyOutput {
	return o
}

func (o SecretkeyOutput) ToSecretkeyOutputWithContext(ctx context.Context) SecretkeyOutput {
	return o
}

func (o SecretkeyOutput) CreatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.StringPtrOutput { return v.CreatedAt }).(pulumi.StringPtrOutput)
}

func (o SecretkeyOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.StringPtrOutput { return v.Name }).(pulumi.StringPtrOutput)
}

func (o SecretkeyOutput) PublicKey() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.IntArrayOutput { return v.PublicKey }).(pulumi.IntArrayOutput)
}

func (o SecretkeyOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.StringPtrOutput { return v.Type }).(pulumi.StringPtrOutput)
}

func (o SecretkeyOutput) UpdatedAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.StringPtrOutput { return v.UpdatedAt }).(pulumi.StringPtrOutput)
}

func (o SecretkeyOutput) Value() pulumi.IntArrayOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.IntArrayOutput { return v.Value }).(pulumi.IntArrayOutput)
}

func (o SecretkeyOutput) Version() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Secretkey) pulumi.IntPtrOutput { return v.Version }).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecretkeyInput)(nil)).Elem(), &Secretkey{})
	pulumi.RegisterOutputType(SecretkeyOutput{})
}
