// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type VolumesExtend struct {
	pulumi.CustomResourceState

	NeedsRestart pulumi.BoolPtrOutput `pulumi:"needsRestart"`
	// Query params to send with the API requests for this resource.
	QueryParams VolumesExtendQueryParamsPtrOutput `pulumi:"queryParams"`
	SizeGb      pulumi.IntPtrOutput               `pulumi:"sizeGb"`
	Volume      VolumeTypePtrOutput               `pulumi:"volume"`
}

// NewVolumesExtend registers a new resource with the given unique name, arguments, and options.
func NewVolumesExtend(ctx *pulumi.Context,
	name string, args *VolumesExtendArgs, opts ...pulumi.ResourceOption) (*VolumesExtend, error) {
	if args == nil {
		args = &VolumesExtendArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource VolumesExtend
	err := ctx.RegisterResource("fly-machines:apps/v1:VolumesExtend", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolumesExtend gets an existing VolumesExtend resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolumesExtend(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumesExtendState, opts ...pulumi.ResourceOption) (*VolumesExtend, error) {
	var resource VolumesExtend
	err := ctx.ReadResource("fly-machines:apps/v1:VolumesExtend", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VolumesExtend resources.
type volumesExtendState struct {
}

type VolumesExtendState struct {
}

func (VolumesExtendState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumesExtendState)(nil)).Elem()
}

type volumesExtendArgs struct {
	// Fly App Name
	AppName *string `pulumi:"appName"`
	// Query params to send with the API requests for this resource.
	QueryParams *VolumesExtendQueryParams `pulumi:"queryParams"`
	SizeGb      *int                      `pulumi:"sizeGb"`
	// Volume ID
	VolumeId *string `pulumi:"volumeId"`
}

// The set of arguments for constructing a VolumesExtend resource.
type VolumesExtendArgs struct {
	// Fly App Name
	AppName pulumi.StringPtrInput
	// Query params to send with the API requests for this resource.
	QueryParams VolumesExtendQueryParamsPtrInput
	SizeGb      pulumi.IntPtrInput
	// Volume ID
	VolumeId pulumi.StringPtrInput
}

func (VolumesExtendArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumesExtendArgs)(nil)).Elem()
}

type VolumesExtendInput interface {
	pulumi.Input

	ToVolumesExtendOutput() VolumesExtendOutput
	ToVolumesExtendOutputWithContext(ctx context.Context) VolumesExtendOutput
}

func (*VolumesExtend) ElementType() reflect.Type {
	return reflect.TypeOf((**VolumesExtend)(nil)).Elem()
}

func (i *VolumesExtend) ToVolumesExtendOutput() VolumesExtendOutput {
	return i.ToVolumesExtendOutputWithContext(context.Background())
}

func (i *VolumesExtend) ToVolumesExtendOutputWithContext(ctx context.Context) VolumesExtendOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumesExtendOutput)
}

type VolumesExtendOutput struct{ *pulumi.OutputState }

func (VolumesExtendOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VolumesExtend)(nil)).Elem()
}

func (o VolumesExtendOutput) ToVolumesExtendOutput() VolumesExtendOutput {
	return o
}

func (o VolumesExtendOutput) ToVolumesExtendOutputWithContext(ctx context.Context) VolumesExtendOutput {
	return o
}

func (o VolumesExtendOutput) NeedsRestart() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *VolumesExtend) pulumi.BoolPtrOutput { return v.NeedsRestart }).(pulumi.BoolPtrOutput)
}

// Query params to send with the API requests for this resource.
func (o VolumesExtendOutput) QueryParams() VolumesExtendQueryParamsPtrOutput {
	return o.ApplyT(func(v *VolumesExtend) VolumesExtendQueryParamsPtrOutput { return v.QueryParams }).(VolumesExtendQueryParamsPtrOutput)
}

func (o VolumesExtendOutput) SizeGb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *VolumesExtend) pulumi.IntPtrOutput { return v.SizeGb }).(pulumi.IntPtrOutput)
}

func (o VolumesExtendOutput) Volume() VolumeTypePtrOutput {
	return o.ApplyT(func(v *VolumesExtend) VolumeTypePtrOutput { return v.Volume }).(VolumeTypePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumesExtendInput)(nil)).Elem(), &VolumesExtend{})
	pulumi.RegisterOutputType(VolumesExtendOutput{})
}
