// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.TokensV1
{
    [FlyMachinesResourceType("fly-machines:tokens/v1:TokensAuthenticate")]
    public partial class TokensAuthenticate : global::Pulumi.CustomResource
    {
        [Output("header")]
        public Output<string?> Header { get; private set; } = null!;


        /// <summary>
        /// Create a TokensAuthenticate resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TokensAuthenticate(string name, TokensAuthenticateArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:tokens/v1:TokensAuthenticate", name, args ?? new TokensAuthenticateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TokensAuthenticate(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:tokens/v1:TokensAuthenticate", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TokensAuthenticate resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TokensAuthenticate Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new TokensAuthenticate(name, id, options);
        }
    }

    public sealed class TokensAuthenticateArgs : global::Pulumi.ResourceArgs
    {
        [Input("header")]
        public Input<string>? Header { get; set; }

        public TokensAuthenticateArgs()
        {
        }
        public static new TokensAuthenticateArgs Empty => new TokensAuthenticateArgs();
    }
}
