// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:AppDeployToken")]
    public partial class AppDeployToken : global::Pulumi.CustomResource
    {
        [Output("expiry")]
        public Output<string?> Expiry { get; private set; } = null!;

        [Output("token")]
        public Output<string?> Token { get; private set; } = null!;


        /// <summary>
        /// Create a AppDeployToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AppDeployToken(string name, AppDeployTokenArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:AppDeployToken", name, args ?? new AppDeployTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AppDeployToken(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:AppDeployToken", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AppDeployToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AppDeployToken Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new AppDeployToken(name, id, options);
        }
    }

    public sealed class AppDeployTokenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        [Input("expiry")]
        public Input<string>? Expiry { get; set; }

        public AppDeployTokenArgs()
        {
        }
        public static new AppDeployTokenArgs Empty => new AppDeployTokenArgs();
    }
}
