// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.FlyMachines.AppsV1
{
    /// <summary>
    /// Type of IP address to allocate. "egress-pair" allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).
    /// </summary>
    [EnumType]
    public readonly struct AppIPAssignmentType : IEquatable<AppIPAssignmentType>
    {
        private readonly string _value;

        private AppIPAssignmentType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static AppIPAssignmentType V4 { get; } = new AppIPAssignmentType("v4");
        public static AppIPAssignmentType V6 { get; } = new AppIPAssignmentType("v6");
        public static AppIPAssignmentType SharedV4 { get; } = new AppIPAssignmentType("shared_v4");
        public static AppIPAssignmentType PrivateV6 { get; } = new AppIPAssignmentType("private_v6");
        public static AppIPAssignmentType EgressV4 { get; } = new AppIPAssignmentType("egress_v4");
        public static AppIPAssignmentType EgressV6 { get; } = new AppIPAssignmentType("egress_v6");
        public static AppIPAssignmentType EgressPair { get; } = new AppIPAssignmentType("egress_pair");

        public static bool operator ==(AppIPAssignmentType left, AppIPAssignmentType right) => left.Equals(right);
        public static bool operator !=(AppIPAssignmentType left, AppIPAssignmentType right) => !left.Equals(right);

        public static explicit operator string(AppIPAssignmentType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is AppIPAssignmentType other && Equals(other);
        public bool Equals(AppIPAssignmentType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct CertificateEntrySource : IEquatable<CertificateEntrySource>
    {
        private readonly string _value;

        private CertificateEntrySource(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static CertificateEntrySource Custom { get; } = new CertificateEntrySource("custom");
        public static CertificateEntrySource Fly { get; } = new CertificateEntrySource("fly");

        public static bool operator ==(CertificateEntrySource left, CertificateEntrySource right) => left.Equals(right);
        public static bool operator !=(CertificateEntrySource left, CertificateEntrySource right) => !left.Equals(right);

        public static explicit operator string(CertificateEntrySource value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is CertificateEntrySource other && Equals(other);
        public bool Equals(CertificateEntrySource other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct CertificateEntryStatus : IEquatable<CertificateEntryStatus>
    {
        private readonly string _value;

        private CertificateEntryStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static CertificateEntryStatus Active { get; } = new CertificateEntryStatus("active");
        public static CertificateEntryStatus PendingOwnership { get; } = new CertificateEntryStatus("pending_ownership");
        public static CertificateEntryStatus PendingValidation { get; } = new CertificateEntryStatus("pending_validation");

        public static bool operator ==(CertificateEntryStatus left, CertificateEntryStatus right) => left.Equals(right);
        public static bool operator !=(CertificateEntryStatus left, CertificateEntryStatus right) => !left.Equals(right);

        public static explicit operator string(CertificateEntryStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is CertificateEntryStatus other && Equals(other);
        public bool Equals(CertificateEntryStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image.
    /// </summary>
    [EnumType]
    public readonly struct FlyEnvFromFieldRef : IEquatable<FlyEnvFromFieldRef>
    {
        private readonly string _value;

        private FlyEnvFromFieldRef(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyEnvFromFieldRef Id { get; } = new FlyEnvFromFieldRef("id");
        public static FlyEnvFromFieldRef Version { get; } = new FlyEnvFromFieldRef("version");
        public static FlyEnvFromFieldRef AppName { get; } = new FlyEnvFromFieldRef("app_name");
        public static FlyEnvFromFieldRef PrivateIp { get; } = new FlyEnvFromFieldRef("private_ip");
        public static FlyEnvFromFieldRef Region { get; } = new FlyEnvFromFieldRef("region");
        public static FlyEnvFromFieldRef Image { get; } = new FlyEnvFromFieldRef("image");

        public static bool operator ==(FlyEnvFromFieldRef left, FlyEnvFromFieldRef right) => left.Equals(right);
        public static bool operator !=(FlyEnvFromFieldRef left, FlyEnvFromFieldRef right) => !left.Equals(right);

        public static explicit operator string(FlyEnvFromFieldRef value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyEnvFromFieldRef other && Equals(other);
        public bool Equals(FlyEnvFromFieldRef other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// Deprecated: use MachineConfig.Rootfs instead
    /// </summary>
    [EnumType]
    public readonly struct FlyMachineGuestPersistRootfs : IEquatable<FlyMachineGuestPersistRootfs>
    {
        private readonly string _value;

        private FlyMachineGuestPersistRootfs(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyMachineGuestPersistRootfs Never { get; } = new FlyMachineGuestPersistRootfs("never");
        public static FlyMachineGuestPersistRootfs Always { get; } = new FlyMachineGuestPersistRootfs("always");
        public static FlyMachineGuestPersistRootfs Restart { get; } = new FlyMachineGuestPersistRootfs("restart");

        public static bool operator ==(FlyMachineGuestPersistRootfs left, FlyMachineGuestPersistRootfs right) => left.Equals(right);
        public static bool operator !=(FlyMachineGuestPersistRootfs left, FlyMachineGuestPersistRootfs right) => !left.Equals(right);

        public static explicit operator string(FlyMachineGuestPersistRootfs value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyMachineGuestPersistRootfs other && Equals(other);
        public bool Equals(FlyMachineGuestPersistRootfs other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// * no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.
    /// * always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.
    /// * on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.
    /// </summary>
    [EnumType]
    public readonly struct FlyMachineRestartPolicy : IEquatable<FlyMachineRestartPolicy>
    {
        private readonly string _value;

        private FlyMachineRestartPolicy(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyMachineRestartPolicy No { get; } = new FlyMachineRestartPolicy("no");
        public static FlyMachineRestartPolicy Always { get; } = new FlyMachineRestartPolicy("always");
        public static FlyMachineRestartPolicy OnFailure { get; } = new FlyMachineRestartPolicy("on-failure");

        public static bool operator ==(FlyMachineRestartPolicy left, FlyMachineRestartPolicy right) => left.Equals(right);
        public static bool operator !=(FlyMachineRestartPolicy left, FlyMachineRestartPolicy right) => !left.Equals(right);

        public static explicit operator string(FlyMachineRestartPolicy value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyMachineRestartPolicy other && Equals(other);
        public bool Equals(FlyMachineRestartPolicy other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct FlyMachineRootfsPersist : IEquatable<FlyMachineRootfsPersist>
    {
        private readonly string _value;

        private FlyMachineRootfsPersist(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyMachineRootfsPersist Never { get; } = new FlyMachineRootfsPersist("never");
        public static FlyMachineRootfsPersist Always { get; } = new FlyMachineRootfsPersist("always");
        public static FlyMachineRootfsPersist Restart { get; } = new FlyMachineRootfsPersist("restart");

        public static bool operator ==(FlyMachineRootfsPersist left, FlyMachineRootfsPersist right) => left.Equals(right);
        public static bool operator !=(FlyMachineRootfsPersist left, FlyMachineRootfsPersist right) => !left.Equals(right);

        public static explicit operator string(FlyMachineRootfsPersist value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyMachineRootfsPersist other && Equals(other);
        public bool Equals(FlyMachineRootfsPersist other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// Accepts a string (new format) or a boolean (old format). For backward compatibility with older clients, the API continues to use booleans for "off" and "stop" in responses.
    /// * "off" or false - Do not autostop the Machine.
    /// * "stop" or true - Automatically stop the Machine.
    /// * "suspend" - Automatically suspend the Machine, falling back to a full stop if this is not possible.
    /// </summary>
    [EnumType]
    public readonly struct FlyMachineServiceAutostop : IEquatable<FlyMachineServiceAutostop>
    {
        private readonly string _value;

        private FlyMachineServiceAutostop(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyMachineServiceAutostop Off { get; } = new FlyMachineServiceAutostop("off");
        public static FlyMachineServiceAutostop Stop { get; } = new FlyMachineServiceAutostop("stop");
        public static FlyMachineServiceAutostop Suspend { get; } = new FlyMachineServiceAutostop("suspend");

        public static bool operator ==(FlyMachineServiceAutostop left, FlyMachineServiceAutostop right) => left.Equals(right);
        public static bool operator !=(FlyMachineServiceAutostop left, FlyMachineServiceAutostop right) => !left.Equals(right);

        public static explicit operator string(FlyMachineServiceAutostop value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyMachineServiceAutostop other && Equals(other);
        public bool Equals(FlyMachineServiceAutostop other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// Currently either "cookie" or "header"
    /// </summary>
    [EnumType]
    public readonly struct FlyReplayCacheType : IEquatable<FlyReplayCacheType>
    {
        private readonly string _value;

        private FlyReplayCacheType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyReplayCacheType Cookie { get; } = new FlyReplayCacheType("cookie");
        public static FlyReplayCacheType Header { get; } = new FlyReplayCacheType("header");

        public static bool operator ==(FlyReplayCacheType left, FlyReplayCacheType right) => left.Equals(right);
        public static bool operator !=(FlyReplayCacheType left, FlyReplayCacheType right) => !left.Equals(right);

        public static explicit operator string(FlyReplayCacheType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyReplayCacheType other && Equals(other);
        public bool Equals(FlyReplayCacheType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct FlyStopConfigSignal : IEquatable<FlyStopConfigSignal>
    {
        private readonly string _value;

        private FlyStopConfigSignal(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static FlyStopConfigSignal Sighup { get; } = new FlyStopConfigSignal("SIGHUP");
        public static FlyStopConfigSignal Sigint { get; } = new FlyStopConfigSignal("SIGINT");
        public static FlyStopConfigSignal Sigquit { get; } = new FlyStopConfigSignal("SIGQUIT");
        public static FlyStopConfigSignal Sigkill { get; } = new FlyStopConfigSignal("SIGKILL");
        public static FlyStopConfigSignal Sigusr1 { get; } = new FlyStopConfigSignal("SIGUSR1");
        public static FlyStopConfigSignal Sigusr2 { get; } = new FlyStopConfigSignal("SIGUSR2");
        public static FlyStopConfigSignal Sigterm { get; } = new FlyStopConfigSignal("SIGTERM");

        public static bool operator ==(FlyStopConfigSignal left, FlyStopConfigSignal right) => left.Equals(right);
        public static bool operator !=(FlyStopConfigSignal left, FlyStopConfigSignal right) => !left.Equals(right);

        public static explicit operator string(FlyStopConfigSignal value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is FlyStopConfigSignal other && Equals(other);
        public bool Equals(FlyStopConfigSignal other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct HostStatus : IEquatable<HostStatus>
    {
        private readonly string _value;

        private HostStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static HostStatus Ok { get; } = new HostStatus("ok");
        public static HostStatus Unknown { get; } = new HostStatus("unknown");
        public static HostStatus Unreachable { get; } = new HostStatus("unreachable");

        public static bool operator ==(HostStatus left, HostStatus right) => left.Equals(right);
        public static bool operator !=(HostStatus left, HostStatus right) => !left.Equals(right);

        public static explicit operator string(HostStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is HostStatus other && Equals(other);
        public bool Equals(HostStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct IssuedCertificateType : IEquatable<IssuedCertificateType>
    {
        private readonly string _value;

        private IssuedCertificateType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static IssuedCertificateType Rsa { get; } = new IssuedCertificateType("rsa");
        public static IssuedCertificateType Ecdsa { get; } = new IssuedCertificateType("ecdsa");

        public static bool operator ==(IssuedCertificateType left, IssuedCertificateType right) => left.Equals(right);
        public static bool operator !=(IssuedCertificateType left, IssuedCertificateType right) => !left.Equals(right);

        public static explicit operator string(IssuedCertificateType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is IssuedCertificateType other && Equals(other);
        public bool Equals(IssuedCertificateType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct MachineHostStatus : IEquatable<MachineHostStatus>
    {
        private readonly string _value;

        private MachineHostStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static MachineHostStatus Ok { get; } = new MachineHostStatus("ok");
        public static MachineHostStatus Unknown { get; } = new MachineHostStatus("unknown");
        public static MachineHostStatus Unreachable { get; } = new MachineHostStatus("unreachable");

        public static bool operator ==(MachineHostStatus left, MachineHostStatus right) => left.Equals(right);
        public static bool operator !=(MachineHostStatus left, MachineHostStatus right) => !left.Equals(right);

        public static explicit operator string(MachineHostStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is MachineHostStatus other && Equals(other);
        public bool Equals(MachineHostStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct MachinesSignalSignal : IEquatable<MachinesSignalSignal>
    {
        private readonly string _value;

        private MachinesSignalSignal(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static MachinesSignalSignal Sigabrt { get; } = new MachinesSignalSignal("SIGABRT");
        public static MachinesSignalSignal Sigalrm { get; } = new MachinesSignalSignal("SIGALRM");
        public static MachinesSignalSignal Sigfpe { get; } = new MachinesSignalSignal("SIGFPE");
        public static MachinesSignalSignal Sighup { get; } = new MachinesSignalSignal("SIGHUP");
        public static MachinesSignalSignal Sigill { get; } = new MachinesSignalSignal("SIGILL");
        public static MachinesSignalSignal Sigint { get; } = new MachinesSignalSignal("SIGINT");
        public static MachinesSignalSignal Sigkill { get; } = new MachinesSignalSignal("SIGKILL");
        public static MachinesSignalSignal Sigpipe { get; } = new MachinesSignalSignal("SIGPIPE");
        public static MachinesSignalSignal Sigquit { get; } = new MachinesSignalSignal("SIGQUIT");
        public static MachinesSignalSignal Sigsegv { get; } = new MachinesSignalSignal("SIGSEGV");
        public static MachinesSignalSignal Sigterm { get; } = new MachinesSignalSignal("SIGTERM");
        public static MachinesSignalSignal Sigtrap { get; } = new MachinesSignalSignal("SIGTRAP");
        public static MachinesSignalSignal Sigusr1 { get; } = new MachinesSignalSignal("SIGUSR1");
        public static MachinesSignalSignal Sigusr2 { get; } = new MachinesSignalSignal("SIGUSR2");

        public static bool operator ==(MachinesSignalSignal left, MachinesSignalSignal right) => left.Equals(right);
        public static bool operator !=(MachinesSignalSignal left, MachinesSignalSignal right) => !left.Equals(right);

        public static explicit operator string(MachinesSignalSignal value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is MachinesSignalSignal other && Equals(other);
        public bool Equals(MachinesSignalSignal other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct Signal : IEquatable<Signal>
    {
        private readonly string _value;

        private Signal(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static Signal Sighup { get; } = new Signal("SIGHUP");
        public static Signal Sigint { get; } = new Signal("SIGINT");
        public static Signal Sigquit { get; } = new Signal("SIGQUIT");
        public static Signal Sigkill { get; } = new Signal("SIGKILL");
        public static Signal Sigusr1 { get; } = new Signal("SIGUSR1");
        public static Signal Sigusr2 { get; } = new Signal("SIGUSR2");
        public static Signal Sigterm { get; } = new Signal("SIGTERM");

        public static bool operator ==(Signal left, Signal right) => left.Equals(right);
        public static bool operator !=(Signal left, Signal right) => !left.Equals(right);

        public static explicit operator string(Signal value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is Signal other && Equals(other);
        public bool Equals(Signal other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct Type : IEquatable<Type>
    {
        private readonly string _value;

        private Type(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static Type Local { get; } = new Type("local");
        public static Type Cache { get; } = new Type("cache");

        public static bool operator ==(Type left, Type right) => left.Equals(right);
        public static bool operator !=(Type left, Type right) => !left.Equals(right);

        public static explicit operator string(Type value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is Type other && Equals(other);
        public bool Equals(Type other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct VolumeHostStatus : IEquatable<VolumeHostStatus>
    {
        private readonly string _value;

        private VolumeHostStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static VolumeHostStatus Ok { get; } = new VolumeHostStatus("ok");
        public static VolumeHostStatus Unknown { get; } = new VolumeHostStatus("unknown");
        public static VolumeHostStatus Unreachable { get; } = new VolumeHostStatus("unreachable");

        public static bool operator ==(VolumeHostStatus left, VolumeHostStatus right) => left.Equals(right);
        public static bool operator !=(VolumeHostStatus left, VolumeHostStatus right) => !left.Equals(right);

        public static explicit operator string(VolumeHostStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is VolumeHostStatus other && Equals(other);
        public bool Equals(VolumeHostStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct VolumeType : IEquatable<VolumeType>
    {
        private readonly string _value;

        private VolumeType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static VolumeType Local { get; } = new VolumeType("local");
        public static VolumeType Cache { get; } = new VolumeType("cache");

        public static bool operator ==(VolumeType left, VolumeType right) => left.Equals(right);
        public static bool operator !=(VolumeType left, VolumeType right) => !left.Equals(right);

        public static explicit operator string(VolumeType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is VolumeType other && Equals(other);
        public bool Equals(VolumeType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
