// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    public static class GetAppCertificate
    {
        public static Task<GetAppCertificateResult> InvokeAsync(GetAppCertificateArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAppCertificateResult>("fly-machines:apps/v1:getAppCertificate", args ?? new GetAppCertificateArgs(), options.WithDefaults());

        public static Output<GetAppCertificateResult> Invoke(GetAppCertificateInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppCertificateResult>("fly-machines:apps/v1:getAppCertificate", args ?? new GetAppCertificateInvokeArgs(), options.WithDefaults());

        public static Output<GetAppCertificateResult> Invoke(GetAppCertificateInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppCertificateResult>("fly-machines:apps/v1:getAppCertificate", args ?? new GetAppCertificateInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAppCertificateArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName", required: true)]
        public string AppName { get; set; } = null!;

        /// <summary>
        /// Certificate Hostname
        /// </summary>
        [Input("hostname", required: true)]
        public string Hostname { get; set; } = null!;

        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Inputs.GetAppCertificateQueryParams? QueryParams { get; set; }

        public GetAppCertificateArgs()
        {
        }
        public static new GetAppCertificateArgs Empty => new GetAppCertificateArgs();
    }

    public sealed class GetAppCertificateInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName", required: true)]
        public Input<string> AppName { get; set; } = null!;

        /// <summary>
        /// Certificate Hostname
        /// </summary>
        [Input("hostname", required: true)]
        public Input<string> Hostname { get; set; } = null!;

        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams")]
        public Input<Inputs.GetAppCertificateQueryParamsArgs>? QueryParams { get; set; }

        public GetAppCertificateInvokeArgs()
        {
        }
        public static new GetAppCertificateInvokeArgs Empty => new GetAppCertificateInvokeArgs();
    }


    [OutputType]
    public sealed class GetAppCertificateResult
    {
        public readonly bool? AcmeRequested;
        public readonly ImmutableArray<Outputs.CertificateEntry> Certificates;
        public readonly bool? Configured;
        public readonly string? DnsProvider;
        public readonly Outputs.DNSRequirements? DnsRequirements;
        public readonly string? Hostname;
        public readonly string? RateLimitedUntil;
        public readonly string? Status;
        public readonly Outputs.CertificateValidation? Validation;
        public readonly ImmutableArray<Outputs.CertificateValidationError> ValidationErrors;

        [OutputConstructor]
        private GetAppCertificateResult(
            bool? acmeRequested,

            ImmutableArray<Outputs.CertificateEntry> certificates,

            bool? configured,

            string? dnsProvider,

            Outputs.DNSRequirements? dnsRequirements,

            string? hostname,

            string? rateLimitedUntil,

            string? status,

            Outputs.CertificateValidation? validation,

            ImmutableArray<Outputs.CertificateValidationError> validationErrors)
        {
            AcmeRequested = acmeRequested;
            Certificates = certificates;
            Configured = configured;
            DnsProvider = dnsProvider;
            DnsRequirements = dnsRequirements;
            Hostname = hostname;
            RateLimitedUntil = rateLimitedUntil;
            Status = status;
            Validation = validation;
            ValidationErrors = validationErrors;
        }
    }
}
