// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    public static class ListApps
    {
        public static Task<ListAppsResult> InvokeAsync(ListAppsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ListAppsResult>("fly-machines:apps/v1:listApps", args ?? new ListAppsArgs(), options.WithDefaults());

        public static Output<ListAppsResult> Invoke(ListAppsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ListAppsResult>("fly-machines:apps/v1:listApps", args ?? new ListAppsInvokeArgs(), options.WithDefaults());

        public static Output<ListAppsResult> Invoke(ListAppsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<ListAppsResult>("fly-machines:apps/v1:listApps", args ?? new ListAppsInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListAppsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams", required: true)]
        public Inputs.ListAppsQueryParams QueryParams { get; set; } = null!;

        public ListAppsArgs()
        {
        }
        public static new ListAppsArgs Empty => new ListAppsArgs();
    }

    public sealed class ListAppsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Query params to send with the API request.
        /// </summary>
        [Input("queryParams", required: true)]
        public Input<Inputs.ListAppsQueryParamsArgs> QueryParams { get; set; } = null!;

        public ListAppsInvokeArgs()
        {
        }
        public static new ListAppsInvokeArgs Empty => new ListAppsInvokeArgs();
    }


    [OutputType]
    public sealed class ListAppsResult
    {
        public readonly ImmutableArray<Outputs.App> Apps;
        public readonly int? TotalApps;

        [OutputConstructor]
        private ListAppsResult(
            ImmutableArray<Outputs.App> apps,

            int? totalApps)
        {
            Apps = apps;
            TotalApps = totalApps;
        }
    }
}
