// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    public static class ListApps
    {
        public static Task<ListAppsResult> InvokeAsync(ListAppsArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ListAppsResult>("fly-machines:apps/v1:listApps", args ?? new ListAppsArgs(), options.WithDefaults());

        public static Output<ListAppsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ListAppsResult>("fly-machines:apps/v1:listApps", InvokeArgs.Empty, options.WithDefaults());

        public static Output<ListAppsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<ListAppsResult>("fly-machines:apps/v1:listApps", InvokeArgs.Empty, options.WithDefaults());
    }


    public sealed class ListAppsArgs : global::Pulumi.InvokeArgs
    {
        public ListAppsArgs()
        {
        }
        public static new ListAppsArgs Empty => new ListAppsArgs();
    }


    [OutputType]
    public sealed class ListAppsResult
    {
        public readonly ImmutableArray<Outputs.App> Apps;
        public readonly int? TotalApps;

        [OutputConstructor]
        private ListAppsResult(
            ImmutableArray<Outputs.App> apps,

            int? totalApps)
        {
            Apps = apps;
            TotalApps = totalApps;
        }
    }
}
