// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    public static class ListSecretkeys
    {
        public static Task<ListSecretkeysResult> InvokeAsync(ListSecretkeysArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<ListSecretkeysResult>("fly-machines:apps/v1:listSecretkeys", args ?? new ListSecretkeysArgs(), options.WithDefaults());

        public static Output<ListSecretkeysResult> Invoke(ListSecretkeysInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<ListSecretkeysResult>("fly-machines:apps/v1:listSecretkeys", args ?? new ListSecretkeysInvokeArgs(), options.WithDefaults());

        public static Output<ListSecretkeysResult> Invoke(ListSecretkeysInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<ListSecretkeysResult>("fly-machines:apps/v1:listSecretkeys", args ?? new ListSecretkeysInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListSecretkeysArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName", required: true)]
        public string AppName { get; set; } = null!;

        public ListSecretkeysArgs()
        {
        }
        public static new ListSecretkeysArgs Empty => new ListSecretkeysArgs();
    }

    public sealed class ListSecretkeysInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName", required: true)]
        public Input<string> AppName { get; set; } = null!;

        public ListSecretkeysInvokeArgs()
        {
        }
        public static new ListSecretkeysInvokeArgs Empty => new ListSecretkeysInvokeArgs();
    }


    [OutputType]
    public sealed class ListSecretkeysResult
    {
        public readonly ImmutableArray<Outputs.SecretKey> SecretKeysValue;

        [OutputConstructor]
        private ListSecretkeysResult(ImmutableArray<Outputs.SecretKey> secretKeys)
        {
            SecretKeysValue = secretKeys;
        }
    }
}
