// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:MachinesReclaimMemory")]
    public partial class MachinesReclaimMemory : global::Pulumi.CustomResource
    {
        [Output("actualMb")]
        public Output<int?> ActualMb { get; private set; } = null!;

        [Output("amountMb")]
        public Output<int?> AmountMb { get; private set; } = null!;

        /// <summary>
        /// Query params to send with the API requests for this resource.
        /// </summary>
        [Output("queryParams")]
        public Output<Outputs.MachinesReclaimMemoryQueryParams?> QueryParams { get; private set; } = null!;


        /// <summary>
        /// Create a MachinesReclaimMemory resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MachinesReclaimMemory(string name, MachinesReclaimMemoryArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:MachinesReclaimMemory", name, args ?? new MachinesReclaimMemoryArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MachinesReclaimMemory(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:MachinesReclaimMemory", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MachinesReclaimMemory resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MachinesReclaimMemory Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new MachinesReclaimMemory(name, id, options);
        }
    }

    public sealed class MachinesReclaimMemoryArgs : global::Pulumi.ResourceArgs
    {
        [Input("amountMb")]
        public Input<int>? AmountMb { get; set; }

        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        /// <summary>
        /// Machine ID
        /// </summary>
        [Input("machineId")]
        public Input<string>? MachineId { get; set; }

        /// <summary>
        /// Query params to send with the API requests for this resource.
        /// </summary>
        [Input("queryParams")]
        public Input<Inputs.MachinesReclaimMemoryQueryParamsArgs>? QueryParams { get; set; }

        public MachinesReclaimMemoryArgs()
        {
        }
        public static new MachinesReclaimMemoryArgs Empty => new MachinesReclaimMemoryArgs();
    }
}
