// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:MachinesStop")]
    public partial class MachinesStop : global::Pulumi.CustomResource
    {
        [Output("signal")]
        public Output<Pulumi.FlyMachines.AppsV1.Signal?> Signal { get; private set; } = null!;

        [Output("timeout")]
        public Output<string?> Timeout { get; private set; } = null!;


        /// <summary>
        /// Create a MachinesStop resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MachinesStop(string name, MachinesStopArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:MachinesStop", name, args ?? new MachinesStopArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MachinesStop(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:MachinesStop", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MachinesStop resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MachinesStop Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new MachinesStop(name, id, options);
        }
    }

    public sealed class MachinesStopArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        /// <summary>
        /// Machine ID
        /// </summary>
        [Input("machineId")]
        public Input<string>? MachineId { get; set; }

        [Input("signal")]
        public Input<Pulumi.FlyMachines.AppsV1.Signal>? Signal { get; set; }

        [Input("timeout")]
        public Input<string>? Timeout { get; set; }

        public MachinesStopArgs()
        {
        }
        public static new MachinesStopArgs Empty => new MachinesStopArgs();
    }
}
