// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:Machine")]
    public partial class Machine : global::Pulumi.CustomResource
    {
        [Output("checks")]
        public Output<ImmutableArray<Outputs.CheckStatus>> Checks { get; private set; } = null!;

        [Output("config")]
        public Output<Outputs.FlyMachineConfig?> Config { get; private set; } = null!;

        [Output("cordoned")]
        public Output<bool?> Cordoned { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string?> CreatedAt { get; private set; } = null!;

        [Output("events")]
        public Output<ImmutableArray<Outputs.MachineEvent>> Events { get; private set; } = null!;

        [Output("hostFeatures")]
        public Output<ImmutableArray<string>> HostFeatures { get; private set; } = null!;

        [Output("hostStatus")]
        public Output<Pulumi.FlyMachines.AppsV1.HostStatus?> HostStatus { get; private set; } = null!;

        [Output("imageRef")]
        public Output<Outputs.ImageRef?> ImageRef { get; private set; } = null!;

        [Output("incompleteConfig")]
        public Output<Outputs.FlyMachineConfig?> IncompleteConfig { get; private set; } = null!;

        /// <summary>
        /// InstanceID is the same value as `version`.
        /// 
        /// Deprecated: use `version`.
        /// </summary>
        [Output("instanceId")]
        public Output<string?> InstanceId { get; private set; } = null!;

        [Output("lease")]
        public Output<Outputs.StrippedLease?> Lease { get; private set; } = null!;

        [Output("leaseTtl")]
        public Output<int?> LeaseTtl { get; private set; } = null!;

        [Output("minSecretsVersion")]
        public Output<int?> MinSecretsVersion { get; private set; } = null!;

        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// Nonce is only every returned on machine creation if a lease_duration was provided.
        /// </summary>
        [Output("nonce")]
        public Output<string?> Nonce { get; private set; } = null!;

        /// <summary>
        /// PrivateIP is the internal 6PN address of the machine.
        /// </summary>
        [Output("privateIp")]
        public Output<string?> PrivateIp { get; private set; } = null!;

        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("skipLaunch")]
        public Output<bool?> SkipLaunch { get; private set; } = null!;

        [Output("skipSecrets")]
        public Output<bool?> SkipSecrets { get; private set; } = null!;

        [Output("skipServiceRegistration")]
        public Output<bool?> SkipServiceRegistration { get; private set; } = null!;

        [Output("state")]
        public Output<string?> State { get; private set; } = null!;

        [Output("updatedAt")]
        public Output<string?> UpdatedAt { get; private set; } = null!;

        /// <summary>
        /// Version is unique for each version of the machine. Pass it as
        /// `current_version` when updating the Machine to reject the update if the
        /// Machine has changed since this version.
        /// </summary>
        [Output("version")]
        public Output<string?> Version { get; private set; } = null!;


        /// <summary>
        /// Create a Machine resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Machine(string name, MachineArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:Machine", name, args ?? new MachineArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Machine(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:Machine", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Machine resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Machine Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Machine(name, id, options);
        }
    }

    public sealed class MachineArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        /// <summary>
        /// An object defining the Machine configuration
        /// </summary>
        [Input("config")]
        public Input<Inputs.ConfigArgs>? Config { get; set; }

        [Input("leaseTtl")]
        public Input<int>? LeaseTtl { get; set; }

        [Input("minSecretsVersion")]
        public Input<int>? MinSecretsVersion { get; set; }

        /// <summary>
        /// Unique name for this Machine. If omitted, one is generated for you
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The target region. Omitting this param launches in the same region as your WireGuard peer connection (somewhere near you).
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("skipLaunch")]
        public Input<bool>? SkipLaunch { get; set; }

        [Input("skipSecrets")]
        public Input<bool>? SkipSecrets { get; set; }

        [Input("skipServiceRegistration")]
        public Input<bool>? SkipServiceRegistration { get; set; }

        public MachineArgs()
        {
        }
        public static new MachineArgs Empty => new MachineArgs();
    }
}
