// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:MachinesLease")]
    public partial class MachinesLease : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Description or reason for the Lease.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// ExpiresAt is the unix timestamp in UTC to denote when the Lease will no longer be valid.
        /// </summary>
        [Output("expiresAt")]
        public Output<int?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// Nonce is the unique ID autogenerated and associated with the Lease.
        /// </summary>
        [Output("nonce")]
        public Output<string?> Nonce { get; private set; } = null!;

        /// <summary>
        /// Owner is the user identifier which acquired the Lease.
        /// </summary>
        [Output("owner")]
        public Output<string?> Owner { get; private set; } = null!;

        /// <summary>
        /// seconds lease will be valid
        /// </summary>
        [Output("ttl")]
        public Output<int?> Ttl { get; private set; } = null!;

        /// <summary>
        /// Machine version
        /// </summary>
        [Output("version")]
        public Output<string?> Version { get; private set; } = null!;


        /// <summary>
        /// Create a MachinesLease resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MachinesLease(string name, MachinesLeaseArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:MachinesLease", name, args ?? new MachinesLeaseArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MachinesLease(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:MachinesLease", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MachinesLease resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MachinesLease Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new MachinesLease(name, id, options);
        }
    }

    public sealed class MachinesLeaseArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Machine ID
        /// </summary>
        [Input("machineId")]
        public Input<string>? MachineId { get; set; }

        /// <summary>
        /// seconds lease will be valid
        /// </summary>
        [Input("ttl")]
        public Input<int>? Ttl { get; set; }

        public MachinesLeaseArgs()
        {
        }
        public static new MachinesLeaseArgs Empty => new MachinesLeaseArgs();
    }
}
