// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:SecretkeyDecrypt")]
    public partial class SecretkeyDecrypt : global::Pulumi.CustomResource
    {
        [Output("associatedData")]
        public Output<ImmutableArray<int>> AssociatedData { get; private set; } = null!;

        [Output("ciphertext")]
        public Output<ImmutableArray<int>> Ciphertext { get; private set; } = null!;

        [Output("plaintext")]
        public Output<ImmutableArray<int>> Plaintext { get; private set; } = null!;


        /// <summary>
        /// Create a SecretkeyDecrypt resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecretkeyDecrypt(string name, SecretkeyDecryptArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:SecretkeyDecrypt", name, args ?? new SecretkeyDecryptArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecretkeyDecrypt(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:SecretkeyDecrypt", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecretkeyDecrypt resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecretkeyDecrypt Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new SecretkeyDecrypt(name, id, options);
        }
    }

    public sealed class SecretkeyDecryptArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        [Input("associatedData")]
        private InputList<int>? _associatedData;
        public InputList<int> AssociatedData
        {
            get => _associatedData ?? (_associatedData = new InputList<int>());
            set => _associatedData = value;
        }

        [Input("ciphertext")]
        private InputList<int>? _ciphertext;
        public InputList<int> Ciphertext
        {
            get => _ciphertext ?? (_ciphertext = new InputList<int>());
            set => _ciphertext = value;
        }

        /// <summary>
        /// Secret key name
        /// </summary>
        [Input("secretName")]
        public Input<string>? SecretName { get; set; }

        public SecretkeyDecryptArgs()
        {
        }
        public static new SecretkeyDecryptArgs Empty => new SecretkeyDecryptArgs();
    }
}
