// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.AppsV1
{
    [FlyMachinesResourceType("fly-machines:apps/v1:Volume")]
    public partial class Volume : global::Pulumi.CustomResource
    {
        [Output("attachedAllocId")]
        public Output<string?> AttachedAllocId { get; private set; } = null!;

        [Output("attachedMachineId")]
        public Output<string?> AttachedMachineId { get; private set; } = null!;

        [Output("autoBackupEnabled")]
        public Output<bool?> AutoBackupEnabled { get; private set; } = null!;

        [Output("blockSize")]
        public Output<int?> BlockSize { get; private set; } = null!;

        [Output("blocks")]
        public Output<int?> Blocks { get; private set; } = null!;

        [Output("blocksAvail")]
        public Output<int?> BlocksAvail { get; private set; } = null!;

        [Output("blocksFree")]
        public Output<int?> BlocksFree { get; private set; } = null!;

        [Output("bytesTotal")]
        public Output<int?> BytesTotal { get; private set; } = null!;

        [Output("bytesUsed")]
        public Output<int?> BytesUsed { get; private set; } = null!;

        [Output("compute")]
        public Output<Outputs.FlyMachineGuest?> Compute { get; private set; } = null!;

        [Output("computeImage")]
        public Output<string?> ComputeImage { get; private set; } = null!;

        [Output("createdAt")]
        public Output<string?> CreatedAt { get; private set; } = null!;

        [Output("encrypted")]
        public Output<bool?> Encrypted { get; private set; } = null!;

        [Output("fstype")]
        public Output<string?> Fstype { get; private set; } = null!;

        [Output("hostFeatures")]
        public Output<ImmutableArray<string>> HostFeatures { get; private set; } = null!;

        [Output("hostStatus")]
        public Output<Pulumi.FlyMachines.AppsV1.HostStatus?> HostStatus { get; private set; } = null!;

        [Output("name")]
        public Output<string?> Name { get; private set; } = null!;

        /// <summary>
        /// Query params to send with the API requests for this resource.
        /// </summary>
        [Output("queryParams")]
        public Output<Outputs.VolumeQueryParams?> QueryParams { get; private set; } = null!;

        [Output("region")]
        public Output<string?> Region { get; private set; } = null!;

        [Output("requireUniqueZone")]
        public Output<bool?> RequireUniqueZone { get; private set; } = null!;

        [Output("requiredHostFeatures")]
        public Output<ImmutableArray<string>> RequiredHostFeatures { get; private set; } = null!;

        [Output("sizeGb")]
        public Output<int?> SizeGb { get; private set; } = null!;

        /// <summary>
        /// restore from snapshot
        /// </summary>
        [Output("snapshotId")]
        public Output<string?> SnapshotId { get; private set; } = null!;

        [Output("snapshotRetention")]
        public Output<int?> SnapshotRetention { get; private set; } = null!;

        /// <summary>
        /// fork from remote volume
        /// </summary>
        [Output("sourceVolumeId")]
        public Output<string?> SourceVolumeId { get; private set; } = null!;

        [Output("state")]
        public Output<string?> State { get; private set; } = null!;

        [Output("type")]
        public Output<Pulumi.FlyMachines.AppsV1.Type?> Type { get; private set; } = null!;

        [Output("uniqueZoneAppWide")]
        public Output<bool?> UniqueZoneAppWide { get; private set; } = null!;

        [Output("zone")]
        public Output<string?> Zone { get; private set; } = null!;


        /// <summary>
        /// Create a Volume resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Volume(string name, VolumeArgs? args = null, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:Volume", name, args ?? new VolumeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Volume(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("fly-machines:apps/v1:Volume", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-fly-machines",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Volume resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Volume Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Volume(name, id, options);
        }
    }

    public sealed class VolumeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Fly App Name
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        /// <summary>
        /// enable scheduled automatic snapshots. Defaults to `true`
        /// </summary>
        [Input("autoBackupEnabled")]
        public Input<bool>? AutoBackupEnabled { get; set; }

        [Input("compute")]
        public Input<Inputs.FlyMachineGuestArgs>? Compute { get; set; }

        [Input("computeImage")]
        public Input<string>? ComputeImage { get; set; }

        [Input("encrypted")]
        public Input<bool>? Encrypted { get; set; }

        [Input("fstype")]
        public Input<string>? Fstype { get; set; }

        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Query params to send with the API requests for this resource.
        /// </summary>
        [Input("queryParams")]
        public Input<Inputs.VolumeQueryParamsArgs>? QueryParams { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("requireUniqueZone")]
        public Input<bool>? RequireUniqueZone { get; set; }

        [Input("sizeGb")]
        public Input<int>? SizeGb { get; set; }

        /// <summary>
        /// restore from snapshot
        /// </summary>
        [Input("snapshotId")]
        public Input<string>? SnapshotId { get; set; }

        [Input("snapshotRetention")]
        public Input<int>? SnapshotRetention { get; set; }

        /// <summary>
        /// fork from remote volume
        /// </summary>
        [Input("sourceVolumeId")]
        public Input<string>? SourceVolumeId { get; set; }

        [Input("uniqueZoneAppWide")]
        public Input<bool>? UniqueZoneAppWide { get; set; }

        public VolumeArgs()
        {
        }
        public static new VolumeArgs Empty => new VolumeArgs();
    }
}
