// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.TokensV1.Inputs
{

    /// <summary>
    /// Action is the action being taken on the specified resource. This is the
    /// combination of individual action characters (e.g "rw")
    ///   - r: read
    ///   - w: write
    ///   - c: create
    ///   - d: delete
    ///   - C: control
    /// </summary>
    public sealed class MainTokenAccessActionArgs : global::Pulumi.ResourceArgs
    {
        public MainTokenAccessActionArgs()
        {
        }
        public static new MainTokenAccessActionArgs Empty => new MainTokenAccessActionArgs();
    }
}
