// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.TokensV1.Inputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    public sealed class TokensRequestKmQueryParamsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        [Input("create")]
        public Input<Inputs.TokensRequestKmCreateQueryParamsArgs>? Create { get; set; }

        public TokensRequestKmQueryParamsArgs()
        {
        }
        public static new TokensRequestKmQueryParamsArgs Empty => new TokensRequestKmQueryParamsArgs();
    }
}
