# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'AppIPAssignmentType',
    'CertificateEntrySource',
    'CertificateEntryStatus',
    'FlyEnvFromFieldRef',
    'FlyMachineGuestPersistRootfs',
    'FlyMachineRestartPolicy',
    'FlyMachineRootfsPersist',
    'FlyMachineServiceAutostop',
    'FlyReplayCacheType',
    'FlyStopConfigSignal',
    'GetMachinesWaitQueryParamsState',
    'HostStatus',
    'IssuedCertificateType',
    'MachineHostStatus',
    'MachinesRestartCreateQueryParamsSignal',
    'MachinesSignalSignal',
    'Signal',
    'Type',
    'VolumeHostStatus',
    'VolumeType',
]


@pulumi.type_token("fly-machines:apps/v1:AppIPAssignmentType")
class AppIPAssignmentType(_builtins.str, Enum):
    """
    Type of IP address to allocate. "egress-pair" allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).
    """
    V4 = "v4"
    V6 = "v6"
    SHARED_V4 = "shared_v4"
    PRIVATE_V6 = "private_v6"
    EGRESS_V4 = "egress_v4"
    EGRESS_V6 = "egress_v6"
    EGRESS_PAIR = "egress_pair"


@pulumi.type_token("fly-machines:apps/v1:CertificateEntrySource")
class CertificateEntrySource(_builtins.str, Enum):
    CUSTOM = "custom"
    FLY = "fly"


@pulumi.type_token("fly-machines:apps/v1:CertificateEntryStatus")
class CertificateEntryStatus(_builtins.str, Enum):
    ACTIVE = "active"
    PENDING_OWNERSHIP = "pending_ownership"
    PENDING_VALIDATION = "pending_validation"


@pulumi.type_token("fly-machines:apps/v1:FlyEnvFromFieldRef")
class FlyEnvFromFieldRef(_builtins.str, Enum):
    """
    FieldRef selects a field of the Machine: supports id, version, app_name, private_ip, region, image.
    """
    ID = "id"
    VERSION = "version"
    APP_NAME = "app_name"
    PRIVATE_IP = "private_ip"
    REGION = "region"
    IMAGE = "image"


@pulumi.type_token("fly-machines:apps/v1:FlyMachineGuestPersistRootfs")
class FlyMachineGuestPersistRootfs(_builtins.str, Enum):
    """
    Deprecated: use MachineConfig.Rootfs instead
    """
    NEVER = "never"
    ALWAYS = "always"
    RESTART = "restart"


@pulumi.type_token("fly-machines:apps/v1:FlyMachineRestartPolicy")
class FlyMachineRestartPolicy(_builtins.str, Enum):
    """
    * no - Never try to restart a Machine automatically when its main process exits, whether that’s on purpose or on a crash.
    * always - Always restart a Machine automatically and never let it enter a stopped state, even when the main process exits cleanly.
    * on-failure - Try up to MaxRetries times to automatically restart the Machine if it exits with a non-zero exit code. Default when no explicit policy is set, and for Machines with schedules.
    """
    NO = "no"
    ALWAYS = "always"
    ON_FAILURE = "on-failure"


@pulumi.type_token("fly-machines:apps/v1:FlyMachineRootfsPersist")
class FlyMachineRootfsPersist(_builtins.str, Enum):
    NEVER = "never"
    ALWAYS = "always"
    RESTART = "restart"


@pulumi.type_token("fly-machines:apps/v1:FlyMachineServiceAutostop")
class FlyMachineServiceAutostop(_builtins.str, Enum):
    """
    Accepts a string (new format) or a boolean (old format). For backward compatibility with older clients, the API continues to use booleans for "off" and "stop" in responses.
    * "off" or false - Do not autostop the Machine.
    * "stop" or true - Automatically stop the Machine.
    * "suspend" - Automatically suspend the Machine, falling back to a full stop if this is not possible.
    """
    OFF = "off"
    STOP = "stop"
    SUSPEND = "suspend"


@pulumi.type_token("fly-machines:apps/v1:FlyReplayCacheType")
class FlyReplayCacheType(_builtins.str, Enum):
    """
    Currently either "cookie" or "header"
    """
    COOKIE = "cookie"
    HEADER = "header"


@pulumi.type_token("fly-machines:apps/v1:FlyStopConfigSignal")
class FlyStopConfigSignal(_builtins.str, Enum):
    SIGHUP = "SIGHUP"
    SIGINT = "SIGINT"
    SIGQUIT = "SIGQUIT"
    SIGKILL = "SIGKILL"
    SIGUSR1 = "SIGUSR1"
    SIGUSR2 = "SIGUSR2"
    SIGTERM = "SIGTERM"


@pulumi.type_token("fly-machines:apps/v1:GetMachinesWaitQueryParamsState")
class GetMachinesWaitQueryParamsState(_builtins.str, Enum):
    STARTED = "started"
    STOPPED = "stopped"
    SUSPENDED = "suspended"
    DESTROYED = "destroyed"
    FAILED = "failed"
    SETTLED = "settled"


@pulumi.type_token("fly-machines:apps/v1:HostStatus")
class HostStatus(_builtins.str, Enum):
    OK = "ok"
    UNKNOWN = "unknown"
    UNREACHABLE = "unreachable"


@pulumi.type_token("fly-machines:apps/v1:IssuedCertificateType")
class IssuedCertificateType(_builtins.str, Enum):
    RSA = "rsa"
    ECDSA = "ecdsa"


@pulumi.type_token("fly-machines:apps/v1:MachineHostStatus")
class MachineHostStatus(_builtins.str, Enum):
    OK = "ok"
    UNKNOWN = "unknown"
    UNREACHABLE = "unreachable"


@pulumi.type_token("fly-machines:apps/v1:MachinesRestartCreateQueryParamsSignal")
class MachinesRestartCreateQueryParamsSignal(_builtins.str, Enum):
    SIGHUP = "SIGHUP"
    SIGINT = "SIGINT"
    SIGQUIT = "SIGQUIT"
    SIGKILL = "SIGKILL"
    SIGUSR1 = "SIGUSR1"
    SIGUSR2 = "SIGUSR2"
    SIGTERM = "SIGTERM"


@pulumi.type_token("fly-machines:apps/v1:MachinesSignalSignal")
class MachinesSignalSignal(_builtins.str, Enum):
    SIGABRT = "SIGABRT"
    SIGALRM = "SIGALRM"
    SIGFPE = "SIGFPE"
    SIGHUP = "SIGHUP"
    SIGILL = "SIGILL"
    SIGINT = "SIGINT"
    SIGKILL = "SIGKILL"
    SIGPIPE = "SIGPIPE"
    SIGQUIT = "SIGQUIT"
    SIGSEGV = "SIGSEGV"
    SIGTERM = "SIGTERM"
    SIGTRAP = "SIGTRAP"
    SIGUSR1 = "SIGUSR1"
    SIGUSR2 = "SIGUSR2"


@pulumi.type_token("fly-machines:apps/v1:Signal")
class Signal(_builtins.str, Enum):
    SIGHUP = "SIGHUP"
    SIGINT = "SIGINT"
    SIGQUIT = "SIGQUIT"
    SIGKILL = "SIGKILL"
    SIGUSR1 = "SIGUSR1"
    SIGUSR2 = "SIGUSR2"
    SIGTERM = "SIGTERM"


@pulumi.type_token("fly-machines:apps/v1:Type")
class Type(_builtins.str, Enum):
    LOCAL = "local"
    CACHE = "cache"


@pulumi.type_token("fly-machines:apps/v1:VolumeHostStatus")
class VolumeHostStatus(_builtins.str, Enum):
    OK = "ok"
    UNKNOWN = "unknown"
    UNREACHABLE = "unreachable"


@pulumi.type_token("fly-machines:apps/v1:VolumeType")
class VolumeType(_builtins.str, Enum):
    LOCAL = "local"
    CACHE = "cache"
