# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *

__all__ = ['AppIPAssignmentArgs', 'AppIPAssignment']

@pulumi.input_type
class AppIPAssignmentArgs:
    def __init__(__self__, *,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional[_builtins.str]] = None,
                 org_slug: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 service_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional['AppIPAssignmentType']] = None):
        """
        The set of arguments for constructing a AppIPAssignment resource.

        :param pulumi.Input[_builtins.str] app_name: Fly App Name
        :param pulumi.Input['AppIPAssignmentType'] type: Type of IP address to allocate. "egress-pair" allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).
        """
        if app_name is not None:
            pulumi.set(__self__, "app_name", app_name)
        if network is not None:
            pulumi.set(__self__, "network", network)
        if org_slug is not None:
            pulumi.set(__self__, "org_slug", org_slug)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if service_name is not None:
            pulumi.set(__self__, "service_name", service_name)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Fly App Name
        """
        return pulumi.get(self, "app_name")

    @app_name.setter
    def app_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "app_name", value)

    @_builtins.property
    @pulumi.getter
    def network(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "network")

    @network.setter
    def network(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "network", value)

    @_builtins.property
    @pulumi.getter(name="orgSlug")
    def org_slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "org_slug")

    @org_slug.setter
    def org_slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_slug", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "service_name")

    @service_name.setter
    def service_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "service_name", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional['AppIPAssignmentType']]:
        """
        Type of IP address to allocate. "egress-pair" allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional['AppIPAssignmentType']]):
        pulumi.set(self, "type", value)


@pulumi.type_token("fly-machines:apps/v1:AppIPAssignment")
class AppIPAssignment(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional[_builtins.str]] = None,
                 org_slug: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 service_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional['AppIPAssignmentType']] = None,
                 __props__=None):
        """
        Create a AppIPAssignment resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] app_name: Fly App Name
        :param pulumi.Input['AppIPAssignmentType'] type: Type of IP address to allocate. "egress-pair" allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[AppIPAssignmentArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AppIPAssignment resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AppIPAssignmentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AppIPAssignmentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 network: pulumi.Input[Optional[_builtins.str]] = None,
                 org_slug: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 service_name: pulumi.Input[Optional[_builtins.str]] = None,
                 type: pulumi.Input[Optional['AppIPAssignmentType']] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AppIPAssignmentArgs.__new__(AppIPAssignmentArgs)

            __props__.__dict__["app_name"] = app_name
            __props__.__dict__["network"] = network
            __props__.__dict__["org_slug"] = org_slug
            __props__.__dict__["region"] = region
            __props__.__dict__["service_name"] = service_name
            __props__.__dict__["type"] = type
            __props__.__dict__["created_at"] = None
            __props__.__dict__["egress"] = None
            __props__.__dict__["ip"] = None
            __props__.__dict__["ip_pair"] = None
            __props__.__dict__["shared"] = None
        super(AppIPAssignment, __self__).__init__(
            'fly-machines:apps/v1:AppIPAssignment',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'AppIPAssignment':
        """
        Get an existing AppIPAssignment resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = AppIPAssignmentArgs.__new__(AppIPAssignmentArgs)

        __props__.__dict__["created_at"] = None
        __props__.__dict__["egress"] = None
        __props__.__dict__["ip"] = None
        __props__.__dict__["ip_pair"] = None
        __props__.__dict__["network"] = None
        __props__.__dict__["org_slug"] = None
        __props__.__dict__["region"] = None
        __props__.__dict__["service_name"] = None
        __props__.__dict__["shared"] = None
        __props__.__dict__["type"] = None
        return AppIPAssignment(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def egress(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "egress")

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter(name="ipPair")
    def ip_pair(self) -> pulumi.Output[Optional['outputs.IpPair']]:
        """
        ip_pair is returned when "egress-pair" IP type is requested; in this case, ip is null.
        """
        return pulumi.get(self, "ip_pair")

    @_builtins.property
    @pulumi.getter
    def network(self) -> pulumi.Output[Optional['outputs.IPAssignmentNetwork']]:
        """
        The 6PN network a Flycast (private_v6) address belongs to. Null for all other IP types.
        """
        return pulumi.get(self, "network")

    @_builtins.property
    @pulumi.getter(name="orgSlug")
    def org_slug(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "org_slug")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="serviceName")
    def service_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "service_name")

    @_builtins.property
    @pulumi.getter
    def shared(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "shared")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[Optional['AppIPAssignmentType']]:
        """
        Type of IP address to allocate. "egress-pair" allocates both v4 and v6 egress IP addresses (recommended when using egress IPs).
        """
        return pulumi.get(self, "type")

