# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = [
    'GetMachineResult',
    'AwaitableGetMachineResult',
    'get_machine',
    'get_machine_output',
]

@pulumi.output_type
class GetMachineResult:
    def __init__(__self__, checks=None, config=None, cordoned=None, created_at=None, events=None, host_features=None, host_status=None, id=None, image_ref=None, incomplete_config=None, instance_id=None, lease=None, name=None, nonce=None, private_ip=None, region=None, state=None, updated_at=None, version=None):
        if checks and not isinstance(checks, list):
            raise TypeError("Expected argument 'checks' to be a list")
        pulumi.set(__self__, "checks", checks)
        if config and not isinstance(config, dict):
            raise TypeError("Expected argument 'config' to be a dict")
        pulumi.set(__self__, "config", config)
        if cordoned and not isinstance(cordoned, bool):
            raise TypeError("Expected argument 'cordoned' to be a bool")
        pulumi.set(__self__, "cordoned", cordoned)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if events and not isinstance(events, list):
            raise TypeError("Expected argument 'events' to be a list")
        pulumi.set(__self__, "events", events)
        if host_features and not isinstance(host_features, list):
            raise TypeError("Expected argument 'host_features' to be a list")
        pulumi.set(__self__, "host_features", host_features)
        if host_status and not isinstance(host_status, str):
            raise TypeError("Expected argument 'host_status' to be a str")
        pulumi.set(__self__, "host_status", host_status)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if image_ref and not isinstance(image_ref, dict):
            raise TypeError("Expected argument 'image_ref' to be a dict")
        pulumi.set(__self__, "image_ref", image_ref)
        if incomplete_config and not isinstance(incomplete_config, dict):
            raise TypeError("Expected argument 'incomplete_config' to be a dict")
        pulumi.set(__self__, "incomplete_config", incomplete_config)
        if instance_id and not isinstance(instance_id, str):
            raise TypeError("Expected argument 'instance_id' to be a str")
        pulumi.set(__self__, "instance_id", instance_id)
        if lease and not isinstance(lease, dict):
            raise TypeError("Expected argument 'lease' to be a dict")
        pulumi.set(__self__, "lease", lease)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if nonce and not isinstance(nonce, str):
            raise TypeError("Expected argument 'nonce' to be a str")
        pulumi.set(__self__, "nonce", nonce)
        if private_ip and not isinstance(private_ip, str):
            raise TypeError("Expected argument 'private_ip' to be a str")
        pulumi.set(__self__, "private_ip", private_ip)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if state and not isinstance(state, str):
            raise TypeError("Expected argument 'state' to be a str")
        pulumi.set(__self__, "state", state)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if version and not isinstance(version, str):
            raise TypeError("Expected argument 'version' to be a str")
        pulumi.set(__self__, "version", version)

    @_builtins.property
    @pulumi.getter
    def checks(self) -> Optional[Sequence['outputs.CheckStatus']]:
        return pulumi.get(self, "checks")

    @_builtins.property
    @pulumi.getter
    def config(self) -> Optional['outputs.FlyMachineConfig']:
        return pulumi.get(self, "config")

    @_builtins.property
    @pulumi.getter
    def cordoned(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "cordoned")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def events(self) -> Optional[Sequence['outputs.MachineEvent']]:
        return pulumi.get(self, "events")

    @_builtins.property
    @pulumi.getter(name="hostFeatures")
    def host_features(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "host_features")

    @_builtins.property
    @pulumi.getter(name="hostStatus")
    def host_status(self) -> Optional['MachineHostStatus']:
        return pulumi.get(self, "host_status")

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="imageRef")
    def image_ref(self) -> Optional['outputs.ImageRef']:
        return pulumi.get(self, "image_ref")

    @_builtins.property
    @pulumi.getter(name="incompleteConfig")
    def incomplete_config(self) -> Optional['outputs.FlyMachineConfig']:
        return pulumi.get(self, "incomplete_config")

    @_builtins.property
    @pulumi.getter(name="instanceId")
    def instance_id(self) -> Optional[_builtins.str]:
        """
        InstanceID is the same value as `version`.

        Deprecated: use `version`.
        """
        return pulumi.get(self, "instance_id")

    @_builtins.property
    @pulumi.getter
    def lease(self) -> Optional['outputs.StrippedLease']:
        return pulumi.get(self, "lease")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def nonce(self) -> Optional[_builtins.str]:
        """
        Nonce is only every returned on machine creation if a lease_duration was provided.
        """
        return pulumi.get(self, "nonce")

    @_builtins.property
    @pulumi.getter(name="privateIp")
    def private_ip(self) -> Optional[_builtins.str]:
        """
        PrivateIP is the internal 6PN address of the machine.
        """
        return pulumi.get(self, "private_ip")

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter
    def state(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "state")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def version(self) -> Optional[_builtins.str]:
        """
        Version is unique for each version of the machine. Pass it as
        `current_version` when updating the Machine to reject the update if the
        Machine has changed since this version.
        """
        return pulumi.get(self, "version")


class AwaitableGetMachineResult(GetMachineResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMachineResult(
            checks=self.checks,
            config=self.config,
            cordoned=self.cordoned,
            created_at=self.created_at,
            events=self.events,
            host_features=self.host_features,
            host_status=self.host_status,
            id=self.id,
            image_ref=self.image_ref,
            incomplete_config=self.incomplete_config,
            instance_id=self.instance_id,
            lease=self.lease,
            name=self.name,
            nonce=self.nonce,
            private_ip=self.private_ip,
            region=self.region,
            state=self.state,
            updated_at=self.updated_at,
            version=self.version)


def get_machine(app_name: Optional[_builtins.str] = None,
                machine_id: Optional[_builtins.str] = None,
                query_params: Optional[Union['GetMachineQueryParams', 'GetMachineQueryParamsDict']] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMachineResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param _builtins.str machine_id: Machine ID
    :param Union['GetMachineQueryParams', 'GetMachineQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['machineId'] = machine_id
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:getMachine', __args__, opts=opts, typ=GetMachineResult).value

    return AwaitableGetMachineResult(
        checks=pulumi.get(__ret__, 'checks'),
        config=pulumi.get(__ret__, 'config'),
        cordoned=pulumi.get(__ret__, 'cordoned'),
        created_at=pulumi.get(__ret__, 'created_at'),
        events=pulumi.get(__ret__, 'events'),
        host_features=pulumi.get(__ret__, 'host_features'),
        host_status=pulumi.get(__ret__, 'host_status'),
        id=pulumi.get(__ret__, 'id'),
        image_ref=pulumi.get(__ret__, 'image_ref'),
        incomplete_config=pulumi.get(__ret__, 'incomplete_config'),
        instance_id=pulumi.get(__ret__, 'instance_id'),
        lease=pulumi.get(__ret__, 'lease'),
        name=pulumi.get(__ret__, 'name'),
        nonce=pulumi.get(__ret__, 'nonce'),
        private_ip=pulumi.get(__ret__, 'private_ip'),
        region=pulumi.get(__ret__, 'region'),
        state=pulumi.get(__ret__, 'state'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        version=pulumi.get(__ret__, 'version'))
def get_machine_output(app_name: pulumi.Input[Optional[_builtins.str]] = None,
                       machine_id: pulumi.Input[Optional[_builtins.str]] = None,
                       query_params: pulumi.Input[Optional[Optional[Union['GetMachineQueryParams', 'GetMachineQueryParamsDict']]]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMachineResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param _builtins.str machine_id: Machine ID
    :param Union['GetMachineQueryParams', 'GetMachineQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['machineId'] = machine_id
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:getMachine', __args__, opts=opts, typ=GetMachineResult)
    return __ret__.apply(lambda __response__: GetMachineResult(
        checks=pulumi.get(__response__, 'checks'),
        config=pulumi.get(__response__, 'config'),
        cordoned=pulumi.get(__response__, 'cordoned'),
        created_at=pulumi.get(__response__, 'created_at'),
        events=pulumi.get(__response__, 'events'),
        host_features=pulumi.get(__response__, 'host_features'),
        host_status=pulumi.get(__response__, 'host_status'),
        id=pulumi.get(__response__, 'id'),
        image_ref=pulumi.get(__response__, 'image_ref'),
        incomplete_config=pulumi.get(__response__, 'incomplete_config'),
        instance_id=pulumi.get(__response__, 'instance_id'),
        lease=pulumi.get(__response__, 'lease'),
        name=pulumi.get(__response__, 'name'),
        nonce=pulumi.get(__response__, 'nonce'),
        private_ip=pulumi.get(__response__, 'private_ip'),
        region=pulumi.get(__response__, 'region'),
        state=pulumi.get(__response__, 'state'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        version=pulumi.get(__response__, 'version')))
