# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = [
    'GetAppCertificateResult',
    'AwaitableGetAppCertificateResult',
    'get_app_certificate',
    'get_app_certificate_output',
]

@pulumi.output_type
class GetAppCertificateResult:
    def __init__(__self__, acme_requested=None, certificates=None, configured=None, dns_provider=None, dns_requirements=None, hostname=None, rate_limited_until=None, status=None, validation=None, validation_errors=None):
        if acme_requested and not isinstance(acme_requested, bool):
            raise TypeError("Expected argument 'acme_requested' to be a bool")
        pulumi.set(__self__, "acme_requested", acme_requested)
        if certificates and not isinstance(certificates, list):
            raise TypeError("Expected argument 'certificates' to be a list")
        pulumi.set(__self__, "certificates", certificates)
        if configured and not isinstance(configured, bool):
            raise TypeError("Expected argument 'configured' to be a bool")
        pulumi.set(__self__, "configured", configured)
        if dns_provider and not isinstance(dns_provider, str):
            raise TypeError("Expected argument 'dns_provider' to be a str")
        pulumi.set(__self__, "dns_provider", dns_provider)
        if dns_requirements and not isinstance(dns_requirements, dict):
            raise TypeError("Expected argument 'dns_requirements' to be a dict")
        pulumi.set(__self__, "dns_requirements", dns_requirements)
        if hostname and not isinstance(hostname, str):
            raise TypeError("Expected argument 'hostname' to be a str")
        pulumi.set(__self__, "hostname", hostname)
        if rate_limited_until and not isinstance(rate_limited_until, str):
            raise TypeError("Expected argument 'rate_limited_until' to be a str")
        pulumi.set(__self__, "rate_limited_until", rate_limited_until)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if validation and not isinstance(validation, dict):
            raise TypeError("Expected argument 'validation' to be a dict")
        pulumi.set(__self__, "validation", validation)
        if validation_errors and not isinstance(validation_errors, list):
            raise TypeError("Expected argument 'validation_errors' to be a list")
        pulumi.set(__self__, "validation_errors", validation_errors)

    @_builtins.property
    @pulumi.getter(name="acmeRequested")
    def acme_requested(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "acme_requested")

    @_builtins.property
    @pulumi.getter
    def certificates(self) -> Optional[Sequence['outputs.CertificateEntry']]:
        return pulumi.get(self, "certificates")

    @_builtins.property
    @pulumi.getter
    def configured(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "configured")

    @_builtins.property
    @pulumi.getter(name="dnsProvider")
    def dns_provider(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "dns_provider")

    @_builtins.property
    @pulumi.getter(name="dnsRequirements")
    def dns_requirements(self) -> Optional['outputs.DNSRequirements']:
        return pulumi.get(self, "dns_requirements")

    @_builtins.property
    @pulumi.getter
    def hostname(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "hostname")

    @_builtins.property
    @pulumi.getter(name="rateLimitedUntil")
    def rate_limited_until(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "rate_limited_until")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def validation(self) -> Optional['outputs.CertificateValidation']:
        return pulumi.get(self, "validation")

    @_builtins.property
    @pulumi.getter(name="validationErrors")
    def validation_errors(self) -> Optional[Sequence['outputs.CertificateValidationError']]:
        return pulumi.get(self, "validation_errors")


class AwaitableGetAppCertificateResult(GetAppCertificateResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAppCertificateResult(
            acme_requested=self.acme_requested,
            certificates=self.certificates,
            configured=self.configured,
            dns_provider=self.dns_provider,
            dns_requirements=self.dns_requirements,
            hostname=self.hostname,
            rate_limited_until=self.rate_limited_until,
            status=self.status,
            validation=self.validation,
            validation_errors=self.validation_errors)


def get_app_certificate(app_name: Optional[_builtins.str] = None,
                        hostname: Optional[_builtins.str] = None,
                        query_params: Optional[Union['GetAppCertificateQueryParams', 'GetAppCertificateQueryParamsDict']] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAppCertificateResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param _builtins.str hostname: Certificate Hostname
    :param Union['GetAppCertificateQueryParams', 'GetAppCertificateQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['hostname'] = hostname
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:getAppCertificate', __args__, opts=opts, typ=GetAppCertificateResult).value

    return AwaitableGetAppCertificateResult(
        acme_requested=pulumi.get(__ret__, 'acme_requested'),
        certificates=pulumi.get(__ret__, 'certificates'),
        configured=pulumi.get(__ret__, 'configured'),
        dns_provider=pulumi.get(__ret__, 'dns_provider'),
        dns_requirements=pulumi.get(__ret__, 'dns_requirements'),
        hostname=pulumi.get(__ret__, 'hostname'),
        rate_limited_until=pulumi.get(__ret__, 'rate_limited_until'),
        status=pulumi.get(__ret__, 'status'),
        validation=pulumi.get(__ret__, 'validation'),
        validation_errors=pulumi.get(__ret__, 'validation_errors'))
def get_app_certificate_output(app_name: pulumi.Input[Optional[_builtins.str]] = None,
                               hostname: pulumi.Input[Optional[_builtins.str]] = None,
                               query_params: pulumi.Input[Optional[Optional[Union['GetAppCertificateQueryParams', 'GetAppCertificateQueryParamsDict']]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAppCertificateResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param _builtins.str hostname: Certificate Hostname
    :param Union['GetAppCertificateQueryParams', 'GetAppCertificateQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['hostname'] = hostname
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:getAppCertificate', __args__, opts=opts, typ=GetAppCertificateResult)
    return __ret__.apply(lambda __response__: GetAppCertificateResult(
        acme_requested=pulumi.get(__response__, 'acme_requested'),
        certificates=pulumi.get(__response__, 'certificates'),
        configured=pulumi.get(__response__, 'configured'),
        dns_provider=pulumi.get(__response__, 'dns_provider'),
        dns_requirements=pulumi.get(__response__, 'dns_requirements'),
        hostname=pulumi.get(__response__, 'hostname'),
        rate_limited_until=pulumi.get(__response__, 'rate_limited_until'),
        status=pulumi.get(__response__, 'status'),
        validation=pulumi.get(__response__, 'validation'),
        validation_errors=pulumi.get(__response__, 'validation_errors')))
