# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetAppResult',
    'AwaitableGetAppResult',
    'get_app',
    'get_app_output',
]

@pulumi.output_type
class GetAppResult:
    def __init__(__self__, id=None, internal_numeric_id=None, machine_count=None, name=None, network=None, network_cidr=None, organization=None, status=None, volume_count=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if internal_numeric_id and not isinstance(internal_numeric_id, int):
            raise TypeError("Expected argument 'internal_numeric_id' to be a int")
        pulumi.set(__self__, "internal_numeric_id", internal_numeric_id)
        if machine_count and not isinstance(machine_count, int):
            raise TypeError("Expected argument 'machine_count' to be a int")
        pulumi.set(__self__, "machine_count", machine_count)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if network and not isinstance(network, str):
            raise TypeError("Expected argument 'network' to be a str")
        pulumi.set(__self__, "network", network)
        if network_cidr and not isinstance(network_cidr, str):
            raise TypeError("Expected argument 'network_cidr' to be a str")
        pulumi.set(__self__, "network_cidr", network_cidr)
        if organization and not isinstance(organization, dict):
            raise TypeError("Expected argument 'organization' to be a dict")
        pulumi.set(__self__, "organization", organization)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if volume_count and not isinstance(volume_count, int):
            raise TypeError("Expected argument 'volume_count' to be a int")
        pulumi.set(__self__, "volume_count", volume_count)

    @_builtins.property
    @pulumi.getter
    def id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="internalNumericId")
    def internal_numeric_id(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "internal_numeric_id")

    @_builtins.property
    @pulumi.getter(name="machineCount")
    def machine_count(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "machine_count")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def network(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "network")

    @_builtins.property
    @pulumi.getter(name="networkCidr")
    def network_cidr(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "network_cidr")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional['outputs.AppOrganizationInfo']:
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="volumeCount")
    def volume_count(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "volume_count")


class AwaitableGetAppResult(GetAppResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetAppResult(
            id=self.id,
            internal_numeric_id=self.internal_numeric_id,
            machine_count=self.machine_count,
            name=self.name,
            network=self.network,
            network_cidr=self.network_cidr,
            organization=self.organization,
            status=self.status,
            volume_count=self.volume_count)


def get_app(name: Optional[_builtins.str] = None,
            query_params: Optional[Union['GetAppQueryParams', 'GetAppQueryParamsDict']] = None,
            opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetAppResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str name: Fly App Name
    :param Union['GetAppQueryParams', 'GetAppQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:getApp', __args__, opts=opts, typ=GetAppResult).value

    return AwaitableGetAppResult(
        id=pulumi.get(__ret__, 'id'),
        internal_numeric_id=pulumi.get(__ret__, 'internal_numeric_id'),
        machine_count=pulumi.get(__ret__, 'machine_count'),
        name=pulumi.get(__ret__, 'name'),
        network=pulumi.get(__ret__, 'network'),
        network_cidr=pulumi.get(__ret__, 'network_cidr'),
        organization=pulumi.get(__ret__, 'organization'),
        status=pulumi.get(__ret__, 'status'),
        volume_count=pulumi.get(__ret__, 'volume_count'))
def get_app_output(name: pulumi.Input[Optional[_builtins.str]] = None,
                   query_params: pulumi.Input[Optional[Optional[Union['GetAppQueryParams', 'GetAppQueryParamsDict']]]] = None,
                   opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetAppResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str name: Fly App Name
    :param Union['GetAppQueryParams', 'GetAppQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:getApp', __args__, opts=opts, typ=GetAppResult)
    return __ret__.apply(lambda __response__: GetAppResult(
        id=pulumi.get(__response__, 'id'),
        internal_numeric_id=pulumi.get(__response__, 'internal_numeric_id'),
        machine_count=pulumi.get(__response__, 'machine_count'),
        name=pulumi.get(__response__, 'name'),
        network=pulumi.get(__response__, 'network'),
        network_cidr=pulumi.get(__response__, 'network_cidr'),
        organization=pulumi.get(__response__, 'organization'),
        status=pulumi.get(__response__, 'status'),
        volume_count=pulumi.get(__response__, 'volume_count')))
