# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'ListAppIPAssignmentsResult',
    'AwaitableListAppIPAssignmentsResult',
    'list_app_ipassignments',
    'list_app_ipassignments_output',
]

@pulumi.output_type
class ListAppIPAssignmentsResult:
    def __init__(__self__, ips=None):
        if ips and not isinstance(ips, list):
            raise TypeError("Expected argument 'ips' to be a list")
        pulumi.set(__self__, "ips", ips)

    @_builtins.property
    @pulumi.getter
    def ips(self) -> Optional[Sequence['outputs.IPAssignment']]:
        return pulumi.get(self, "ips")


class AwaitableListAppIPAssignmentsResult(ListAppIPAssignmentsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListAppIPAssignmentsResult(
            ips=self.ips)


def list_app_ipassignments(app_name: Optional[_builtins.str] = None,
                           query_params: Optional[Union['ListAppIPAssignmentsQueryParams', 'ListAppIPAssignmentsQueryParamsDict']] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListAppIPAssignmentsResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param Union['ListAppIPAssignmentsQueryParams', 'ListAppIPAssignmentsQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:listAppIPAssignments', __args__, opts=opts, typ=ListAppIPAssignmentsResult).value

    return AwaitableListAppIPAssignmentsResult(
        ips=pulumi.get(__ret__, 'ips'))
def list_app_ipassignments_output(app_name: pulumi.Input[Optional[_builtins.str]] = None,
                                  query_params: pulumi.Input[Optional[Optional[Union['ListAppIPAssignmentsQueryParams', 'ListAppIPAssignmentsQueryParamsDict']]]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListAppIPAssignmentsResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param Union['ListAppIPAssignmentsQueryParams', 'ListAppIPAssignmentsQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:listAppIPAssignments', __args__, opts=opts, typ=ListAppIPAssignmentsResult)
    return __ret__.apply(lambda __response__: ListAppIPAssignmentsResult(
        ips=pulumi.get(__response__, 'ips')))
