# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ListMachinesResult',
    'AwaitableListMachinesResult',
    'list_machines',
    'list_machines_output',
]

@pulumi.output_type
class ListMachinesResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, list):
            raise TypeError("Expected argument 'items' to be a list")
        pulumi.set(__self__, "items", items)

    @_builtins.property
    @pulumi.getter
    def items(self) -> Sequence['outputs.Machine']:
        return pulumi.get(self, "items")


class AwaitableListMachinesResult(ListMachinesResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListMachinesResult(
            items=self.items)


def list_machines(app_name: Optional[_builtins.str] = None,
                  opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListMachinesResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    """
    __args__ = dict()
    __args__['appName'] = app_name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:listMachines', __args__, opts=opts, typ=ListMachinesResult).value

    return AwaitableListMachinesResult(
        items=pulumi.get(__ret__, 'items'))
def list_machines_output(app_name: pulumi.Input[Optional[_builtins.str]] = None,
                         opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListMachinesResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    """
    __args__ = dict()
    __args__['appName'] = app_name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:listMachines', __args__, opts=opts, typ=ListMachinesResult)
    return __ret__.apply(lambda __response__: ListMachinesResult(
        items=pulumi.get(__response__, 'items')))
