# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs

__all__ = [
    'ListAppsResult',
    'AwaitableListAppsResult',
    'list_apps',
    'list_apps_output',
]

@pulumi.output_type
class ListAppsResult:
    def __init__(__self__, apps=None, total_apps=None):
        if apps and not isinstance(apps, list):
            raise TypeError("Expected argument 'apps' to be a list")
        pulumi.set(__self__, "apps", apps)
        if total_apps and not isinstance(total_apps, int):
            raise TypeError("Expected argument 'total_apps' to be a int")
        pulumi.set(__self__, "total_apps", total_apps)

    @_builtins.property
    @pulumi.getter
    def apps(self) -> Optional[Sequence['outputs.App']]:
        return pulumi.get(self, "apps")

    @_builtins.property
    @pulumi.getter(name="totalApps")
    def total_apps(self) -> Optional[_builtins.int]:
        return pulumi.get(self, "total_apps")


class AwaitableListAppsResult(ListAppsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListAppsResult(
            apps=self.apps,
            total_apps=self.total_apps)


def list_apps(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListAppsResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:listApps', __args__, opts=opts, typ=ListAppsResult).value

    return AwaitableListAppsResult(
        apps=pulumi.get(__ret__, 'apps'),
        total_apps=pulumi.get(__ret__, 'total_apps'))
def list_apps_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListAppsResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:listApps', __args__, opts=opts, typ=ListAppsResult)
    return __ret__.apply(lambda __response__: ListAppsResult(
        apps=pulumi.get(__response__, 'apps'),
        total_apps=pulumi.get(__response__, 'total_apps')))
