# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs

__all__ = [
    'ListVolumesSnapshotsResult',
    'AwaitableListVolumesSnapshotsResult',
    'list_volumes_snapshots',
    'list_volumes_snapshots_output',
]

@pulumi.output_type
class ListVolumesSnapshotsResult:
    def __init__(__self__, items=None):
        if items and not isinstance(items, list):
            raise TypeError("Expected argument 'items' to be a list")
        pulumi.set(__self__, "items", items)

    @_builtins.property
    @pulumi.getter
    def items(self) -> Sequence['outputs.VolumeSnapshot']:
        return pulumi.get(self, "items")


class AwaitableListVolumesSnapshotsResult(ListVolumesSnapshotsResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListVolumesSnapshotsResult(
            items=self.items)


def list_volumes_snapshots(app_name: Optional[_builtins.str] = None,
                           volume_id: Optional[_builtins.str] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListVolumesSnapshotsResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param _builtins.str volume_id: Volume ID
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['volumeId'] = volume_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:apps/v1:listVolumesSnapshots', __args__, opts=opts, typ=ListVolumesSnapshotsResult).value

    return AwaitableListVolumesSnapshotsResult(
        items=pulumi.get(__ret__, 'items'))
def list_volumes_snapshots_output(app_name: pulumi.Input[Optional[_builtins.str]] = None,
                                  volume_id: pulumi.Input[Optional[_builtins.str]] = None,
                                  opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListVolumesSnapshotsResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str app_name: Fly App Name
    :param _builtins.str volume_id: Volume ID
    """
    __args__ = dict()
    __args__['appName'] = app_name
    __args__['volumeId'] = volume_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:apps/v1:listVolumesSnapshots', __args__, opts=opts, typ=ListVolumesSnapshotsResult)
    return __ret__.apply(lambda __response__: ListVolumesSnapshotsResult(
        items=pulumi.get(__response__, 'items')))
