# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SecretArgs', 'Secret']

@pulumi.input_type
class SecretArgs:
    def __init__(__self__, *,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 query_params: pulumi.Input[Optional['SecretQueryParamsArgs']] = None,
                 secret_name: pulumi.Input[Optional[_builtins.str]] = None,
                 value: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a Secret resource.

        :param pulumi.Input[_builtins.str] app_name: Fly App Name
        :param pulumi.Input['SecretQueryParamsArgs'] query_params: Query params to send with the API requests for this resource.
        :param pulumi.Input[_builtins.str] secret_name: App secret name
        """
        if app_name is not None:
            pulumi.set(__self__, "app_name", app_name)
        if query_params is not None:
            pulumi.set(__self__, "query_params", query_params)
        if secret_name is not None:
            pulumi.set(__self__, "secret_name", secret_name)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Fly App Name
        """
        return pulumi.get(self, "app_name")

    @app_name.setter
    def app_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "app_name", value)

    @_builtins.property
    @pulumi.getter(name="queryParams")
    def query_params(self) -> pulumi.Input[Optional['SecretQueryParamsArgs']]:
        """
        Query params to send with the API requests for this resource.
        """
        return pulumi.get(self, "query_params")

    @query_params.setter
    def query_params(self, value: pulumi.Input[Optional['SecretQueryParamsArgs']]):
        pulumi.set(self, "query_params", value)

    @_builtins.property
    @pulumi.getter(name="secretName")
    def secret_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        App secret name
        """
        return pulumi.get(self, "secret_name")

    @secret_name.setter
    def secret_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "secret_name", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "value", value)


@pulumi.type_token("fly-machines:apps/v1:Secret")
class Secret(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 query_params: pulumi.Input[Optional[Union['SecretQueryParamsArgs', 'SecretQueryParamsArgsDict', 'outputs.SecretQueryParams']]] = None,
                 secret_name: pulumi.Input[Optional[_builtins.str]] = None,
                 value: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Secret resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] app_name: Fly App Name
        :param pulumi.Input[Union['SecretQueryParamsArgs', 'SecretQueryParamsArgsDict', 'outputs.SecretQueryParams']] query_params: Query params to send with the API requests for this resource.
        :param pulumi.Input[_builtins.str] secret_name: App secret name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SecretArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Secret resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SecretArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SecretArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 query_params: pulumi.Input[Optional[Union['SecretQueryParamsArgs', 'SecretQueryParamsArgsDict', 'outputs.SecretQueryParams']]] = None,
                 secret_name: pulumi.Input[Optional[_builtins.str]] = None,
                 value: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SecretArgs.__new__(SecretArgs)

            __props__.__dict__["app_name"] = app_name
            __props__.__dict__["query_params"] = query_params
            __props__.__dict__["secret_name"] = secret_name
            __props__.__dict__["value"] = value
            __props__.__dict__["created_at"] = None
            __props__.__dict__["digest"] = None
            __props__.__dict__["name"] = None
            __props__.__dict__["updated_at"] = None
            __props__.__dict__["version"] = None
        super(Secret, __self__).__init__(
            'fly-machines:apps/v1:Secret',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Secret':
        """
        Get an existing Secret resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = SecretArgs.__new__(SecretArgs)

        __props__.__dict__["created_at"] = None
        __props__.__dict__["digest"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["query_params"] = None
        __props__.__dict__["updated_at"] = None
        __props__.__dict__["value"] = None
        __props__.__dict__["version"] = None
        return Secret(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def digest(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "digest")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="queryParams")
    def query_params(self) -> pulumi.Output[Optional['outputs.SecretQueryParams']]:
        """
        Query params to send with the API requests for this resource.
        """
        return pulumi.get(self, "query_params")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "value")

    @_builtins.property
    @pulumi.getter
    def version(self) -> pulumi.Output[Optional[_builtins.int]]:
        return pulumi.get(self, "version")

