// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: use MachineConfig.Rootfs instead
type FlyMachineGuestPersistRootfs string

const (
	FlyMachineGuestPersistRootfsNever   = FlyMachineGuestPersistRootfs("never")
	FlyMachineGuestPersistRootfsAlways  = FlyMachineGuestPersistRootfs("always")
	FlyMachineGuestPersistRootfsRestart = FlyMachineGuestPersistRootfs("restart")
)

func (FlyMachineGuestPersistRootfs) ElementType() reflect.Type {
	return reflect.TypeOf((*FlyMachineGuestPersistRootfs)(nil)).Elem()
}

func (e FlyMachineGuestPersistRootfs) ToFlyMachineGuestPersistRootfsOutput() FlyMachineGuestPersistRootfsOutput {
	return pulumi.ToOutput(e).(FlyMachineGuestPersistRootfsOutput)
}

func (e FlyMachineGuestPersistRootfs) ToFlyMachineGuestPersistRootfsOutputWithContext(ctx context.Context) FlyMachineGuestPersistRootfsOutput {
	return pulumi.ToOutputWithContext(ctx, e).(FlyMachineGuestPersistRootfsOutput)
}

func (e FlyMachineGuestPersistRootfs) ToFlyMachineGuestPersistRootfsPtrOutput() FlyMachineGuestPersistRootfsPtrOutput {
	return e.ToFlyMachineGuestPersistRootfsPtrOutputWithContext(context.Background())
}

func (e FlyMachineGuestPersistRootfs) ToFlyMachineGuestPersistRootfsPtrOutputWithContext(ctx context.Context) FlyMachineGuestPersistRootfsPtrOutput {
	return FlyMachineGuestPersistRootfs(e).ToFlyMachineGuestPersistRootfsOutputWithContext(ctx).ToFlyMachineGuestPersistRootfsPtrOutputWithContext(ctx)
}

func (e FlyMachineGuestPersistRootfs) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e FlyMachineGuestPersistRootfs) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e FlyMachineGuestPersistRootfs) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e FlyMachineGuestPersistRootfs) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type FlyMachineGuestPersistRootfsOutput struct{ *pulumi.OutputState }

func (FlyMachineGuestPersistRootfsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*FlyMachineGuestPersistRootfs)(nil)).Elem()
}

func (o FlyMachineGuestPersistRootfsOutput) ToFlyMachineGuestPersistRootfsOutput() FlyMachineGuestPersistRootfsOutput {
	return o
}

func (o FlyMachineGuestPersistRootfsOutput) ToFlyMachineGuestPersistRootfsOutputWithContext(ctx context.Context) FlyMachineGuestPersistRootfsOutput {
	return o
}

func (o FlyMachineGuestPersistRootfsOutput) ToFlyMachineGuestPersistRootfsPtrOutput() FlyMachineGuestPersistRootfsPtrOutput {
	return o.ToFlyMachineGuestPersistRootfsPtrOutputWithContext(context.Background())
}

func (o FlyMachineGuestPersistRootfsOutput) ToFlyMachineGuestPersistRootfsPtrOutputWithContext(ctx context.Context) FlyMachineGuestPersistRootfsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v FlyMachineGuestPersistRootfs) *FlyMachineGuestPersistRootfs {
		return &v
	}).(FlyMachineGuestPersistRootfsPtrOutput)
}

func (o FlyMachineGuestPersistRootfsOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o FlyMachineGuestPersistRootfsOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e FlyMachineGuestPersistRootfs) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o FlyMachineGuestPersistRootfsOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o FlyMachineGuestPersistRootfsOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e FlyMachineGuestPersistRootfs) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type FlyMachineGuestPersistRootfsPtrOutput struct{ *pulumi.OutputState }

func (FlyMachineGuestPersistRootfsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**FlyMachineGuestPersistRootfs)(nil)).Elem()
}

func (o FlyMachineGuestPersistRootfsPtrOutput) ToFlyMachineGuestPersistRootfsPtrOutput() FlyMachineGuestPersistRootfsPtrOutput {
	return o
}

func (o FlyMachineGuestPersistRootfsPtrOutput) ToFlyMachineGuestPersistRootfsPtrOutputWithContext(ctx context.Context) FlyMachineGuestPersistRootfsPtrOutput {
	return o
}

func (o FlyMachineGuestPersistRootfsPtrOutput) Elem() FlyMachineGuestPersistRootfsOutput {
	return o.ApplyT(func(v *FlyMachineGuestPersistRootfs) FlyMachineGuestPersistRootfs {
		if v != nil {
			return *v
		}
		var ret FlyMachineGuestPersistRootfs
		return ret
	}).(FlyMachineGuestPersistRootfsOutput)
}

func (o FlyMachineGuestPersistRootfsPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o FlyMachineGuestPersistRootfsPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *FlyMachineGuestPersistRootfs) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// FlyMachineGuestPersistRootfsInput is an input type that accepts values of the FlyMachineGuestPersistRootfs enum
// A concrete instance of `FlyMachineGuestPersistRootfsInput` can be one of the following:
//
//	FlyMachineGuestPersistRootfsNever
//	FlyMachineGuestPersistRootfsAlways
//	FlyMachineGuestPersistRootfsRestart
type FlyMachineGuestPersistRootfsInput interface {
	pulumi.Input

	ToFlyMachineGuestPersistRootfsOutput() FlyMachineGuestPersistRootfsOutput
	ToFlyMachineGuestPersistRootfsOutputWithContext(context.Context) FlyMachineGuestPersistRootfsOutput
}

var flyMachineGuestPersistRootfsPtrType = reflect.TypeOf((**FlyMachineGuestPersistRootfs)(nil)).Elem()

type FlyMachineGuestPersistRootfsPtrInput interface {
	pulumi.Input

	ToFlyMachineGuestPersistRootfsPtrOutput() FlyMachineGuestPersistRootfsPtrOutput
	ToFlyMachineGuestPersistRootfsPtrOutputWithContext(context.Context) FlyMachineGuestPersistRootfsPtrOutput
}

type flyMachineGuestPersistRootfsPtr string

func FlyMachineGuestPersistRootfsPtr(v string) FlyMachineGuestPersistRootfsPtrInput {
	return (*flyMachineGuestPersistRootfsPtr)(&v)
}

func (*flyMachineGuestPersistRootfsPtr) ElementType() reflect.Type {
	return flyMachineGuestPersistRootfsPtrType
}

func (in *flyMachineGuestPersistRootfsPtr) ToFlyMachineGuestPersistRootfsPtrOutput() FlyMachineGuestPersistRootfsPtrOutput {
	return pulumi.ToOutput(in).(FlyMachineGuestPersistRootfsPtrOutput)
}

func (in *flyMachineGuestPersistRootfsPtr) ToFlyMachineGuestPersistRootfsPtrOutputWithContext(ctx context.Context) FlyMachineGuestPersistRootfsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(FlyMachineGuestPersistRootfsPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*FlyMachineGuestPersistRootfsInput)(nil)).Elem(), FlyMachineGuestPersistRootfs("never"))
	pulumi.RegisterInputType(reflect.TypeOf((*FlyMachineGuestPersistRootfsPtrInput)(nil)).Elem(), FlyMachineGuestPersistRootfs("never"))
	pulumi.RegisterOutputType(FlyMachineGuestPersistRootfsOutput{})
	pulumi.RegisterOutputType(FlyMachineGuestPersistRootfsPtrOutput{})
}
