// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-fly-machines/sdk/go/fly-machines/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

// Resource requirements for the Machine to simulate. Defaults to a performance-1x machine
type Compute struct {
	CpuKind          *string  `pulumi:"cpuKind"`
	Cpus             *int     `pulumi:"cpus"`
	GpuKind          *string  `pulumi:"gpuKind"`
	Gpus             *int     `pulumi:"gpus"`
	HostDedicationId *string  `pulumi:"hostDedicationId"`
	KernelArgs       []string `pulumi:"kernelArgs"`
	MaxMemoryMb      *int     `pulumi:"maxMemoryMb"`
	MemoryMb         *int     `pulumi:"memoryMb"`
	// Deprecated: use MachineConfig.Rootfs instead
	PersistRootfs        *FlyMachineGuestPersistRootfs `pulumi:"persistRootfs"`
	RequiredHostFeatures []string                      `pulumi:"requiredHostFeatures"`
}

// ComputeInput is an input type that accepts ComputeArgs and ComputeOutput values.
// You can construct a concrete instance of `ComputeInput` via:
//
//	ComputeArgs{...}
type ComputeInput interface {
	pulumi.Input

	ToComputeOutput() ComputeOutput
	ToComputeOutputWithContext(context.Context) ComputeOutput
}

// Resource requirements for the Machine to simulate. Defaults to a performance-1x machine
type ComputeArgs struct {
	CpuKind          pulumi.StringPtrInput   `pulumi:"cpuKind"`
	Cpus             pulumi.IntPtrInput      `pulumi:"cpus"`
	GpuKind          pulumi.StringPtrInput   `pulumi:"gpuKind"`
	Gpus             pulumi.IntPtrInput      `pulumi:"gpus"`
	HostDedicationId pulumi.StringPtrInput   `pulumi:"hostDedicationId"`
	KernelArgs       pulumi.StringArrayInput `pulumi:"kernelArgs"`
	MaxMemoryMb      pulumi.IntPtrInput      `pulumi:"maxMemoryMb"`
	MemoryMb         pulumi.IntPtrInput      `pulumi:"memoryMb"`
	// Deprecated: use MachineConfig.Rootfs instead
	PersistRootfs        FlyMachineGuestPersistRootfsPtrInput `pulumi:"persistRootfs"`
	RequiredHostFeatures pulumi.StringArrayInput              `pulumi:"requiredHostFeatures"`
}

func (ComputeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Compute)(nil)).Elem()
}

func (i ComputeArgs) ToComputeOutput() ComputeOutput {
	return i.ToComputeOutputWithContext(context.Background())
}

func (i ComputeArgs) ToComputeOutputWithContext(ctx context.Context) ComputeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputeOutput)
}

func (i ComputeArgs) ToComputePtrOutput() ComputePtrOutput {
	return i.ToComputePtrOutputWithContext(context.Background())
}

func (i ComputeArgs) ToComputePtrOutputWithContext(ctx context.Context) ComputePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputeOutput).ToComputePtrOutputWithContext(ctx)
}

// ComputePtrInput is an input type that accepts ComputeArgs, ComputePtr and ComputePtrOutput values.
// You can construct a concrete instance of `ComputePtrInput` via:
//
//	        ComputeArgs{...}
//
//	or:
//
//	        nil
type ComputePtrInput interface {
	pulumi.Input

	ToComputePtrOutput() ComputePtrOutput
	ToComputePtrOutputWithContext(context.Context) ComputePtrOutput
}

type computePtrType ComputeArgs

func ComputePtr(v *ComputeArgs) ComputePtrInput {
	return (*computePtrType)(v)
}

func (*computePtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Compute)(nil)).Elem()
}

func (i *computePtrType) ToComputePtrOutput() ComputePtrOutput {
	return i.ToComputePtrOutputWithContext(context.Background())
}

func (i *computePtrType) ToComputePtrOutputWithContext(ctx context.Context) ComputePtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComputePtrOutput)
}

// Resource requirements for the Machine to simulate. Defaults to a performance-1x machine
type ComputeOutput struct{ *pulumi.OutputState }

func (ComputeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Compute)(nil)).Elem()
}

func (o ComputeOutput) ToComputeOutput() ComputeOutput {
	return o
}

func (o ComputeOutput) ToComputeOutputWithContext(ctx context.Context) ComputeOutput {
	return o
}

func (o ComputeOutput) ToComputePtrOutput() ComputePtrOutput {
	return o.ToComputePtrOutputWithContext(context.Background())
}

func (o ComputeOutput) ToComputePtrOutputWithContext(ctx context.Context) ComputePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Compute) *Compute {
		return &v
	}).(ComputePtrOutput)
}

func (o ComputeOutput) CpuKind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Compute) *string { return v.CpuKind }).(pulumi.StringPtrOutput)
}

func (o ComputeOutput) Cpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Compute) *int { return v.Cpus }).(pulumi.IntPtrOutput)
}

func (o ComputeOutput) GpuKind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Compute) *string { return v.GpuKind }).(pulumi.StringPtrOutput)
}

func (o ComputeOutput) Gpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Compute) *int { return v.Gpus }).(pulumi.IntPtrOutput)
}

func (o ComputeOutput) HostDedicationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Compute) *string { return v.HostDedicationId }).(pulumi.StringPtrOutput)
}

func (o ComputeOutput) KernelArgs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Compute) []string { return v.KernelArgs }).(pulumi.StringArrayOutput)
}

func (o ComputeOutput) MaxMemoryMb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Compute) *int { return v.MaxMemoryMb }).(pulumi.IntPtrOutput)
}

func (o ComputeOutput) MemoryMb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Compute) *int { return v.MemoryMb }).(pulumi.IntPtrOutput)
}

// Deprecated: use MachineConfig.Rootfs instead
func (o ComputeOutput) PersistRootfs() FlyMachineGuestPersistRootfsPtrOutput {
	return o.ApplyT(func(v Compute) *FlyMachineGuestPersistRootfs { return v.PersistRootfs }).(FlyMachineGuestPersistRootfsPtrOutput)
}

func (o ComputeOutput) RequiredHostFeatures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Compute) []string { return v.RequiredHostFeatures }).(pulumi.StringArrayOutput)
}

type ComputePtrOutput struct{ *pulumi.OutputState }

func (ComputePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Compute)(nil)).Elem()
}

func (o ComputePtrOutput) ToComputePtrOutput() ComputePtrOutput {
	return o
}

func (o ComputePtrOutput) ToComputePtrOutputWithContext(ctx context.Context) ComputePtrOutput {
	return o
}

func (o ComputePtrOutput) Elem() ComputeOutput {
	return o.ApplyT(func(v *Compute) Compute {
		if v != nil {
			return *v
		}
		var ret Compute
		return ret
	}).(ComputeOutput)
}

func (o ComputePtrOutput) CpuKind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Compute) *string {
		if v == nil {
			return nil
		}
		return v.CpuKind
	}).(pulumi.StringPtrOutput)
}

func (o ComputePtrOutput) Cpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Compute) *int {
		if v == nil {
			return nil
		}
		return v.Cpus
	}).(pulumi.IntPtrOutput)
}

func (o ComputePtrOutput) GpuKind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Compute) *string {
		if v == nil {
			return nil
		}
		return v.GpuKind
	}).(pulumi.StringPtrOutput)
}

func (o ComputePtrOutput) Gpus() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Compute) *int {
		if v == nil {
			return nil
		}
		return v.Gpus
	}).(pulumi.IntPtrOutput)
}

func (o ComputePtrOutput) HostDedicationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Compute) *string {
		if v == nil {
			return nil
		}
		return v.HostDedicationId
	}).(pulumi.StringPtrOutput)
}

func (o ComputePtrOutput) KernelArgs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Compute) []string {
		if v == nil {
			return nil
		}
		return v.KernelArgs
	}).(pulumi.StringArrayOutput)
}

func (o ComputePtrOutput) MaxMemoryMb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Compute) *int {
		if v == nil {
			return nil
		}
		return v.MaxMemoryMb
	}).(pulumi.IntPtrOutput)
}

func (o ComputePtrOutput) MemoryMb() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Compute) *int {
		if v == nil {
			return nil
		}
		return v.MemoryMb
	}).(pulumi.IntPtrOutput)
}

// Deprecated: use MachineConfig.Rootfs instead
func (o ComputePtrOutput) PersistRootfs() FlyMachineGuestPersistRootfsPtrOutput {
	return o.ApplyT(func(v *Compute) *FlyMachineGuestPersistRootfs {
		if v == nil {
			return nil
		}
		return v.PersistRootfs
	}).(FlyMachineGuestPersistRootfsPtrOutput)
}

func (o ComputePtrOutput) RequiredHostFeatures() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Compute) []string {
		if v == nil {
			return nil
		}
		return v.RequiredHostFeatures
	}).(pulumi.StringArrayOutput)
}

type MainRegionResponse struct {
	Nearest *string         `pulumi:"nearest"`
	Regions []MainRegionRow `pulumi:"regions"`
}

type MainRegionRow struct {
	Code             *string  `pulumi:"code"`
	Deprecated       *bool    `pulumi:"deprecated"`
	GatewayAvailable *bool    `pulumi:"gatewayAvailable"`
	GeoRegion        *string  `pulumi:"geoRegion"`
	Latitude         *float64 `pulumi:"latitude"`
	Longitude        *float64 `pulumi:"longitude"`
	MpgAvailable     *bool    `pulumi:"mpgAvailable"`
	Name             *string  `pulumi:"name"`
	RequiresPaidPlan *bool    `pulumi:"requiresPaidPlan"`
}

type MainRegionRowOutput struct{ *pulumi.OutputState }

func (MainRegionRowOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*MainRegionRow)(nil)).Elem()
}

func (o MainRegionRowOutput) ToMainRegionRowOutput() MainRegionRowOutput {
	return o
}

func (o MainRegionRowOutput) ToMainRegionRowOutputWithContext(ctx context.Context) MainRegionRowOutput {
	return o
}

func (o MainRegionRowOutput) Code() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *string { return v.Code }).(pulumi.StringPtrOutput)
}

func (o MainRegionRowOutput) Deprecated() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *bool { return v.Deprecated }).(pulumi.BoolPtrOutput)
}

func (o MainRegionRowOutput) GatewayAvailable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *bool { return v.GatewayAvailable }).(pulumi.BoolPtrOutput)
}

func (o MainRegionRowOutput) GeoRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *string { return v.GeoRegion }).(pulumi.StringPtrOutput)
}

func (o MainRegionRowOutput) Latitude() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v MainRegionRow) *float64 { return v.Latitude }).(pulumi.Float64PtrOutput)
}

func (o MainRegionRowOutput) Longitude() pulumi.Float64PtrOutput {
	return o.ApplyT(func(v MainRegionRow) *float64 { return v.Longitude }).(pulumi.Float64PtrOutput)
}

func (o MainRegionRowOutput) MpgAvailable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *bool { return v.MpgAvailable }).(pulumi.BoolPtrOutput)
}

func (o MainRegionRowOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o MainRegionRowOutput) RequiresPaidPlan() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v MainRegionRow) *bool { return v.RequiresPaidPlan }).(pulumi.BoolPtrOutput)
}

type MainRegionRowArrayOutput struct{ *pulumi.OutputState }

func (MainRegionRowArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]MainRegionRow)(nil)).Elem()
}

func (o MainRegionRowArrayOutput) ToMainRegionRowArrayOutput() MainRegionRowArrayOutput {
	return o
}

func (o MainRegionRowArrayOutput) ToMainRegionRowArrayOutputWithContext(ctx context.Context) MainRegionRowArrayOutput {
	return o
}

func (o MainRegionRowArrayOutput) Index(i pulumi.IntInput) MainRegionRowOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) MainRegionRow {
		return vs[0].([]MainRegionRow)[vs[1].(int)]
	}).(MainRegionRowOutput)
}

type PlacementRegionPlacement struct {
	Concurrency *int    `pulumi:"concurrency"`
	Count       *int    `pulumi:"count"`
	Region      *string `pulumi:"region"`
}

type PlacementRegionPlacementOutput struct{ *pulumi.OutputState }

func (PlacementRegionPlacementOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PlacementRegionPlacement)(nil)).Elem()
}

func (o PlacementRegionPlacementOutput) ToPlacementRegionPlacementOutput() PlacementRegionPlacementOutput {
	return o
}

func (o PlacementRegionPlacementOutput) ToPlacementRegionPlacementOutputWithContext(ctx context.Context) PlacementRegionPlacementOutput {
	return o
}

func (o PlacementRegionPlacementOutput) Concurrency() pulumi.IntPtrOutput {
	return o.ApplyT(func(v PlacementRegionPlacement) *int { return v.Concurrency }).(pulumi.IntPtrOutput)
}

func (o PlacementRegionPlacementOutput) Count() pulumi.IntPtrOutput {
	return o.ApplyT(func(v PlacementRegionPlacement) *int { return v.Count }).(pulumi.IntPtrOutput)
}

func (o PlacementRegionPlacementOutput) Region() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PlacementRegionPlacement) *string { return v.Region }).(pulumi.StringPtrOutput)
}

type PlacementRegionPlacementArrayOutput struct{ *pulumi.OutputState }

func (PlacementRegionPlacementArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PlacementRegionPlacement)(nil)).Elem()
}

func (o PlacementRegionPlacementArrayOutput) ToPlacementRegionPlacementArrayOutput() PlacementRegionPlacementArrayOutput {
	return o
}

func (o PlacementRegionPlacementArrayOutput) ToPlacementRegionPlacementArrayOutputWithContext(ctx context.Context) PlacementRegionPlacementArrayOutput {
	return o
}

func (o PlacementRegionPlacementArrayOutput) Index(i pulumi.IntInput) PlacementRegionPlacementOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PlacementRegionPlacement {
		return vs[0].([]PlacementRegionPlacement)[vs[1].(int)]
	}).(PlacementRegionPlacementOutput)
}

// Optional weights to override default placement preferences.
type Weights struct {
}

// WeightsInput is an input type that accepts WeightsArgs and WeightsOutput values.
// You can construct a concrete instance of `WeightsInput` via:
//
//	WeightsArgs{...}
type WeightsInput interface {
	pulumi.Input

	ToWeightsOutput() WeightsOutput
	ToWeightsOutputWithContext(context.Context) WeightsOutput
}

// Optional weights to override default placement preferences.
type WeightsArgs struct {
}

func (WeightsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Weights)(nil)).Elem()
}

func (i WeightsArgs) ToWeightsOutput() WeightsOutput {
	return i.ToWeightsOutputWithContext(context.Background())
}

func (i WeightsArgs) ToWeightsOutputWithContext(ctx context.Context) WeightsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WeightsOutput)
}

func (i WeightsArgs) ToWeightsPtrOutput() WeightsPtrOutput {
	return i.ToWeightsPtrOutputWithContext(context.Background())
}

func (i WeightsArgs) ToWeightsPtrOutputWithContext(ctx context.Context) WeightsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WeightsOutput).ToWeightsPtrOutputWithContext(ctx)
}

// WeightsPtrInput is an input type that accepts WeightsArgs, WeightsPtr and WeightsPtrOutput values.
// You can construct a concrete instance of `WeightsPtrInput` via:
//
//	        WeightsArgs{...}
//
//	or:
//
//	        nil
type WeightsPtrInput interface {
	pulumi.Input

	ToWeightsPtrOutput() WeightsPtrOutput
	ToWeightsPtrOutputWithContext(context.Context) WeightsPtrOutput
}

type weightsPtrType WeightsArgs

func WeightsPtr(v *WeightsArgs) WeightsPtrInput {
	return (*weightsPtrType)(v)
}

func (*weightsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Weights)(nil)).Elem()
}

func (i *weightsPtrType) ToWeightsPtrOutput() WeightsPtrOutput {
	return i.ToWeightsPtrOutputWithContext(context.Background())
}

func (i *weightsPtrType) ToWeightsPtrOutputWithContext(ctx context.Context) WeightsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(WeightsPtrOutput)
}

// Optional weights to override default placement preferences.
type WeightsOutput struct{ *pulumi.OutputState }

func (WeightsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Weights)(nil)).Elem()
}

func (o WeightsOutput) ToWeightsOutput() WeightsOutput {
	return o
}

func (o WeightsOutput) ToWeightsOutputWithContext(ctx context.Context) WeightsOutput {
	return o
}

func (o WeightsOutput) ToWeightsPtrOutput() WeightsPtrOutput {
	return o.ToWeightsPtrOutputWithContext(context.Background())
}

func (o WeightsOutput) ToWeightsPtrOutputWithContext(ctx context.Context) WeightsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Weights) *Weights {
		return &v
	}).(WeightsPtrOutput)
}

type WeightsPtrOutput struct{ *pulumi.OutputState }

func (WeightsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Weights)(nil)).Elem()
}

func (o WeightsPtrOutput) ToWeightsPtrOutput() WeightsPtrOutput {
	return o
}

func (o WeightsPtrOutput) ToWeightsPtrOutputWithContext(ctx context.Context) WeightsPtrOutput {
	return o
}

func (o WeightsPtrOutput) Elem() WeightsOutput {
	return o.ApplyT(func(v *Weights) Weights {
		if v != nil {
			return *v
		}
		var ret Weights
		return ret
	}).(WeightsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ComputeInput)(nil)).Elem(), ComputeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ComputePtrInput)(nil)).Elem(), ComputeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WeightsInput)(nil)).Elem(), WeightsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*WeightsPtrInput)(nil)).Elem(), WeightsArgs{})
	pulumi.RegisterOutputType(ComputeOutput{})
	pulumi.RegisterOutputType(ComputePtrOutput{})
	pulumi.RegisterOutputType(MainRegionRowOutput{})
	pulumi.RegisterOutputType(MainRegionRowArrayOutput{})
	pulumi.RegisterOutputType(PlacementRegionPlacementOutput{})
	pulumi.RegisterOutputType(PlacementRegionPlacementArrayOutput{})
	pulumi.RegisterOutputType(WeightsOutput{})
	pulumi.RegisterOutputType(WeightsPtrOutput{})
}
