// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PostgresV1.Inputs
{

    /// <summary>
    /// Query params for the API request.
    /// </summary>
    public sealed class ListPostgresQueryParams : global::Pulumi.InvokeArgs
    {
        [Input("additionalParams")]
        private Dictionary<string, string>? _additionalParams;

        /// <summary>
        /// Additional query params to send with the request that are not defined in the API spec.
        /// </summary>
        public Dictionary<string, string> AdditionalParams
        {
            get => _additionalParams ?? (_additionalParams = new Dictionary<string, string>());
            set => _additionalParams = value;
        }

        /// <summary>
        /// Include deleted clusters
        /// </summary>
        [Input("includeDeleted")]
        public bool? IncludeDeleted { get; set; }

        /// <summary>
        /// Fly Organization Slug, or 'personal' for the caller's personal organization
        /// </summary>
        [Input("orgSlug", required: true)]
        public string OrgSlug { get; set; } = null!;

        public ListPostgresQueryParams()
        {
        }
        public static new ListPostgresQueryParams Empty => new ListPostgresQueryParams();
    }
}
