// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listVolumesOrg(args: ListVolumesOrgArgs, opts?: pulumi.InvokeOptions): Promise<ListVolumesOrgResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:orgs/v1:listVolumesOrg", {
        "orgSlug": args.orgSlug,
        "queryParams": args.queryParams,
    }, opts);
}

export interface ListVolumesOrgArgs {
    /**
     * Fly Organization Slug
     */
    orgSlug: string;
    /**
     * Query params to send with the API request.
     */
    queryParams?: inputs.orgs.v1.ListVolumesOrgQueryParams;
}

export interface ListVolumesOrgResult {
    readonly lastUpdatedAt?: string;
    readonly lastVolumeId?: string;
    readonly nextCursor?: string;
    readonly volumes?: outputs.orgs.v1.OrgVolume[];
}
export function listVolumesOrgOutput(args: ListVolumesOrgOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListVolumesOrgResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:orgs/v1:listVolumesOrg", {
        "orgSlug": args.orgSlug,
        "queryParams": args.queryParams,
    }, opts);
}

export interface ListVolumesOrgOutputArgs {
    /**
     * Fly Organization Slug
     */
    orgSlug: pulumi.Input<string>;
    /**
     * Query params to send with the API request.
     */
    queryParams?: pulumi.Input<inputs.orgs.v1.ListVolumesOrgQueryParamsArgs | undefined>;
}
