// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export function listMachinesOrg(args: ListMachinesOrgArgs, opts?: pulumi.InvokeOptions): Promise<ListMachinesOrgResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("fly-machines:orgs/v1:listMachinesOrg", {
        "orgSlug": args.orgSlug,
    }, opts);
}

export interface ListMachinesOrgArgs {
    /**
     * Fly Organization Slug
     */
    orgSlug: string;
}

export interface ListMachinesOrgResult {
    readonly errorRegions?: string[];
    readonly lastMachineId?: string;
    readonly lastUpdatedAt?: string;
    readonly machines?: outputs.orgs.v1.OrgMachine[];
    readonly nextCursor?: string;
}
export function listMachinesOrgOutput(args: ListMachinesOrgOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<ListMachinesOrgResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("fly-machines:orgs/v1:listMachinesOrg", {
        "orgSlug": args.orgSlug,
    }, opts);
}

export interface ListMachinesOrgOutputArgs {
    /**
     * Fly Organization Slug
     */
    orgSlug: pulumi.Input<string>;
}
