// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PostgresV1.Outputs
{

    [OutputType]
    public sealed class PostgresActiveQuery
    {
        /// <summary>
        /// Application connected to the backend.
        /// </summary>
        public readonly string? ApplicationName;
        /// <summary>
        /// Client address.
        /// </summary>
        public readonly string? Client;
        /// <summary>
        /// Database name.
        /// </summary>
        public readonly string? Database;
        /// <summary>
        /// Query duration in seconds.
        /// </summary>
        public readonly double? DurationSeconds;
        /// <summary>
        /// Process ID of the backend running the query.
        /// </summary>
        public readonly int? Pid;
        /// <summary>
        /// Full query text.
        /// </summary>
        public readonly string? Query;
        /// <summary>
        /// Current backend state.
        /// </summary>
        public readonly string? State;
        /// <summary>
        /// Time spent in the current state, in seconds.
        /// </summary>
        public readonly double? StateDurationSeconds;
        /// <summary>
        /// User running the query.
        /// </summary>
        public readonly string? User;
        /// <summary>
        /// Event the backend is waiting for.
        /// </summary>
        public readonly string? WaitEvent;
        /// <summary>
        /// Type of event the backend is waiting for.
        /// </summary>
        public readonly string? WaitEventType;

        [OutputConstructor]
        private PostgresActiveQuery(
            string? applicationName,

            string? client,

            string? database,

            double? durationSeconds,

            int? pid,

            string? query,

            string? state,

            double? stateDurationSeconds,

            string? user,

            string? waitEvent,

            string? waitEventType)
        {
            ApplicationName = applicationName;
            Client = client;
            Database = database;
            DurationSeconds = durationSeconds;
            Pid = pid;
            Query = query;
            State = state;
            StateDurationSeconds = stateDurationSeconds;
            User = user;
            WaitEvent = waitEvent;
            WaitEventType = waitEventType;
        }
    }
}
