// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PostgresV1.Outputs
{

    /// <summary>
    /// Query params for each of the operations of the resource.
    /// </summary>
    [OutputType]
    public sealed class PostgresUsersRotatePasswordQueryParams
    {
        /// <summary>
        /// Query params for the create operation.
        /// </summary>
        public readonly Outputs.PostgresUsersRotatePasswordCreateQueryParams? Create;

        [OutputConstructor]
        private PostgresUsersRotatePasswordQueryParams(Outputs.PostgresUsersRotatePasswordCreateQueryParams? create)
        {
            Create = create;
        }
    }
}
