// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.FlyMachines.PostgresV1.Outputs
{

    /// <summary>
    /// Pooled connection to the cluster node (through PgBouncer).
    /// </summary>
    [OutputType]
    public sealed class PostgresNodeEndpointsPooler
    {
        /// <summary>
        /// Hostname to connect to.
        /// </summary>
        public readonly string? Host;
        /// <summary>
        /// TCP port.
        /// </summary>
        public readonly int? Port;

        [OutputConstructor]
        private PostgresNodeEndpointsPooler(
            string? host,

            int? port)
        {
            Host = host;
            Port = port;
        }
    }
}
