# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._inputs import *

__all__ = [
    'GetPlatformRegionResult',
    'AwaitableGetPlatformRegionResult',
    'get_platform_region',
    'get_platform_region_output',
]

@pulumi.output_type
class GetPlatformRegionResult:
    def __init__(__self__, nearest=None, regions=None):
        if nearest and not isinstance(nearest, str):
            raise TypeError("Expected argument 'nearest' to be a str")
        pulumi.set(__self__, "nearest", nearest)
        if regions and not isinstance(regions, list):
            raise TypeError("Expected argument 'regions' to be a list")
        pulumi.set(__self__, "regions", regions)

    @_builtins.property
    @pulumi.getter
    def nearest(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "nearest")

    @_builtins.property
    @pulumi.getter
    def regions(self) -> Optional[Sequence['outputs.MainRegionRow']]:
        return pulumi.get(self, "regions")


class AwaitableGetPlatformRegionResult(GetPlatformRegionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPlatformRegionResult(
            nearest=self.nearest,
            regions=self.regions)


def get_platform_region(query_params: Optional[Union['GetPlatformRegionQueryParams', 'GetPlatformRegionQueryParamsDict']] = None,
                        opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPlatformRegionResult:
    """
    Use this data source to access information about an existing resource.

    :param Union['GetPlatformRegionQueryParams', 'GetPlatformRegionQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:platform/v1:getPlatformRegion', __args__, opts=opts, typ=GetPlatformRegionResult).value

    return AwaitableGetPlatformRegionResult(
        nearest=pulumi.get(__ret__, 'nearest'),
        regions=pulumi.get(__ret__, 'regions'))
def get_platform_region_output(query_params: pulumi.Input[Optional[Optional[Union['GetPlatformRegionQueryParams', 'GetPlatformRegionQueryParamsDict']]]] = None,
                               opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPlatformRegionResult]:
    """
    Use this data source to access information about an existing resource.

    :param Union['GetPlatformRegionQueryParams', 'GetPlatformRegionQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:platform/v1:getPlatformRegion', __args__, opts=opts, typ=GetPlatformRegionResult)
    return __ret__.apply(lambda __response__: GetPlatformRegionResult(
        nearest=pulumi.get(__response__, 'nearest'),
        regions=pulumi.get(__response__, 'regions')))
