# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ListMachinesOrgResult',
    'AwaitableListMachinesOrgResult',
    'list_machines_org',
    'list_machines_org_output',
]

@pulumi.output_type
class ListMachinesOrgResult:
    def __init__(__self__, error_regions=None, last_machine_id=None, last_updated_at=None, machines=None, next_cursor=None):
        if error_regions and not isinstance(error_regions, list):
            raise TypeError("Expected argument 'error_regions' to be a list")
        pulumi.set(__self__, "error_regions", error_regions)
        if last_machine_id and not isinstance(last_machine_id, str):
            raise TypeError("Expected argument 'last_machine_id' to be a str")
        pulumi.set(__self__, "last_machine_id", last_machine_id)
        if last_updated_at and not isinstance(last_updated_at, str):
            raise TypeError("Expected argument 'last_updated_at' to be a str")
        pulumi.set(__self__, "last_updated_at", last_updated_at)
        if machines and not isinstance(machines, list):
            raise TypeError("Expected argument 'machines' to be a list")
        pulumi.set(__self__, "machines", machines)
        if next_cursor and not isinstance(next_cursor, str):
            raise TypeError("Expected argument 'next_cursor' to be a str")
        pulumi.set(__self__, "next_cursor", next_cursor)

    @_builtins.property
    @pulumi.getter(name="errorRegions")
    def error_regions(self) -> Optional[Sequence[_builtins.str]]:
        return pulumi.get(self, "error_regions")

    @_builtins.property
    @pulumi.getter(name="lastMachineId")
    def last_machine_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "last_machine_id")

    @_builtins.property
    @pulumi.getter(name="lastUpdatedAt")
    def last_updated_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "last_updated_at")

    @_builtins.property
    @pulumi.getter
    def machines(self) -> Optional[Sequence['outputs.OrgMachine']]:
        return pulumi.get(self, "machines")

    @_builtins.property
    @pulumi.getter(name="nextCursor")
    def next_cursor(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "next_cursor")


class AwaitableListMachinesOrgResult(ListMachinesOrgResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListMachinesOrgResult(
            error_regions=self.error_regions,
            last_machine_id=self.last_machine_id,
            last_updated_at=self.last_updated_at,
            machines=self.machines,
            next_cursor=self.next_cursor)


def list_machines_org(org_slug: Optional[_builtins.str] = None,
                      opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListMachinesOrgResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str org_slug: Fly Organization Slug
    """
    __args__ = dict()
    __args__['orgSlug'] = org_slug
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:orgs/v1:listMachinesOrg', __args__, opts=opts, typ=ListMachinesOrgResult).value

    return AwaitableListMachinesOrgResult(
        error_regions=pulumi.get(__ret__, 'error_regions'),
        last_machine_id=pulumi.get(__ret__, 'last_machine_id'),
        last_updated_at=pulumi.get(__ret__, 'last_updated_at'),
        machines=pulumi.get(__ret__, 'machines'),
        next_cursor=pulumi.get(__ret__, 'next_cursor'))
def list_machines_org_output(org_slug: pulumi.Input[Optional[_builtins.str]] = None,
                             opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListMachinesOrgResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str org_slug: Fly Organization Slug
    """
    __args__ = dict()
    __args__['orgSlug'] = org_slug
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:orgs/v1:listMachinesOrg', __args__, opts=opts, typ=ListMachinesOrgResult)
    return __ret__.apply(lambda __response__: ListMachinesOrgResult(
        error_regions=pulumi.get(__response__, 'error_regions'),
        last_machine_id=pulumi.get(__response__, 'last_machine_id'),
        last_updated_at=pulumi.get(__response__, 'last_updated_at'),
        machines=pulumi.get(__response__, 'machines'),
        next_cursor=pulumi.get(__response__, 'next_cursor')))
