# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from ... import _utilities
from . import outputs
from ._enums import *
from ._inputs import *

__all__ = [
    'ListVolumesOrgResult',
    'AwaitableListVolumesOrgResult',
    'list_volumes_org',
    'list_volumes_org_output',
]

@pulumi.output_type
class ListVolumesOrgResult:
    def __init__(__self__, last_updated_at=None, last_volume_id=None, next_cursor=None, volumes=None):
        if last_updated_at and not isinstance(last_updated_at, str):
            raise TypeError("Expected argument 'last_updated_at' to be a str")
        pulumi.set(__self__, "last_updated_at", last_updated_at)
        if last_volume_id and not isinstance(last_volume_id, str):
            raise TypeError("Expected argument 'last_volume_id' to be a str")
        pulumi.set(__self__, "last_volume_id", last_volume_id)
        if next_cursor and not isinstance(next_cursor, str):
            raise TypeError("Expected argument 'next_cursor' to be a str")
        pulumi.set(__self__, "next_cursor", next_cursor)
        if volumes and not isinstance(volumes, list):
            raise TypeError("Expected argument 'volumes' to be a list")
        pulumi.set(__self__, "volumes", volumes)

    @_builtins.property
    @pulumi.getter(name="lastUpdatedAt")
    def last_updated_at(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "last_updated_at")

    @_builtins.property
    @pulumi.getter(name="lastVolumeId")
    def last_volume_id(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "last_volume_id")

    @_builtins.property
    @pulumi.getter(name="nextCursor")
    def next_cursor(self) -> Optional[_builtins.str]:
        return pulumi.get(self, "next_cursor")

    @_builtins.property
    @pulumi.getter
    def volumes(self) -> Optional[Sequence['outputs.OrgVolume']]:
        return pulumi.get(self, "volumes")


class AwaitableListVolumesOrgResult(ListVolumesOrgResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ListVolumesOrgResult(
            last_updated_at=self.last_updated_at,
            last_volume_id=self.last_volume_id,
            next_cursor=self.next_cursor,
            volumes=self.volumes)


def list_volumes_org(org_slug: Optional[_builtins.str] = None,
                     query_params: Optional[Union['ListVolumesOrgQueryParams', 'ListVolumesOrgQueryParamsDict']] = None,
                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableListVolumesOrgResult:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str org_slug: Fly Organization Slug
    :param Union['ListVolumesOrgQueryParams', 'ListVolumesOrgQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['orgSlug'] = org_slug
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('fly-machines:orgs/v1:listVolumesOrg', __args__, opts=opts, typ=ListVolumesOrgResult).value

    return AwaitableListVolumesOrgResult(
        last_updated_at=pulumi.get(__ret__, 'last_updated_at'),
        last_volume_id=pulumi.get(__ret__, 'last_volume_id'),
        next_cursor=pulumi.get(__ret__, 'next_cursor'),
        volumes=pulumi.get(__ret__, 'volumes'))
def list_volumes_org_output(org_slug: pulumi.Input[Optional[_builtins.str]] = None,
                            query_params: pulumi.Input[Optional[Optional[Union['ListVolumesOrgQueryParams', 'ListVolumesOrgQueryParamsDict']]]] = None,
                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ListVolumesOrgResult]:
    """
    Use this data source to access information about an existing resource.

    :param _builtins.str org_slug: Fly Organization Slug
    :param Union['ListVolumesOrgQueryParams', 'ListVolumesOrgQueryParamsDict'] query_params: Query params to send with the API request.
    """
    __args__ = dict()
    __args__['orgSlug'] = org_slug
    __args__['queryParams'] = query_params
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('fly-machines:orgs/v1:listVolumesOrg', __args__, opts=opts, typ=ListVolumesOrgResult)
    return __ret__.apply(lambda __response__: ListVolumesOrgResult(
        last_updated_at=pulumi.get(__response__, 'last_updated_at'),
        last_volume_id=pulumi.get(__response__, 'last_volume_id'),
        next_cursor=pulumi.get(__response__, 'next_cursor'),
        volumes=pulumi.get(__response__, 'volumes')))
